In [ ]:
# Re-import needed libraries after reset
import os
import shutil
from sklearn.model_selection import train_test_split
import pandas as pd

# ✅ Paths to the new dataset folders (7 class folders)
parent_dir = "/content/drive/MyDrive/hand-picked-data"
class_folders = [os.path.join(parent_dir, folder) for folder in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, folder))]

# ✅ Temporary merged directory
merged_dir = "/content/drive/MyDrive/hand-picked-data/dataset"
merged_images = os.path.join(merged_dir, "images")
merged_labels = os.path.join(merged_dir, "labels")
os.makedirs(merged_images, exist_ok=True)
os.makedirs(merged_labels, exist_ok=True)

# ✅ Merge images and labels
for folder in class_folders:
    img_dir = os.path.join(folder, "images")
    lbl_dir = os.path.join(folder, "labels")
    for fname in os.listdir(img_dir):
        if fname.endswith(".jpg"):
            shutil.copy(os.path.join(img_dir, fname), os.path.join(merged_images, fname))
            label_name = fname.replace(".jpg", ".txt")
            lbl_path = os.path.join(lbl_dir, label_name)
            if os.path.exists(lbl_path):
                shutil.copy(lbl_path, os.path.join(merged_labels, label_name))

# ✅ Split into 80:20
all_images = [f for f in os.listdir(merged_images) if f.endswith(".jpg")]
train_files, val_files = train_test_split(all_images, test_size=0.2, random_state=42)

# ✅ Output directories
split_base = "/content/drive/MyDrive/hand-picked-data/Final_Split_New_Datasets"
train_img_dir = os.path.join(split_base, "train/images")
train_lbl_dir = os.path.join(split_base, "train/labels")
val_img_dir = os.path.join(split_base, "val/images")
val_lbl_dir = os.path.join(split_base, "val/labels")

os.makedirs(train_img_dir, exist_ok=True)
os.makedirs(train_lbl_dir, exist_ok=True)
os.makedirs(val_img_dir, exist_ok=True)
os.makedirs(val_lbl_dir, exist_ok=True)

# ✅ Copy files
for f in train_files:
    shutil.copy(os.path.join(merged_images, f), os.path.join(train_img_dir, f))
    shutil.copy(os.path.join(merged_labels, f.replace(".jpg", ".txt")), os.path.join(train_lbl_dir, f.replace(".jpg", ".txt")))

for f in val_files:
    shutil.copy(os.path.join(merged_images, f), os.path.join(val_img_dir, f))
    shutil.copy(os.path.join(merged_labels, f.replace(".jpg", ".txt")), os.path.join(val_lbl_dir, f.replace(".jpg", ".txt")))

# ✅ Summary
summary = pd.DataFrame({
    "Total Images": [len(all_images)],
    "Training Set": [len(train_files)],
    "Validation Set": [len(val_files)],
    "Class Folders Merged": [len(class_folders)]
})

import pandas as pd
from IPython.display import display

summary = pd.DataFrame({
    "Total Clean Images": [len(all_images)],
    "Training Set": [len(train_imgs)],
    "Validation Set": [len(val_imgs)],
    "Faulty Images Removed": [len(faulty_ids)]
})

display(summary)

KeyboardInterrupt:

In [ ]:
import os
import shutil
from sklearn.model_selection import train_test_split
import pandas as pd
from IPython.display import display

# ✅ Root path where class folders are located
parent_dir = "/content/drive/MyDrive/hand-picked-data"
merged_dir = os.path.join(parent_dir, "dataset")

# ✅ Clean up old merged folder if it exists
if os.path.exists(merged_dir):
    shutil.rmtree(merged_dir)

# ✅ Recreate merged dataset folders
merged_images = os.path.join(merged_dir, "images")
merged_labels = os.path.join(merged_dir, "labels")
os.makedirs(merged_images, exist_ok=True)
os.makedirs(merged_labels, exist_ok=True)

# ✅ Prepare list of valid class folders (exclude "dataset")
class_folders = [
    os.path.join(parent_dir, folder)
    for folder in os.listdir(parent_dir)
    if os.path.isdir(os.path.join(parent_dir, folder)) and folder != "dataset"
]

print("📦 Merging image-label pairs...")

merged_count = 0
skipped_missing_label = 0
skipped_structure = 0

for folder in class_folders:
    img_dir = os.path.join(folder, "images")
    lbl_dir = os.path.join(folder, "labels")

    if not os.path.exists(img_dir) or not os.path.exists(lbl_dir):
        print(f"⚠️ Skipped: {folder} — Missing 'images/' or 'labels/'")
        skipped_structure += 1
        continue

    for fname in os.listdir(img_dir):
        if fname.endswith(".jpg"):
            img_src = os.path.join(img_dir, fname)
            lbl_src = os.path.join(lbl_dir, fname.replace(".jpg", ".txt"))

            if not os.path.exists(lbl_src):
                skipped_missing_label += 1
                continue

            shutil.copy(img_src, os.path.join(merged_images, fname))
            shutil.copy(lbl_src, os.path.join(merged_labels, fname.replace(".jpg", ".txt")))
            merged_count += 1

print(f"✅ Merged {merged_count} image-label pairs")
print(f"⚠️ Skipped {skipped_missing_label} files with missing labels")
print(f"⚠️ Skipped {skipped_structure} folders with missing structure")

# ✅ Split merged dataset into train/val (80:20)
all_images = [f for f in os.listdir(merged_images) if f.endswith(".jpg")]
train_files, val_files = train_test_split(all_images, test_size=0.2, random_state=42)

# ✅ Create final output split directories
split_base = os.path.join(parent_dir, "Final_Split_New_Datasets")
for split in ["train/images", "train/labels", "val/images", "val/labels"]:
    os.makedirs(os.path.join(split_base, split), exist_ok=True)

# ✅ Copy to train
for f in train_files:
    img_path = os.path.join(merged_images, f)
    lbl_path = os.path.join(merged_labels, f.replace(".jpg", ".txt"))
    if os.path.exists(img_path) and os.path.exists(lbl_path):
        shutil.copy(img_path, os.path.join(split_base, "train/images", f))
        shutil.copy(lbl_path, os.path.join(split_base, "train/labels", f.replace(".jpg", ".txt")))

# ✅ Copy to val
for f in val_files:
    img_path = os.path.join(merged_images, f)
    lbl_path = os.path.join(merged_labels, f.replace(".jpg", ".txt"))
    if os.path.exists(img_path) and os.path.exists(lbl_path):
        shutil.copy(img_path, os.path.join(split_base, "val/images", f))
        shutil.copy(lbl_path, os.path.join(split_base, "val/labels", f.replace(".jpg", ".txt")))

# ✅ Summary
summary = pd.DataFrame({
    "Total Merged Images": [len(all_images)],
    "Training Set": [len(train_files)],
    "Validation Set": [len(val_files)],
    "Valid Class Folders": [len(class_folders) - skipped_structure],
    "Skipped (missing labels)": [skipped_missing_label]
})

display(summary)

📦 Merging image-label pairs...
⚠️ Skipped: /content/drive/MyDrive/hand-picked-data/images — Missing 'images/' or 'labels/'
⚠️ Skipped: /content/drive/MyDrive/hand-picked-data/labels — Missing 'images/' or 'labels/'
⚠️ Skipped: /content/drive/MyDrive/hand-picked-data/Final_Split_New_Datasets — Missing 'images/' or 'labels/'
✅ Merged 1388 image-label pairs
⚠️ Skipped 0 files with missing labels
⚠️ Skipped 3 folders with missing structure

,Total Merged Images,Training Set,Validation Set,Valid Class Folders,Skipped (missing labels)
0,1388,1110,278,7,0

In [ ]:
import os

# Define training script content
from ultralytics import YOLO
import os
import cv2
from tqdm import tqdm
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

# ✅ Paths
yaml_path = "/content/drive/MyDrive/hand-picked-data/Final_Split_New_Datasets/config.yaml"
model_path = "models/yolo11n.pt"
output_dir = "/content/drive/MyDrive/YOLOv11_Results/Handpicked_YOLOv11_1000x1000"

val_images_path = "/content/drive/MyDrive/hand-picked-data/Final_Split_New_Datasets/val/images"
val_labels_path = "/content/drive/MyDrive/hand-picked-data/Final_Split_New_Datasets/val/labels"

# ✅ Train YOLOv11
model = YOLO(model_path)
model.train(
    data=yaml_path,
    epochs=300,
    imgsz=1000,
    patience=30,
    device="cuda",
    project=output_dir,
    name="train_1000x1000",
    save=True,
    resume=True
)

# ✅ Evaluation
val_results = model.val(data=yaml_path, save_json=True)

# ✅ Output folders for errors
fp_dir = os.path.join(output_dir, "false_positives")
fn_dir = os.path.join(output_dir, "false_negatives")
mc_dir = os.path.join(output_dir, "misclassified")
os.makedirs(fp_dir, exist_ok=True)
os.makedirs(fn_dir, exist_ok=True)
os.makedirs(mc_dir, exist_ok=True)

# ✅ Class names
class_names = {
    0: "Formicidae", 1: "Brachycera", 2: "Nematocera", 3: "Collembola",
    4: "Arachnida", 5: "Aphididae", 6: "Hymenoptera", 7: "Syrphidae"
}

# ✅ IOU calculation
def compute_iou(box1, box2):
    xA = max(box1[0], box2[0])
    yA = max(box1[1], box2[1])
    xB = min(box1[2], box2[2])
    yB = min(box1[3], box2[3])
    inter = max(0, xB - xA) * max(0, yB - yA)
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    return inter / (area1 + area2 - inter + 1e-6)

print("🔍 Evaluating validation set...")
y_true = []
y_pred = []

for img_name in tqdm(os.listdir(val_images_path)):
    if not img_name.endswith(".jpg"):
        continue

    img_path = os.path.join(val_images_path, img_name)
    label_path = os.path.join(val_labels_path, img_name.replace(".jpg", ".txt"))
    image = cv2.imread(img_path)
    height, width = image.shape[:2]

    results = model(img_path)[0]
    pred_boxes = results.boxes.xyxy.cpu().numpy()
    pred_classes = results.boxes.cls.cpu().numpy()

    gt_boxes = []
    gt_classes = []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                x1 = int((x - w / 2) * width)
                y1 = int((y - h / 2) * height)
                x2 = int((x + w / 2) * width)
                y2 = int((y + h / 2) * height)
                gt_boxes.append([x1, y1, x2, y2])
                gt_classes.append(int(cls))

    matched_pred = set()
    matched_gt = set()

    for i, pbox in enumerate(pred_boxes):
        px1, py1, px2, py2 = map(int, pbox[:4])
        pred_cls = int(pred_classes[i])
        for j, gtbox in enumerate(gt_boxes):
            iou = compute_iou(pbox[:4], gtbox)
            if iou > 0.3:
                matched_pred.add(i)
                matched_gt.add(j)
                if pred_cls != gt_classes[j]:
                    img_copy = image.copy()
                    gx1, gy1, gx2, gy2 = gtbox
                    cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (0, 255, 0), 2)
                    cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
                    cv2.putText(img_copy, f"Pred: {class_names.get(pred_cls, pred_cls)}", (px1, py1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
                    cv2.putText(img_copy, f"GT: {class_names.get(gt_classes[j], gt_classes[j])}", (gx1, gy1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
                    cv2.imwrite(os.path.join(mc_dir, f"mc_{img_name}"), img_copy)
                break

    for i, pbox in enumerate(pred_boxes):
        if i not in matched_pred:
            y_true.append(0)
            y_pred.append(1)
            px1, py1, px2, py2 = map(int, pbox[:4])
            pred_cls = int(pred_classes[i])
            img_copy = image.copy()
            cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
            cv2.putText(img_copy, f"FP: {class_names.get(pred_cls, pred_cls)}", (px1, py1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
            cv2.imwrite(os.path.join(fp_dir, f"fp_{img_name}"), img_copy)

    for j, gtbox in enumerate(gt_boxes):
        if j not in matched_gt:
            y_true.append(1)
            y_pred.append(0)
            gx1, gy1, gx2, gy2 = gtbox
            img_copy = image.copy()
            cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (255, 0, 0), 2)
            cv2.putText(img_copy, "FN", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            cv2.imwrite(os.path.join(fn_dir, f"fn_{img_name}"), img_copy)

# ✅ Metrics
precision = precision_score(y_true, y_pred) * 100
recall = recall_score(y_true, y_pred) * 100
f1 = f1_score(y_true, y_pred) * 100

print(f"✅ Evaluation Complete:")
print(f"Precision: {precision:.2f}%")
print(f"Recall:    {recall:.2f}%")
print(f"F1 Score:  {f1:.2f}%")
print(f"→ False Positives saved to: {fp_dir}")
print(f"→ False Negatives saved to: {fn_dir}")
print(f"→ Misclassifications saved to: {mc_dir}")


# Save to .py script so user can run it
script_path = "/mnt/data/train_and_eval_yolov11n_1000x1000.py"
with open(script_path, "w") as f:
    f.write(script_content)

script_path

In [ ]:
import os

# Set base directory for dataset
base_dir = "/content/drive/MyDrive/hand-picked-data"

# Extension filters
image_ext = ".jpg"
label_ext = ".txt"

report = []

# Loop through each class folder
for class_name in os.listdir(base_dir):
    class_path = os.path.join(base_dir, class_name)
    if not os.path.isdir(class_path):
        continue

    img_dir = os.path.join(class_path, "images")
    lbl_dir = os.path.join(class_path, "labels")

    if not os.path.exists(img_dir) or not os.path.exists(lbl_dir):
        print(f"⚠️ Missing 'images/' or 'labels/' in: {class_name}")
        continue

    img_files = set(os.path.splitext(f)[0] for f in os.listdir(img_dir) if f.endswith(image_ext))
    lbl_files = set(os.path.splitext(f)[0] for f in os.listdir(lbl_dir) if f.endswith(label_ext))

    unmatched_imgs = img_files - lbl_files
    unmatched_lbls = lbl_files - img_files
    matched = img_files & lbl_files

    report.append({
        "Class": class_name,
        "Image Count": len(img_files),
        "Label Count": len(lbl_files),
        "Matched": len(matched),
        "Images w/o Labels": len(unmatched_imgs),
        "Labels w/o Images": len(unmatched_lbls)
    })

    if unmatched_imgs:
        print(f"🖼️ Images without labels in '{class_name}': {sorted(unmatched_imgs)}")
    if unmatched_lbls:
        print(f"📝 Labels without images in '{class_name}': {sorted(unmatched_lbls)}")

import pandas as pd
df = pd.DataFrame(report)
print("\n📊 Dataset Integrity Summary:")
print(df)

📝 Labels without images in 'Arachnida': ['11_364515', '11_364516', '11_364517', '11_364518', '11_364519', '11_364521', '11_364522', '11_364523', '11_364524', '11_364525', '11_364528', '11_364530', '11_364531', '11_364532', '11_364533', '11_364534', '11_364535', '11_364536', '11_364537', '11_364538', '11_364539', '11_364540', '11_364541', '11_364542', '11_364543', '11_364544', '11_364545', '11_364546', '11_364547', '11_364548', '11_364549', '11_364550', '11_364553', '11_364554', '11_364555', '11_364560', '11_364586', '11_364588', '11_364596', '11_364607', '11_364619', '11_364620', '11_364628', '11_364631', '11_364632', '11_364633', '11_364639', '11_364655', '11_364658', '11_364666', '11_364669', '265_489208', '265_769887', '793_1801365', '793_1801375', '827_1542128', '827_1542129', '827_1542130', '827_1542133', '827_1542137', '827_1542139', '827_1542140', '827_1542141', '827_1542144', '827_1542145', '827_1542147', '827_1542149', '827_1591071']
📝 Labels without images in 'Brachycera': ['298_1108925', '298_1108953', '298_1109049', '298_1109055', '298_1109062', '298_1408909', '298_868478', '298_868479', '298_868480', '298_880379', '298_950689', '298_981530', '298_981531', '298_981532', '298_981533', '793_1538263', '793_1538270', '793_1538305', '793_1706507', '793_1706508', '793_1706509', '793_1706512', '827_1477793']
📝 Labels without images in 'Apoidea': ['298_1017615', '298_1017617', '298_1096742', '298_1306070', '298_1306072', '298_1306076', '298_1306082', '298_885353', '298_981474', '793_1674579', '827_1547897', '827_1547899', '827_1547906', '827_1547910', '827_1547911', '991_1780273', '991_1813212', '991_1813216', '991_1818154', '991_1819856']
📝 Labels without images in 'Formicidae': ['793_1879875', '826_1865193', '826_1865197', '827_1558491', '827_1558542', '827_1559290', '827_1577538', '827_1627285', '827_1682663', '827_1707928']
📝 Labels without images in 'Coleoptera': ['298_1020962', '298_1021031', '298_1021033', '298_765051', '298_765057', '298_765058', '298_765059', '298_843520', '298_843521', '298_843524', '793_1732376', '793_1736689', '793_1869263', '827_1542129', '827_1542130', '827_1542133', '827_1542137', '827_1542139', '827_1542140', '827_1542141', '827_1542160', '827_1673017', '827_1673018', '827_1673019', '827_1673020']
📝 Labels without images in 'Syraphidae': ['298_756633', '298_756638']
📝 Labels without images in 'Nematocera': ['265_1032407', '265_1247269', '265_1296677', '265_1296678', '265_541860', '265_541861', '265_541902', '265_541946', '265_541949', '265_576678', '265_650220', '265_650221', '265_650222', '265_650223', '265_650224', '265_661413', '265_661431', '265_661442', '265_661443', '265_661445', '265_661446', '265_661450', '265_661451', '265_661452', '265_661453', '265_661454', '265_661455', '265_661456', '265_661457', '265_661458', '265_661459', '265_661460', '265_661461', '265_661462', '265_661463', '265_661464', '265_661465', '265_661466', '265_661467', '265_661468', '265_661469', '265_661470', '265_661471', '265_661472', '265_661473', '265_661474', '265_661475', '265_661476', '265_661477', '265_661478', '265_661479', '265_661480', '265_661482', '265_661484', '265_661485', '265_661486', '265_661487', '265_931979', '265_931981', '265_934400', '265_937073', '298_943484', '298_943485', '298_943658', '298_944273', '298_944274', '298_944356', '298_944357', '298_944358', '298_944359', '298_944361', '298_944365', '298_944386', '298_944399', '298_944400', '298_944423', '298_944427', '298_969135', '298_969194', '298_969544', '298_970634', '298_970635', '298_970685', '298_970687', '298_970748', '562_1573887', '562_1577929', '562_1577993', '562_1577995', '562_1577998', '562_1582026', '562_1582029', '562_1582030', '562_1585933', '562_1596224', '562_1604601', '562_1604625', '562_1604626', '562_1604627', '562_1606002', '562_1707007', '562_1719292', '562_1719297', '562_1719298', '562_1722956', '562_1723865', '562_1726059', '562_1788493', '562_1910671', '562_1910999', '562_1911879', '562_1914869', '562_1942740', '562_1942761', '793_1659843', '793_1659844', '793_1659846', '793_1701705', '827_1551876', '827_1703707', '925_2003491']

📊 Dataset Integrity Summary:
        Class  Image Count  Label Count  Matched  Images w/o Labels  \
0   Arachnida           65          133       65                  0
1  Brachycera          106          129      106                  0
2     Apoidea           52           72       52                  0
3  Formicidae          337          347      337                  0
4  Coleoptera          258          283      258                  0
5  Syraphidae          132          134      132                  0
6  Nematocera          438          559      438                  0
7     dataset         1388         1388     1388                  0

   Labels w/o Images
0                 68
1                 23
2                 20
3                 10
4                 25
5                  2
6                121
7                  0

In [ ]:
import os

# ✅ Path to your dataset containing the class folders
base_dir = "/content/drive/MyDrive/hand-picked-data"

# ✅ Classes you want to process (excluding "dataset" and any already merged ones)
class_folders = [d for d in os.listdir(base_dir)
                 if os.path.isdir(os.path.join(base_dir, d)) and d != "dataset"]

removed = {}

for class_name in class_folders:
    lbl_dir = os.path.join(base_dir, class_name, "labels")
    img_dir = os.path.join(base_dir, class_name, "images")

    if not os.path.exists(lbl_dir) or not os.path.exists(img_dir):
        continue

    label_files = [f for f in os.listdir(lbl_dir) if f.endswith(".txt")]
    img_files = set(os.path.splitext(f)[0] for f in os.listdir(img_dir) if f.endswith(".jpg"))

    count = 0
    for label_file in label_files:
        label_id = os.path.splitext(label_file)[0]
        if label_id not in img_files:
            os.remove(os.path.join(lbl_dir, label_file))
            count += 1

    removed[class_name] = count

# ✅ Report
print("\n🧹 Removed orphan labels:")
for k, v in removed.items():
    print(f"{k}: {v} orphan label files removed")

🧹 Removed orphan labels:
Arachnida: 68 orphan label files removed
Brachycera: 23 orphan label files removed
Apoidea: 20 orphan label files removed
Formicidae: 10 orphan label files removed
Coleoptera: 25 orphan label files removed
Syraphidae: 2 orphan label files removed
Nematocera: 121 orphan label files removed

In [ ]:
import os
import shutil
from sklearn.model_selection import train_test_split
import pandas as pd
from tqdm import tqdm

# ✅ Update this to your actual dataset base path
base_path = "/content/drive/MyDrive/hand-picked-data"

# ✅ Class folder to ID mapping
class_mapping = {
    "Apoidea": 0,
    "Arachnida": 1,
    "Brachycera": 2,
    "Coleoptera": 3,
    "Formicidae": 4,
    "Formicidae": 5,
    "Syraphidae": 6
}

# ✅ Output merged & split paths
output_base = os.path.join(base_path, "2024-04-11-reindexed_and_split")
merged_images_dir = os.path.join(output_base, "merged/images")
merged_labels_dir = os.path.join(output_base, "merged/labels")
split_train_img = os.path.join(output_base, "train/images")
split_train_lbl = os.path.join(output_base, "train/labels")
split_val_img = os.path.join(output_base, "val/images")
split_val_lbl = os.path.join(output_base, "val/labels")

# ✅ Create directories
for d in [merged_images_dir, merged_labels_dir, split_train_img, split_train_lbl, split_val_img, split_val_lbl]:
    os.makedirs(d, exist_ok=True)

# ✅ Reindex and copy
print("🔁 Rewriting label files with new indices...")
for class_name, class_id in class_mapping.items():
    class_path = os.path.join(base_path, class_name)
    img_dir = os.path.join(class_path, "images")
    lbl_dir = os.path.join(class_path, "labels")

    for fname in tqdm(os.listdir(img_dir), desc=f"Processing {class_name}"):
        if not fname.endswith(".jpg"):
            continue
        img_src = os.path.join(img_dir, fname)
        lbl_src = os.path.join(lbl_dir, fname.replace(".jpg", ".txt"))

        img_dst = os.path.join(merged_images_dir, fname)
        lbl_dst = os.path.join(merged_labels_dir, fname.replace(".jpg", ".txt"))

        shutil.copy(img_src, img_dst)

        if os.path.exists(lbl_src):
            with open(lbl_src, 'r') as f:
                lines = f.readlines()

            with open(lbl_dst, 'w') as f_out:
                for line in lines:
                    parts = line.strip().split()
                    if len(parts) == 5:
                        parts[0] = str(class_id)
                        f_out.write(" ".join(parts) + "\n")

print("✅ Reindexing and merging completed.")

# ✅ 80:20 Train-Val Split
all_images = [f for f in os.listdir(merged_images_dir) if f.endswith(".jpg")]
train_imgs, val_imgs = train_test_split(all_images, test_size=0.2, random_state=42)

# ✅ Copy train files
for f in train_imgs:
    shutil.copy(os.path.join(merged_images_dir, f), os.path.join(split_train_img, f))
    shutil.copy(os.path.join(merged_labels_dir, f.replace(".jpg", ".txt")), os.path.join(split_train_lbl, f.replace(".jpg", ".txt")))

# ✅ Copy val files
for f in val_imgs:
    shutil.copy(os.path.join(merged_images_dir, f), os.path.join(split_val_img, f))
    shutil.copy(os.path.join(merged_labels_dir, f.replace(".jpg", ".txt")), os.path.join(split_val_lbl, f.replace(".jpg", ".txt")))

# ✅ Summary
summary = pd.DataFrame({
    "Total Merged Images": [len(all_images)],
    "Training Set": [len(train_imgs)],
    "Validation Set": [len(val_imgs)],
    "Classes Processed": [len(class_mapping)]
})
print("\n📊 Dataset Preparation Summary:")
print(summary.to_string(index=False))

🔁 Rewriting label files with new indices...

Processing Apoidea: 100%|██████████| 53/53 [00:29<00:00,  1.78it/s]
Processing Arachnida: 100%|██████████| 66/66 [00:32<00:00,  2.03it/s]
Processing Brachycera: 100%|██████████| 107/107 [00:30<00:00,  3.51it/s]
Processing Coleoptera: 100%|██████████| 259/259 [01:05<00:00,  3.97it/s]
Processing Formicidae: 100%|██████████| 338/338 [01:25<00:00,  3.95it/s]
Processing Nematocera: 100%|██████████| 439/439 [01:51<00:00,  3.94it/s]
Processing Syraphidae: 100%|██████████| 133/133 [00:34<00:00,  3.83it/s]

✅ Reindexing and merging completed.

📊 Dataset Preparation Summary:
 Total Merged Images  Training Set  Validation Set  Classes Processed
                1388          1110             278                  7

In [ ]:
!pip install ultralytics
import os
import cv2
import numpy as np
from tqdm import tqdm
from ultralytics import YOLO
from sklearn.metrics import precision_score, recall_score, f1_score

# ✅ Paths
yaml_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/config.yaml"
model_path = "models/yolo11n.pt"
output_dir = "/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run"

# ✅ Train YOLOv11n model (no resume)
model = YOLO(model_path)
model.train(
    data=yaml_path,
    epochs=300,
    imgsz=1000,
    patience=20,
    save=True,
    project=output_dir,
    name="train_yolo11n_reindexed"
)

# ✅ Validation and Evaluation
val_images_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images"
val_labels_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels"

fp_dir = os.path.join(output_dir, "false_positives")
fn_dir = os.path.join(output_dir, "false_negatives")
mc_dir = os.path.join(output_dir, "misclassified")
os.makedirs(fp_dir, exist_ok=True)
os.makedirs(fn_dir, exist_ok=True)
os.makedirs(mc_dir, exist_ok=True)

class_names = {
    0: "Apoidea", 1: "Arachnida", 2: "Brachycera", 3: "Coleoptera",
    4: "Formicidae", 5: "Nematocera", 6: "Syraphidae"
}

def compute_iou(box1, box2):
    xA, yA = max(box1[0], box2[0]), max(box1[1], box2[1])
    xB, yB = min(box1[2], box2[2]), min(box1[3], box2[3])
    inter = max(0, xB - xA) * max(0, yB - yA)
    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])
    return inter / (area1 + area2 - inter + 1e-6)

print("🔍 Evaluating on validation set...")
y_true, y_pred = [], []

for img_name in tqdm(os.listdir(val_images_path)):
    if not img_name.endswith(".jpg"):
        continue

    img_path = os.path.join(val_images_path, img_name)
    label_path = os.path.join(val_labels_path, img_name.replace(".jpg", ".txt"))
    image = cv2.imread(img_path)
    height, width = image.shape[:2]

    results = model(img_path, conf=0.25, iou=0.7)[0]
    pred_boxes = results.boxes.xyxy.cpu().numpy()
    pred_classes = results.boxes.cls.cpu().numpy()

    gt_boxes, gt_classes = [], []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                x1 = int((x - w/2) * width)
                y1 = int((y - h/2) * height)
                x2 = int((x + w/2) * width)
                y2 = int((y + h/2) * height)
                gt_boxes.append([x1, y1, x2, y2])
                gt_classes.append(int(cls))

    matched_pred = set()
    matched_gt = set()

    for i, pbox in enumerate(pred_boxes):
        px1, py1, px2, py2 = map(int, pbox[:4])
        pred_cls = int(pred_classes[i])
        for j, gtbox in enumerate(gt_boxes):
            iou = compute_iou(pbox[:4], gtbox)
            if iou > 0.3:
                matched_pred.add(i)
                matched_gt.add(j)
                if pred_cls != gt_classes[j]:
                    img_copy = image.copy()
                    gx1, gy1, gx2, gy2 = gtbox
                    cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (0, 255, 0), 2)
                    cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
                    cv2.putText(img_copy, f"Pred: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
                    cv2.putText(img_copy, f"GT: {class_names.get(gt_classes[j])}", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)
                    cv2.imwrite(os.path.join(mc_dir, f"mc_{img_name}"), img_copy)
                break

    for i, pbox in enumerate(pred_boxes):
        if i not in matched_pred:
            y_true.append(0)
            y_pred.append(1)
            px1, py1, px2, py2 = map(int, pbox[:4])
            pred_cls = int(pred_classes[i])
            img_copy = image.copy()
            cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
            cv2.putText(img_copy, f"FP: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
            cv2.imwrite(os.path.join(fp_dir, f"fp_{img_name}"), img_copy)

    for j, gtbox in enumerate(gt_boxes):
        if j not in matched_gt:
            y_true.append(1)
            y_pred.append(0)
            gx1, gy1, gx2, gy2 = gtbox
            img_copy = image.copy()
            cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (255, 0, 0), 2)
            cv2.putText(img_copy, "FN", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            cv2.imwrite(os.path.join(fn_dir, f"fn_{img_name}"), img_copy)

# ✅ Summary metrics
precision = precision_score(y_true, y_pred) * 100
recall = recall_score(y_true, y_pred) * 100
f1 = f1_score(y_true, y_pred) * 100

print("\n✅ Evaluation Summary:")
print(f"Precision: {precision:.2f}%")
print(f"Recall:    {recall:.2f}%")
print(f"F1 Score:  {f1:.2f}%")
print(f"→ FP saved to: {fp_dir}")
print(f"→ FN saved to: {fn_dir}")
print(f"→ MC saved to: {mc_dir}")

Collecting ultralytics
  Downloading ultralytics-8.3.104-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy<=2.1.1,>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.14.1)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.2.2)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.13.2)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.14-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.1.31)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Downloading ultralytics-8.3.104-py3-none-any.whl (994 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 994.1/994.1 kB 18.8 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 106.8 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 82.2 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 58.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.9 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 90.0 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.14-py3-none-any.whl (26 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.104 ultralytics-thop-2.0.14
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'models/yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 124MB/s]

Ultralytics 8.3.104 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: task=detect, mode=train, model=models/yolo11n.pt, data=/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/config.yaml, epochs=300, time=None, patience=20, batch=16, imgsz=1000, save=True, save_period=-1, cache=False, device=None, workers=8, project=/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run, name=train_yolo11n_reindexed, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...

100%|██████████| 755k/755k [00:00<00:00, 19.6MB/s]

Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    432037  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]
YOLO11n summary: 181 layers, 2,591,205 parameters, 2,591,189 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 110MB/s]

AMP: checks passed ✅
WARNING ⚠️ imgsz=[1000] must be multiple of max stride 32, updating to [1024]

train: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/train/labels... 1110 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1110/1110 [08:33<00:00,  2.16it/s]

train: New cache created: /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels... 278 images, 0 backgrounds, 0 corrupt: 100%|██████████| 278/278 [01:54<00:00,  2.42it/s]

val: New cache created: /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels.cache
Plotting labels to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/300      6.04G      2.168      7.879      1.807          9       1024: 100%|██████████| 70/70 [01:16<00:00,  1.09s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:11<00:00,  1.26s/it]

                   all        278        284    0.00404      0.864      0.139     0.0634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/300      7.42G      1.618       5.44      1.452          3       1024: 100%|██████████| 70/70 [01:12<00:00,  1.04s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:10<00:00,  1.21s/it]

                   all        278        284      0.431      0.308      0.311      0.171

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/300      7.44G      1.628      4.414        1.5          7       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:10<00:00,  1.15s/it]

                   all        278        284      0.531      0.366      0.337      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/300      7.45G      1.575      3.764      1.504          8       1024: 100%|██████████| 70/70 [01:09<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.34it/s]

                   all        278        284      0.506      0.495      0.457       0.26

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/300      7.46G       1.59      3.281       1.48          7       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.20it/s]

                   all        278        284      0.354       0.56      0.478       0.26

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/300      7.48G      1.537      2.888       1.45          5       1024: 100%|██████████| 70/70 [01:09<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.28it/s]

                   all        278        284       0.47      0.513      0.466      0.267

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/300      7.49G      1.515      2.455      1.487         10       1024: 100%|██████████| 70/70 [01:12<00:00,  1.03s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.08s/it]

                   all        278        284      0.571      0.563      0.525      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/300      7.51G      1.493      2.291      1.468          5       1024: 100%|██████████| 70/70 [01:12<00:00,  1.04s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.04s/it]

                   all        278        284      0.458      0.501      0.495      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/300      7.52G      1.464       2.08      1.433          7       1024: 100%|██████████| 70/70 [01:10<00:00,  1.01s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:11<00:00,  1.24s/it]

                   all        278        284      0.662      0.545      0.603      0.348

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/300      7.53G      1.435       1.91      1.407          8       1024: 100%|██████████| 70/70 [01:09<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:10<00:00,  1.18s/it]

                   all        278        284       0.58      0.547      0.587      0.348

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/300      7.55G      1.436      1.819      1.412          4       1024: 100%|██████████| 70/70 [01:19<00:00,  1.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:11<00:00,  1.27s/it]

                   all        278        284       0.65       0.48      0.565      0.319

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/300      7.57G      1.424      1.728       1.39          5       1024: 100%|██████████| 70/70 [01:11<00:00,  1.03s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:11<00:00,  1.27s/it]

                   all        278        284      0.727      0.593      0.651      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/300      7.58G      1.429      1.692      1.414         10       1024: 100%|██████████| 70/70 [01:18<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:13<00:00,  1.49s/it]

                   all        278        284      0.602      0.596      0.631      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/300      7.59G      1.399      1.586      1.407         10       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:11<00:00,  1.32s/it]

                   all        278        284      0.811       0.58      0.678      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/300      7.61G       1.41      1.502      1.397          9       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.08it/s]

                   all        278        284      0.615      0.679      0.709      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/300      7.62G      1.362      1.485       1.37         11       1024: 100%|██████████| 70/70 [01:11<00:00,  1.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.08s/it]

                   all        278        284      0.742      0.666      0.717       0.44

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/300      7.64G      1.399      1.424      1.413          6       1024: 100%|██████████| 70/70 [01:14<00:00,  1.07s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.46it/s]

                   all        278        284      0.757      0.712      0.767      0.451

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/300      7.65G      1.341      1.352      1.362         15       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.08it/s]

                   all        278        284      0.874      0.629      0.747      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/300      7.67G      1.347      1.322      1.379         11       1024: 100%|██████████| 70/70 [01:12<00:00,  1.03s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:10<00:00,  1.13s/it]

                   all        278        284      0.793      0.608      0.717      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/300      7.69G      1.343      1.312      1.376          7       1024: 100%|██████████| 70/70 [01:11<00:00,  1.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.29it/s]

                   all        278        284       0.73      0.743      0.769      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/300       7.7G      1.338      1.283      1.372         17       1024: 100%|██████████| 70/70 [01:18<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:12<00:00,  1.35s/it]

                   all        278        284      0.757      0.611      0.673      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/300      7.71G        1.3      1.245      1.334          7       1024: 100%|██████████| 70/70 [01:12<00:00,  1.04s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.12it/s]

                   all        278        284      0.825      0.663      0.743      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/300      7.73G      1.318      1.248      1.348         12       1024: 100%|██████████| 70/70 [01:15<00:00,  1.09s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:10<00:00,  1.20s/it]

                   all        278        284      0.799      0.653      0.761      0.452

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/300      7.74G      1.327      1.228      1.367         11       1024: 100%|██████████| 70/70 [01:20<00:00,  1.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.26it/s]

                   all        278        284      0.696      0.653      0.697      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/300      7.76G      1.293      1.173      1.337          9       1024: 100%|██████████| 70/70 [01:07<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.18it/s]

                   all        278        284      0.798      0.692      0.792      0.488

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/300      7.77G      1.274      1.145      1.326         13       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.33it/s]

                   all        278        284      0.682      0.774      0.731      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/300      7.79G      1.263      1.095      1.316         10       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.08s/it]

                   all        278        284       0.76      0.625      0.713      0.426

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/300       7.8G      1.261       1.13      1.324          4       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.30it/s]

                   all        278        284      0.742      0.663      0.717      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/300      7.82G      1.281      1.065      1.325          7       1024: 100%|██████████| 70/70 [01:09<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.18it/s]

                   all        278        284      0.806      0.728      0.783      0.465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/300      7.83G       1.25      1.118      1.309          9       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.00s/it]

                   all        278        284      0.868      0.714      0.825      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/300      7.85G      1.244      1.061      1.312         10       1024: 100%|██████████| 70/70 [01:14<00:00,  1.07s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.23it/s]

                   all        278        284       0.85      0.706      0.812      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/300      7.86G      1.234      1.037      1.295         11       1024: 100%|██████████| 70/70 [01:11<00:00,  1.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.32it/s]

                   all        278        284        0.8      0.703      0.783      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/300      7.88G      1.242      1.071      1.312          7       1024: 100%|██████████| 70/70 [01:06<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.11it/s]

                   all        278        284      0.859      0.729      0.803      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/300      7.89G      1.228      1.023      1.301         10       1024: 100%|██████████| 70/70 [01:07<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.13it/s]

                   all        278        284      0.852      0.647      0.792      0.462

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/300      7.91G      1.235          1      1.312          9       1024: 100%|██████████| 70/70 [01:11<00:00,  1.01s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.45it/s]

                   all        278        284      0.802      0.684      0.774      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/300      7.92G       1.21     0.9956      1.282          8       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.14it/s]

                   all        278        284      0.839      0.686      0.785      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/300      7.94G       1.23      1.011      1.299          3       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.33it/s]

                   all        278        284      0.867      0.742      0.809      0.499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/300      7.95G      1.192     0.9687      1.282          8       1024: 100%|██████████| 70/70 [01:08<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.09it/s]

                   all        278        284      0.847      0.767       0.83      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/300      7.96G      1.197     0.9679      1.287          5       1024: 100%|██████████| 70/70 [01:07<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.45it/s]

                   all        278        284       0.86      0.769      0.827      0.488

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/300      7.98G      1.209     0.9929      1.274         10       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.33it/s]

                   all        278        284      0.862      0.716      0.813      0.492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/300      7.99G      1.202     0.9589      1.288          9       1024: 100%|██████████| 70/70 [01:09<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.08it/s]

                   all        278        284      0.828      0.735      0.799      0.515

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/300      8.01G      1.165     0.9193      1.269          8       1024: 100%|██████████| 70/70 [01:08<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.44it/s]

                   all        278        284      0.872      0.763       0.84       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/300      8.03G      1.193     0.9753      1.279          8       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.14it/s]

                   all        278        284      0.832      0.748      0.797      0.488

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/300      8.04G      1.162     0.9412       1.26         12       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.00it/s]

                   all        278        284      0.868      0.711      0.831      0.502

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/300      8.06G      1.171     0.8962      1.262          4       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.13it/s]

                   all        278        284      0.762      0.743      0.826       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/300      8.07G      1.182     0.9435      1.287         10       1024: 100%|██████████| 70/70 [01:08<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.31it/s]

                   all        278        284      0.904      0.717      0.817        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/300      8.08G      1.167      0.894      1.257          9       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.09it/s]

                   all        278        284      0.826      0.737      0.794      0.475

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/300       8.1G      1.147      0.867      1.254          8       1024: 100%|██████████| 70/70 [01:11<00:00,  1.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.25it/s]

                   all        278        284      0.871      0.708      0.823      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/300      8.12G      1.161     0.8776      1.255         15       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.22it/s]

                   all        278        284      0.831      0.711      0.819      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/300      8.13G      1.185       0.88      1.268         10       1024: 100%|██████████| 70/70 [01:06<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.34it/s]

                   all        278        284      0.852      0.764       0.83      0.502

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/300      8.14G      1.143     0.8294      1.246         12       1024: 100%|██████████| 70/70 [01:09<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.03s/it]

                   all        278        284      0.898      0.738      0.823       0.49

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/300      8.16G      1.141     0.9012      1.239          6       1024: 100%|██████████| 70/70 [01:08<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.34it/s]

                   all        278        284      0.862      0.759      0.851      0.513

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/300      8.17G      1.136     0.8269      1.246         12       1024: 100%|██████████| 70/70 [01:07<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.27it/s]

                   all        278        284      0.905       0.79      0.893      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/300      8.19G      1.101     0.8225      1.232         10       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.14it/s]

                   all        278        284      0.876      0.759      0.841      0.519

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/300       8.2G      1.131     0.8355      1.237          7       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.10it/s]

                   all        278        284        0.9      0.802      0.881      0.518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/300      8.22G      1.138     0.8262      1.236          7       1024: 100%|██████████| 70/70 [01:05<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.15it/s]

                   all        278        284       0.89      0.722      0.814      0.501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/300      8.23G      1.112     0.8144      1.213         11       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.30it/s]

                   all        278        284      0.805      0.759      0.839      0.507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/300      8.25G      1.094     0.8035      1.206          7       1024: 100%|██████████| 70/70 [01:08<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.03s/it]

                   all        278        284       0.89      0.752      0.846      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/300      8.26G      1.113     0.8079      1.229          9       1024: 100%|██████████| 70/70 [01:06<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.53it/s]

                   all        278        284      0.914      0.723      0.825      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/300      8.28G      1.127     0.7991      1.245          9       1024: 100%|██████████| 70/70 [01:08<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.16it/s]

                   all        278        284      0.936      0.783      0.862      0.519

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/300      8.29G      1.135     0.8157      1.239         10       1024: 100%|██████████| 70/70 [01:11<00:00,  1.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.49it/s]

                   all        278        284      0.912      0.714      0.839      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/300      8.31G       1.12     0.8096      1.236          9       1024: 100%|██████████| 70/70 [01:07<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.02it/s]

                   all        278        284      0.848      0.791      0.861      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/300      8.32G      1.068     0.7719      1.201         10       1024: 100%|██████████| 70/70 [01:08<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.39it/s]

                   all        278        284      0.862      0.813      0.863      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/300      8.34G      1.076     0.7468      1.195         11       1024: 100%|██████████| 70/70 [01:06<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.24it/s]

                   all        278        284       0.87      0.819      0.857      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/300      8.35G       1.13     0.8144      1.226         10       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.28it/s]

                   all        278        284      0.814       0.76      0.845      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/300      8.37G      1.092     0.7621      1.205          4       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:11<00:00,  1.32s/it]

                   all        278        284      0.875      0.794      0.855      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/300      8.38G      1.081     0.7529       1.19          8       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.41it/s]

                   all        278        284      0.923      0.771       0.85      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/300       8.4G      1.066     0.7612      1.181          6       1024: 100%|██████████| 70/70 [01:07<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.11it/s]

                   all        278        284       0.93      0.735       0.85      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/300      8.41G       1.05     0.7633      1.184         11       1024: 100%|██████████| 70/70 [01:07<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.25it/s]

                   all        278        284      0.923       0.75       0.87      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/300      8.43G      1.058     0.7345      1.191         12       1024: 100%|██████████| 70/70 [01:11<00:00,  1.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.18it/s]

                   all        278        284      0.838      0.844       0.91      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/300      8.44G      1.038     0.7388      1.183         10       1024: 100%|██████████| 70/70 [01:10<00:00,  1.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:09<00:00,  1.02s/it]

                   all        278        284      0.921      0.753      0.856      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/300      8.46G       1.09     0.8032      1.209          8       1024: 100%|██████████| 70/70 [01:12<00:00,  1.04s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.45it/s]

                   all        278        284      0.879      0.835       0.87      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/300      8.47G      1.092     0.7805      1.206         10       1024: 100%|██████████| 70/70 [01:09<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.17it/s]

                   all        278        284      0.906      0.765      0.833      0.507
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 53, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

73 epochs completed in 1.625 hours.
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed/weights/last.pt, 5.6MB
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed/weights/best.pt, 5.6MB

Validating /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed/weights/best.pt...
Ultralytics 8.3.104 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLO11n summary (fused): 100 layers, 2,583,517 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:16<00:00,  1.86s/it]

                   all        278        284      0.905       0.79      0.893      0.553
               Apoidea         10         10      0.774      0.685      0.685      0.432
             Arachnida         15         15          1      0.574      0.923      0.495
            Brachycera         16         16      0.872      0.938      0.929      0.629
            Coleoptera         51         51      0.904      0.961      0.973      0.625
            Formicidae         67         73       0.85      0.822      0.918      0.637
            Formicidae         95         95      0.968      0.926      0.964      0.576
            Syraphidae         24         24       0.97      0.625      0.862      0.479
Speed: 1.7ms preprocess, 7.1ms inference, 0.0ms loss, 7.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/train_yolo11n_reindexed
🔍 Evaluating on validation set...

  0%|          | 0/278 [00:00<?, ?it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1576697.jpg: 1024x1024 1 Formicidae, 9.9ms
Speed: 7.1ms preprocess, 9.9ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

  0%|          | 1/278 [00:00<01:08,  4.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1174454.jpg: 864x1024 1 Brachycera, 47.6ms
Speed: 10.9ms preprocess, 47.6ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1024)

  1%|          | 2/278 [00:00<00:56,  4.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802958.jpg: 1024x1024 1 Coleoptera, 10.4ms
Speed: 6.9ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

  1%|          | 3/278 [00:00<01:37,  2.83it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1892601.jpg: 1024x1024 1 Formicidae, 10.1ms
Speed: 7.5ms preprocess, 10.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1035967.jpg: 1024x1024 1 Apoidea, 9.6ms
Speed: 7.5ms preprocess, 9.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

  2%|▏         | 5/278 [00:01<00:55,  4.96it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869664.jpg: 1024x1024 1 Coleoptera, 9.6ms
Speed: 7.8ms preprocess, 9.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1658656.jpg: 1024x1024 1 Formicidae, 9.4ms
Speed: 6.5ms preprocess, 9.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  3%|▎         | 7/278 [00:01<00:36,  7.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1883122.jpg: 1024x1024 1 Formicidae, 9.7ms
Speed: 6.6ms preprocess, 9.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650228.jpg: 1024x1024 1 Formicidae, 9.6ms
Speed: 6.5ms preprocess, 9.6ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_499672.jpg: 768x1024 1 Brachycera, 47.5ms
Speed: 9.6ms preprocess, 47.5ms inference, 1.5ms postprocess per image at shape (1, 3, 768, 1024)

  4%|▎         | 10/278 [00:01<00:32,  8.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1739113.jpg: 1024x1024 1 Coleoptera, 10.7ms
Speed: 6.7ms preprocess, 10.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626638.jpg: 1024x1024 1 Formicidae, 11.2ms
Speed: 7.0ms preprocess, 11.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1680229.jpg: 1024x1024 1 Formicidae, 11.1ms
Speed: 7.8ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

  5%|▍         | 13/278 [00:01<00:24, 10.88it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542164.jpg: 736x1024 1 Arachnida, 49.7ms
Speed: 7.1ms preprocess, 49.7ms inference, 1.7ms postprocess per image at shape (1, 3, 736, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1705644.jpg: 1024x1024 1 Formicidae, 14.3ms
Speed: 6.9ms preprocess, 14.3ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  5%|▌         | 15/278 [00:01<00:25, 10.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703727.jpg: 768x1024 1 Brachycera, 12.6ms
Speed: 6.8ms preprocess, 12.6ms inference, 1.4ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1679968.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 10.0ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  6%|▌         | 17/278 [00:02<00:55,  4.74it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1199210.jpg: 800x1024 (no detections), 48.3ms
Speed: 7.1ms preprocess, 48.3ms inference, 0.7ms postprocess per image at shape (1, 3, 800, 1024)

  6%|▋         | 18/278 [00:03<00:56,  4.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1880449.jpg: 800x1024 3 Formicidaes, 12.2ms
Speed: 10.6ms preprocess, 12.2ms inference, 1.6ms postprocess per image at shape (1, 3, 800, 1024)

  7%|▋         | 19/278 [00:05<02:52,  1.50it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1720000.jpg: 1024x1024 1 Formicidae, 17.5ms
Speed: 10.3ms preprocess, 17.5ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1889657.jpg: 1024x1024 1 Formicidae, 19.6ms
Speed: 10.1ms preprocess, 19.6ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

  8%|▊         | 21/278 [00:05<01:56,  2.22it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541911.jpg: 1024x1024 (no detections), 16.9ms
Speed: 14.5ms preprocess, 16.9ms inference, 1.0ms postprocess per image at shape (1, 3, 1024, 1024)

  8%|▊         | 22/278 [00:05<01:41,  2.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661407.jpg: 1024x1024 1 Formicidae, 17.6ms
Speed: 10.4ms preprocess, 17.6ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862511.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 10.8ms preprocess, 14.2ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

  9%|▊         | 24/278 [00:06<01:09,  3.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1032411.jpg: 1024x1024 1 Formicidae, 21.8ms
Speed: 17.2ms preprocess, 21.8ms inference, 2.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869258.jpg: 1024x1024 2 Coleopteras, 14.2ms
Speed: 12.8ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

  9%|▉         | 26/278 [00:06<00:52,  4.79it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803945.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 11.3ms preprocess, 14.2ms inference, 2.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214502.jpg: 1024x1024 1 Coleoptera, 22.2ms
Speed: 10.5ms preprocess, 22.2ms inference, 2.3ms postprocess per image at shape (1, 3, 1024, 1024)

 10%|█         | 28/278 [00:06<00:40,  6.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1909134.jpg: 1024x1024 1 Formicidae, 17.6ms
Speed: 10.8ms preprocess, 17.6ms inference, 2.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_931985.jpg: 1024x1024 1 Formicidae, 16.0ms
Speed: 10.2ms preprocess, 16.0ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 11%|█         | 30/278 [00:06<00:32,  7.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886378.jpg: 1024x1024 1 Formicidae, 15.7ms
Speed: 9.9ms preprocess, 15.7ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1719649.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 12%|█▏        | 32/278 [00:06<00:26,  9.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803987.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1760513.jpg: 992x1024 1 Arachnida, 47.8ms
Speed: 7.9ms preprocess, 47.8ms inference, 1.4ms postprocess per image at shape (1, 3, 992, 1024)

 12%|█▏        | 34/278 [00:06<00:26,  9.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1611112.jpg: 1024x1024 2 Formicidaes, 17.2ms
Speed: 6.9ms preprocess, 17.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802908.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 13%|█▎        | 36/278 [00:07<00:22, 10.53it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1540578.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701561.jpg: 1024x1024 1 Syraphidae, 14.1ms
Speed: 7.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 14%|█▎        | 38/278 [00:07<00:19, 12.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1884094.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1831577.jpg: 1024x1024 1 Formicidae, 17.0ms
Speed: 9.5ms preprocess, 17.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 14%|█▍        | 40/278 [00:07<00:17, 13.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1537477.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541858.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 15%|█▌        | 42/278 [00:07<00:17, 13.80it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2001820.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661488.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 16%|█▌        | 44/278 [00:07<00:15, 15.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1693286.jpg: 1024x1024 1 Brachycera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_758932.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.4ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 17%|█▋        | 46/278 [00:07<00:14, 15.80it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893193.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893214.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 17%|█▋        | 48/278 [00:07<00:13, 16.66it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1560917.jpg: 800x1024 1 Apoidea, 1 Brachycera, 12.8ms
Speed: 6.9ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626454.jpg: 1024x1024 2 Formicidaes, 15.1ms
Speed: 7.5ms preprocess, 15.1ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 18%|█▊        | 50/278 [00:07<00:18, 12.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1208580.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869228.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 19%|█▊        | 52/278 [00:08<00:16, 13.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_405031.jpg: 768x1024 1 Syraphidae, 13.5ms
Speed: 11.1ms preprocess, 13.5ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1589547.jpg: 1024x1024 2 Formicidaes, 15.0ms
Speed: 12.1ms preprocess, 15.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 19%|█▉        | 54/278 [00:08<00:18, 12.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1607684.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893434.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 20%|██        | 56/278 [00:08<00:16, 13.33it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626230.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1544074.jpg: 800x1024 1 Syraphidae, 12.8ms
Speed: 7.1ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 21%|██        | 58/278 [00:08<00:17, 12.25it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680031.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 7.6ms preprocess, 14.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_488523.jpg: 1024x1024 1 Arachnida, 1 Coleoptera, 1 Formicidae, 14.1ms
Speed: 9.1ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 22%|██▏       | 60/278 [00:08<00:16, 13.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_931996.jpg: 1024x1024 1 Coleoptera, 1 Formicidae, 14.1ms
Speed: 10.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_14144.jpg: 576x1024 1 Apoidea, 47.7ms
Speed: 5.4ms preprocess, 47.7ms inference, 1.4ms postprocess per image at shape (1, 3, 576, 1024)

 22%|██▏       | 62/278 [00:09<00:21,  9.99it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1558288.jpg: 1024x1024 1 Formicidae, 14.9ms
Speed: 7.6ms preprocess, 14.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/991_1813221.jpg: 800x1024 (no detections), 12.8ms
Speed: 7.0ms preprocess, 12.8ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

 23%|██▎       | 64/278 [00:09<00:22,  9.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1885403.jpg: 768x1024 2 Formicidaes, 12.6ms
Speed: 6.7ms preprocess, 12.6ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2001915.jpg: 1024x1024 2 Formicidaes, 14.8ms
Speed: 7.1ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 24%|██▎       | 66/278 [00:09<00:23,  8.97it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/859_1832273.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943955.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 7.6ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 24%|██▍       | 68/278 [00:09<00:19, 10.66it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705250.jpg: 1024x1024 1 Brachycera, 14.2ms
Speed: 10.2ms preprocess, 14.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1543606.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.5ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 25%|██▌       | 70/278 [00:09<00:19, 10.48it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1583461.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.0ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661404.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.8ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 26%|██▌       | 72/278 [00:09<00:17, 11.92it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1590245.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214640.jpg: 800x1024 (no detections), 12.8ms
Speed: 7.8ms preprocess, 12.8ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

 27%|██▋       | 74/278 [00:11<01:06,  3.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1539172.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 6.8ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1760492.jpg: 1024x1024 1 Arachnida, 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 27%|██▋       | 76/278 [00:11<00:49,  4.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364929.jpg: 1024x1024 1 Arachnida, 14.1ms
Speed: 7.4ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_499671.jpg: 800x1024 (no detections), 12.8ms
Speed: 6.7ms preprocess, 12.8ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

 28%|██▊       | 78/278 [00:12<00:41,  4.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310900.jpg: 800x1024 1 Coleoptera, 1 Syraphidae, 12.2ms
Speed: 7.0ms preprocess, 12.2ms inference, 3.8ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1859767.jpg: 1024x1024 1 Coleoptera, 14.8ms
Speed: 8.2ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 29%|██▉       | 80/278 [00:12<00:36,  5.39it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1263711.jpg: 768x1024 1 Formicidae, 12.5ms
Speed: 6.9ms preprocess, 12.5ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1730099.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 6.6ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 29%|██▉       | 82/278 [00:12<00:29,  6.67it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214505.jpg: 1024x1024 2 Coleopteras, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_983481.jpg: 800x1024 1 Apoidea, 1 Syraphidae, 13.2ms
Speed: 7.5ms preprocess, 13.2ms inference, 1.6ms postprocess per image at shape (1, 3, 800, 1024)

 30%|███       | 84/278 [00:12<00:27,  7.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886365.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 6.7ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1129307.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.4ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 31%|███       | 86/278 [00:12<00:21,  8.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1304800.jpg: 864x1024 (no detections), 13.3ms
Speed: 7.1ms preprocess, 13.3ms inference, 0.6ms postprocess per image at shape (1, 3, 864, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1539168.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 6.8ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 32%|███▏      | 88/278 [00:13<00:21,  8.73it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1892602.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943961.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 7.3ms preprocess, 14.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 32%|███▏      | 90/278 [00:13<00:18, 10.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541881.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1793456.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 33%|███▎      | 92/278 [00:13<00:15, 11.69it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869227.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862547.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680046.jpg: 800x1024 1 Formicidae, 12.8ms
Speed: 6.8ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 34%|███▍      | 95/278 [00:13<00:15, 12.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1756184.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 6.6ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_376520.jpg: 576x1024 1 Syraphidae, 55.2ms
Speed: 23.9ms preprocess, 55.2ms inference, 1.6ms postprocess per image at shape (1, 3, 576, 1024)

 35%|███▍      | 97/278 [00:18<02:13,  1.36it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1558357.jpg: 1024x1024 1 Formicidae, 83.9ms
Speed: 57.9ms preprocess, 83.9ms inference, 3.2ms postprocess per image at shape (1, 3, 1024, 1024)

 35%|███▌      | 98/278 [00:18<01:57,  1.53it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1596975.jpg: 1024x1024 1 Formicidae, 63.4ms
Speed: 30.5ms preprocess, 63.4ms inference, 2.6ms postprocess per image at shape (1, 3, 1024, 1024)

 36%|███▌      | 99/278 [00:18<01:41,  1.77it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1296685.jpg: 1024x1024 1 Formicidae, 71.5ms
Speed: 37.5ms preprocess, 71.5ms inference, 4.7ms postprocess per image at shape (1, 3, 1024, 1024)

 36%|███▌      | 100/278 [00:19<01:27,  2.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542166.jpg: 1024x1024 1 Formicidae, 1 Formicidae, 33.9ms
Speed: 25.2ms preprocess, 33.9ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 36%|███▋      | 101/278 [00:19<01:15,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_503051.jpg: 576x1024 1 Formicidae, 1 Syraphidae, 55.7ms
Speed: 20.2ms preprocess, 55.7ms inference, 12.2ms postprocess per image at shape (1, 3, 576, 1024)

 37%|███▋      | 102/278 [00:20<01:35,  1.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869236.jpg: 1024x1024 1 Coleoptera, 24.0ms
Speed: 25.0ms preprocess, 24.0ms inference, 13.0ms postprocess per image at shape (1, 3, 1024, 1024)

 37%|███▋      | 103/278 [00:20<01:17,  2.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935393.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.8ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1739198.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 10.9ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 38%|███▊      | 105/278 [00:20<00:49,  3.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/34_977656.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.1ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661365.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.6ms preprocess, 14.2ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 38%|███▊      | 107/278 [00:20<00:35,  4.75it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_710011.jpg: 576x1024 1 Syraphidae, 53.3ms
Speed: 24.9ms preprocess, 53.3ms inference, 1.6ms postprocess per image at shape (1, 3, 576, 1024)

 39%|███▉      | 108/278 [00:21<00:43,  3.94it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578215.jpg: 1024x1024 (no detections), 27.9ms
Speed: 25.8ms preprocess, 27.9ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

 39%|███▉      | 109/278 [00:21<00:39,  4.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1202777.jpg: 1024x1024 1 Formicidae, 18.1ms
Speed: 25.5ms preprocess, 18.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 40%|███▉      | 110/278 [00:21<00:36,  4.60it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680041.jpg: 800x1024 1 Formicidae, 67.1ms
Speed: 29.2ms preprocess, 67.1ms inference, 8.5ms postprocess per image at shape (1, 3, 800, 1024)

 40%|███▉      | 111/278 [00:21<00:44,  3.73it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870243.jpg: 1024x1024 1 Coleoptera, 71.8ms
Speed: 46.4ms preprocess, 71.8ms inference, 11.4ms postprocess per image at shape (1, 3, 1024, 1024)

 40%|████      | 112/278 [00:22<00:42,  3.87it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1909301.jpg: 768x1024 1 Apoidea, 83.2ms
Speed: 34.0ms preprocess, 83.2ms inference, 1.6ms postprocess per image at shape (1, 3, 768, 1024)

 41%|████      | 113/278 [00:22<00:51,  3.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1726947.jpg: 1024x1024 1 Brachycera, 1 Formicidae, 66.7ms
Speed: 21.7ms preprocess, 66.7ms inference, 5.3ms postprocess per image at shape (1, 3, 1024, 1024)

 41%|████      | 114/278 [00:22<00:45,  3.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_495546.jpg: 1024x1024 1 Arachnida, 1 Formicidae, 62.0ms
Speed: 33.1ms preprocess, 62.0ms inference, 8.4ms postprocess per image at shape (1, 3, 1024, 1024)

 41%|████▏     | 115/278 [00:22<00:44,  3.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650235.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1719192.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 42%|████▏     | 117/278 [00:23<00:28,  5.68it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1582009.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870212.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 43%|████▎     | 119/278 [00:23<00:20,  7.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680043.jpg: 800x1024 1 Formicidae, 12.8ms
Speed: 6.7ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1887570.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 6.9ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 44%|████▎     | 121/278 [00:23<00:17,  8.78it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1847163.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1650775.jpg: 832x1024 1 Apoidea, 51.0ms
Speed: 7.1ms preprocess, 51.0ms inference, 1.5ms postprocess per image at shape (1, 3, 832, 1024)

 44%|████▍     | 123/278 [00:23<00:17,  8.62it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1565506.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 6.7ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661377.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 45%|████▍     | 125/278 [00:23<00:14, 10.46it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214590.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1225144.jpg: 864x1024 1 Brachycera, 13.3ms
Speed: 7.5ms preprocess, 13.3ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1024)

 46%|████▌     | 127/278 [00:23<00:14, 10.68it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_1570493.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 6.6ms preprocess, 14.7ms inference, 1.2ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1742462.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 46%|████▋     | 129/278 [00:24<00:12, 12.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869201.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.4ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1804174.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 47%|████▋     | 131/278 [00:24<00:10, 13.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1947655.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214629.jpg: 1024x1024 2 Coleopteras, 14.1ms
Speed: 7.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 48%|████▊     | 133/278 [00:24<00:10, 14.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1883119.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1550514.jpg: 1024x1024 (no detections), 14.1ms
Speed: 8.4ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 49%|████▊     | 135/278 [00:24<00:10, 13.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541854.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802914.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 49%|████▉     | 137/278 [00:24<00:10, 13.34it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1690164.jpg: 768x1024 1 Formicidae, 12.7ms
Speed: 6.5ms preprocess, 12.7ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_934398.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.4ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 50%|█████     | 139/278 [00:24<00:11, 12.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1263867.jpg: 768x1024 1 Formicidae, 12.6ms
Speed: 6.8ms preprocess, 12.6ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707531.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 6.6ms preprocess, 14.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 51%|█████     | 141/278 [00:24<00:11, 11.50it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703711.jpg: 768x1024 1 Brachycera, 12.6ms
Speed: 10.0ms preprocess, 12.6ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1035966.jpg: 1024x1024 1 Syraphidae, 14.8ms
Speed: 6.9ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 51%|█████▏    | 143/278 [00:26<00:40,  3.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1585491.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707001.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 52%|█████▏    | 145/278 [00:26<00:30,  4.40it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_70781.jpg: 576x1024 1 Syraphidae, 12.0ms
Speed: 5.5ms preprocess, 12.0ms inference, 1.4ms postprocess per image at shape (1, 3, 576, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_15077.jpg: 576x1024 1 Syraphidae, 9.7ms
Speed: 5.4ms preprocess, 9.7ms inference, 1.3ms postprocess per image at shape (1, 3, 576, 1024)

 53%|█████▎    | 147/278 [00:29<01:16,  1.71it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802938.jpg: 1024x1024 1 Coleoptera, 14.7ms
Speed: 6.7ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1660000.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 54%|█████▎    | 149/278 [00:29<00:54,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1563515.jpg: 960x1024 2 Formicidaes, 49.5ms
Speed: 7.8ms preprocess, 49.5ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1788482.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 8.4ms preprocess, 14.8ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 54%|█████▍    | 151/278 [00:29<00:42,  2.98it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1660109.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214573.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 55%|█████▌    | 153/278 [00:29<00:31,  4.00it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1544081.jpg: 800x1024 1 Syraphidae, 12.9ms
Speed: 6.8ms preprocess, 12.9ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578478.jpg: 1024x1024 1 Formicidae, 15.0ms
Speed: 6.9ms preprocess, 15.0ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 56%|█████▌    | 155/278 [00:30<00:24,  4.98it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364920.jpg: 1024x1024 1 Arachnida, 14.2ms
Speed: 8.2ms preprocess, 14.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/34_998277.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 8.5ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 56%|█████▋    | 157/278 [00:30<00:19,  6.24it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1551894.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_15503.jpg: 576x1024 1 Apoidea, 10.2ms
Speed: 5.4ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 576, 1024)

 57%|█████▋    | 159/278 [00:31<00:32,  3.67it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1788275.jpg: 736x1024 1 Arachnida, 12.4ms
Speed: 6.5ms preprocess, 12.4ms inference, 1.3ms postprocess per image at shape (1, 3, 736, 1024)

 58%|█████▊    | 160/278 [00:31<00:29,  4.02it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1708731.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 8.7ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541890.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 58%|█████▊    | 162/278 [00:31<00:21,  5.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886833.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1564042.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 59%|█████▉    | 164/278 [00:31<00:16,  6.74it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709230.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803311.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 60%|█████▉    | 166/278 [00:31<00:13,  8.47it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1833731.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650212.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.2ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 60%|██████    | 168/278 [00:31<00:10, 10.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1540596.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310895.jpg: 864x1024 1 Syraphidae, 13.4ms
Speed: 8.5ms preprocess, 13.4ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1024)

 61%|██████    | 170/278 [00:32<00:10, 10.69it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1708646.jpg: 768x1024 1 Brachycera, 1 Formicidae, 16.9ms
Speed: 9.5ms preprocess, 16.9ms inference, 1.9ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1577457.jpg: 1024x1024 2 Formicidaes, 15.0ms
Speed: 12.9ms preprocess, 15.0ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 62%|██████▏   | 172/278 [00:33<00:23,  4.51it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1872752.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 11.2ms preprocess, 14.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1576661.jpg: 800x1024 1 Formicidae, 13.0ms
Speed: 10.6ms preprocess, 13.0ms inference, 1.6ms postprocess per image at shape (1, 3, 800, 1024)

 63%|██████▎   | 174/278 [00:33<00:20,  5.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1706996.jpg: 1024x1024 1 Formicidae, 15.1ms
Speed: 11.1ms preprocess, 15.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1421739.jpg: 1024x1024 1 Arachnida, 14.2ms
Speed: 11.0ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 63%|██████▎   | 176/278 [00:33<00:15,  6.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626259.jpg: 1024x1024 2 Formicidaes, 14.2ms
Speed: 11.4ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709242.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.2ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 64%|██████▍   | 178/278 [00:33<00:13,  7.68it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1628691.jpg: 800x1024 1 Brachycera, 1 Formicidae, 14.7ms
Speed: 10.4ms preprocess, 14.7ms inference, 1.5ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802936.jpg: 1024x1024 1 Coleoptera, 15.0ms
Speed: 10.5ms preprocess, 15.0ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 65%|██████▍   | 180/278 [00:34<00:13,  7.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1602609.jpg: 1024x1024 1 Apoidea, 1 Formicidae, 17.2ms
Speed: 10.1ms preprocess, 17.2ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650233.jpg: 1024x1024 1 Formicidae, 18.5ms
Speed: 11.8ms preprocess, 18.5ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 65%|██████▌   | 182/278 [00:34<00:11,  8.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_1999521.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.1ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1722814.jpg: 1024x1024 1 Formicidae, 17.4ms
Speed: 10.9ms preprocess, 17.4ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 66%|██████▌   | 184/278 [00:34<00:09,  9.41it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541874.jpg: 1024x1024 1 Formicidae, 18.4ms
Speed: 15.7ms preprocess, 18.4ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701558.jpg: 800x1024 (no detections), 13.0ms
Speed: 10.8ms preprocess, 13.0ms inference, 0.7ms postprocess per image at shape (1, 3, 800, 1024)

 67%|██████▋   | 186/278 [00:34<00:11,  8.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1621246.jpg: 1024x1024 1 Formicidae, 15.1ms
Speed: 10.5ms preprocess, 15.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_766602.jpg: 1024x1024 1 Formicidae, 1 Syraphidae, 14.2ms
Speed: 10.2ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 68%|██████▊   | 188/278 [00:34<00:09,  9.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2008658.jpg: 1024x1024 1 Brachycera, 14.2ms
Speed: 13.1ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1297358.jpg: 1024x1024 1 Brachycera, 14.2ms
Speed: 10.5ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 68%|██████▊   | 190/278 [00:35<00:09,  9.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1590559.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.4ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1796311.jpg: 1024x1024 1 Brachycera, 1 Formicidae, 1 Formicidae, 18.4ms
Speed: 10.5ms preprocess, 18.4ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 69%|██████▉   | 192/278 [00:35<00:08, 10.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1559305.jpg: 1024x1024 2 Formicidaes, 14.2ms
Speed: 10.9ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1701608.jpg: 1024x1024 (no detections), 14.2ms
Speed: 10.6ms preprocess, 14.2ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)

 70%|██████▉   | 194/278 [00:35<00:07, 11.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709231.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.8ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650227.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.9ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 71%|███████   | 196/278 [00:35<00:06, 12.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1692863.jpg: 1024x1024 1 Formicidae, 17.2ms
Speed: 13.7ms preprocess, 17.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541905.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.0ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 71%|███████   | 198/278 [00:35<00:06, 12.58it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701569.jpg: 1024x1024 1 Syraphidae, 14.2ms
Speed: 11.4ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1265110.jpg: 768x1024 1 Formicidae, 20.1ms
Speed: 10.5ms preprocess, 20.1ms inference, 2.9ms postprocess per image at shape (1, 3, 768, 1024)

 72%|███████▏  | 200/278 [00:35<00:07, 10.39it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661427.jpg: 1024x1024 1 Formicidae, 16.2ms
Speed: 13.0ms preprocess, 16.2ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870096.jpg: 1024x1024 1 Coleoptera, 20.5ms
Speed: 10.8ms preprocess, 20.5ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 73%|███████▎  | 202/278 [00:36<00:06, 10.99it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803962.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 13.2ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870125.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 10.6ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 73%|███████▎  | 204/278 [00:36<00:06, 11.81it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803326.jpg: 1024x1024 1 Coleoptera, 18.7ms
Speed: 13.0ms preprocess, 18.7ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214632.jpg: 1024x1024 2 Coleopteras, 20.1ms
Speed: 10.6ms preprocess, 20.1ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 74%|███████▍  | 206/278 [00:36<00:06, 11.25it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802976.jpg: 1024x1024 1 Coleoptera, 17.4ms
Speed: 11.1ms preprocess, 17.4ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1630250.jpg: 1024x1024 1 Formicidae, 17.6ms
Speed: 10.4ms preprocess, 17.6ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 75%|███████▍  | 208/278 [00:36<00:05, 12.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1610847.jpg: 800x1024 (no detections), 18.3ms
Speed: 11.7ms preprocess, 18.3ms inference, 1.1ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1658717.jpg: 1024x1024 1 Formicidae, 15.0ms
Speed: 6.6ms preprocess, 15.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 76%|███████▌  | 210/278 [00:36<00:07,  9.39it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870208.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542159.jpg: 928x1024 1 Arachnida, 49.5ms
Speed: 7.3ms preprocess, 49.5ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1024)

 76%|███████▋  | 212/278 [00:37<00:06,  9.69it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893238.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 6.6ms preprocess, 14.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870113.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 77%|███████▋  | 214/278 [00:37<00:05, 11.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1722852.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_368619.jpg: 800x1024 1 Brachycera, 1 Syraphidae, 12.9ms
Speed: 6.9ms preprocess, 12.9ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 78%|███████▊  | 216/278 [00:37<00:06,  9.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/859_1834070.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.1ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1884047.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 78%|███████▊  | 218/278 [00:37<00:05, 10.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709220.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.2ms preprocess, 14.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364909.jpg: 1024x1024 1 Arachnida, 14.2ms
Speed: 6.5ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 79%|███████▉  | 220/278 [00:37<00:04, 12.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703719.jpg: 768x1024 1 Brachycera, 12.6ms
Speed: 6.8ms preprocess, 12.6ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_939952.jpg: 1024x1024 1 Syraphidae, 14.8ms
Speed: 6.8ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 80%|███████▉  | 222/278 [00:37<00:04, 11.98it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870099.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1730092.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 6.5ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_13827.jpg: 576x1024 2 Syraphidaes, 10.0ms
Speed: 5.2ms preprocess, 10.0ms inference, 1.3ms postprocess per image at shape (1, 3, 576, 1024)

 81%|████████  | 225/278 [00:38<00:04, 12.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578214.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.2ms preprocess, 14.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541869.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 82%|████████▏ | 227/278 [00:38<00:03, 13.25it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_311300.jpg: 1024x1024 1 Apoidea, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_930779.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 82%|████████▏ | 229/278 [00:38<00:03, 12.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707082.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 7.1ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661381.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 83%|████████▎ | 231/278 [00:38<00:03, 14.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1682266.jpg: 800x1024 2 Formicidaes, 13.2ms
Speed: 7.1ms preprocess, 13.2ms inference, 1.8ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705255.jpg: 768x1024 1 Brachycera, 13.1ms
Speed: 6.6ms preprocess, 13.1ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

 84%|████████▍ | 233/278 [00:39<00:10,  4.34it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802998.jpg: 1024x1024 1 Coleoptera, 15.1ms
Speed: 6.7ms preprocess, 15.1ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870207.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 85%|████████▍ | 235/278 [00:39<00:07,  5.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1889633.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1891801.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 85%|████████▌ | 237/278 [00:39<00:06,  6.73it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1545097.jpg: 1024x1024 1 Brachycera, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1690283.jpg: 1024x1024 1 Coleoptera, 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 86%|████████▌ | 239/278 [00:40<00:04,  8.00it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886831.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1572039.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 87%|████████▋ | 241/278 [00:40<00:03,  9.32it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935478.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1689926.jpg: 800x1024 (no detections), 13.0ms
Speed: 6.8ms preprocess, 13.0ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

 87%|████████▋ | 243/278 [00:40<00:04,  8.64it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705267.jpg: 768x1024 1 Brachycera, 12.6ms
Speed: 6.8ms preprocess, 12.6ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680040.jpg: 800x1024 1 Brachycera, 12.8ms
Speed: 6.9ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 88%|████████▊ | 245/278 [00:40<00:04,  7.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862525.jpg: 1024x1024 1 Coleoptera, 14.8ms
Speed: 6.7ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541903.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 89%|████████▉ | 247/278 [00:40<00:03,  9.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541909.jpg: 928x1024 1 Formicidae, 13.7ms
Speed: 7.6ms preprocess, 13.7ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541855.jpg: 1024x1024 1 Formicidae, 14.9ms
Speed: 8.2ms preprocess, 14.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 90%|████████▉ | 249/278 [00:41<00:03,  9.38it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680044.jpg: 800x1024 (no detections), 12.8ms
Speed: 6.8ms preprocess, 12.8ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_939772.jpg: 1024x1024 1 Apoidea, 1 Syraphidae, 14.7ms
Speed: 6.8ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 90%|█████████ | 251/278 [00:41<00:03,  8.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_938706.jpg: 800x1024 1 Apoidea, 13.0ms
Speed: 7.0ms preprocess, 13.0ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1700897.jpg: 768x1024 1 Brachycera, 12.5ms
Speed: 6.7ms preprocess, 12.5ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

 91%|█████████ | 253/278 [00:43<00:08,  3.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943984.jpg: 1024x1024 1 Coleoptera, 15.8ms
Speed: 6.8ms preprocess, 15.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578240.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 92%|█████████▏| 255/278 [00:43<00:05,  4.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870089.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1604091.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 92%|█████████▏| 257/278 [00:43<00:03,  5.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1446473.jpg: 1024x1024 (no detections), 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1700912.jpg: 800x1024 1 Brachycera, 13.1ms
Speed: 7.0ms preprocess, 13.1ms inference, 1.4ms postprocess per image at shape (1, 3, 800, 1024)

 93%|█████████▎| 259/278 [00:43<00:03,  6.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1746506.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 10.3ms preprocess, 14.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214613.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 94%|█████████▍| 261/278 [00:43<00:02,  7.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_934128.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1563281.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.4ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 95%|█████████▍| 263/278 [00:43<00:01,  9.24it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802956.jpg: 1024x1024 1 Coleoptera, 16.9ms
Speed: 10.9ms preprocess, 16.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1721874.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 95%|█████████▌| 265/278 [00:43<00:01, 10.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1564396.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 7.0ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1577222.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 96%|█████████▌| 267/278 [00:43<00:00, 12.25it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1551883.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943945.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 97%|█████████▋| 269/278 [00:44<00:00, 13.70it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1708728.jpg: 992x1024 1 Formicidae, 14.7ms
Speed: 7.3ms preprocess, 14.7ms inference, 1.4ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/991_1813226.jpg: 896x1024 (no detections), 49.0ms
Speed: 7.4ms preprocess, 49.0ms inference, 0.6ms postprocess per image at shape (1, 3, 896, 1024)

 97%|█████████▋| 271/278 [00:44<00:00, 10.78it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1143735.jpg: 1024x1024 1 Brachycera, 14.7ms
Speed: 7.1ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803155.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 98%|█████████▊| 273/278 [00:44<00:00, 12.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1551881.jpg: 992x1024 1 Formicidae, 14.6ms
Speed: 8.0ms preprocess, 14.6ms inference, 1.3ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869001.jpg: 1024x1024 1 Coleoptera, 14.8ms
Speed: 6.9ms preprocess, 14.8ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 99%|█████████▉| 275/278 [00:44<00:00, 12.92it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310899.jpg: 800x1024 1 Coleoptera, 1 Syraphidae, 12.8ms
Speed: 6.4ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935599.jpg: 1024x1024 1 Apoidea, 1 Syraphidae, 15.1ms
Speed: 7.2ms preprocess, 15.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

100%|█████████▉| 277/278 [00:44<00:00, 11.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870086.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

100%|██████████| 278/278 [00:44<00:00,  6.20it/s]

✅ Evaluation Summary:
Precision: 0.00%
Recall:    0.00%
F1 Score:  0.00%
→ FP saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/false_positives
→ FN saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/false_negatives
→ MC saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run/misclassified

In [ ]:
!pip install ultralytics
import os
import cv2
import numpy as np
from tqdm import tqdm
from ultralytics import YOLO
from sklearn.metrics import precision_score, recall_score, f1_score

# ✅ Paths
yaml_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/config.yaml"
model_path = "models/yolo11n.pt"
output_dir = "/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200"

# ✅ Train YOLOv11n model (no resume)
model = YOLO(model_path)
model.train(
    data=yaml_path,
    epochs=300,
    imgsz=1200,
    patience=20,
    save=True,
    project=output_dir,
    name="train_yolo11n_reindexed_1200"
)

# ✅ Validation and Evaluation
val_images_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images"
val_labels_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels"

fp_dir = os.path.join(output_dir, "false_positives")
fn_dir = os.path.join(output_dir, "false_negatives")
mc_dir = os.path.join(output_dir, "misclassified")
os.makedirs(fp_dir, exist_ok=True)
os.makedirs(fn_dir, exist_ok=True)
os.makedirs(mc_dir, exist_ok=True)

class_names = {
    0: "Apoidea", 1: "Arachnida", 2: "Brachycera", 3: "Coleoptera",
    4: "Formicidae", 5: "Nematocera", 6: "Syraphidae"
}

def compute_iou(box1, box2):
    xA, yA = max(box1[0], box2[0]), max(box1[1], box2[1])
    xB, yB = min(box1[2], box2[2]), min(box1[3], box2[3])
    inter = max(0, xB - xA) * max(0, yB - yA)
    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])
    return inter / (area1 + area2 - inter + 1e-6)

print("🔍 Evaluating on validation set...")
y_true, y_pred = [], []

for img_name in tqdm(os.listdir(val_images_path)):
    if not img_name.endswith(".jpg"):
        continue

    img_path = os.path.join(val_images_path, img_name)
    label_path = os.path.join(val_labels_path, img_name.replace(".jpg", ".txt"))
    image = cv2.imread(img_path)
    height, width = image.shape[:2]

    results = model(img_path, conf=0.25, iou=0.7)[0]
    pred_boxes = results.boxes.xyxy.cpu().numpy()
    pred_classes = results.boxes.cls.cpu().numpy()

    gt_boxes, gt_classes = [], []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                x1 = int((x - w/2) * width)
                y1 = int((y - h/2) * height)
                x2 = int((x + w/2) * width)
                y2 = int((y + h/2) * height)
                gt_boxes.append([x1, y1, x2, y2])
                gt_classes.append(int(cls))

    matched_pred = set()
    matched_gt = set()

    for i, pbox in enumerate(pred_boxes):
        px1, py1, px2, py2 = map(int, pbox[:4])
        pred_cls = int(pred_classes[i])
        for j, gtbox in enumerate(gt_boxes):
            iou = compute_iou(pbox[:4], gtbox)
            if iou > 0.3:
                matched_pred.add(i)
                matched_gt.add(j)
                if pred_cls != gt_classes[j]:
                    img_copy = image.copy()
                    gx1, gy1, gx2, gy2 = gtbox
                    cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (0, 255, 0), 2)
                    cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
                    cv2.putText(img_copy, f"Pred: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
                    cv2.putText(img_copy, f"GT: {class_names.get(gt_classes[j])}", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)
                    cv2.imwrite(os.path.join(mc_dir, f"mc_{img_name}"), img_copy)
                break

    for i, pbox in enumerate(pred_boxes):
        if i not in matched_pred:
            y_true.append(0)
            y_pred.append(1)
            px1, py1, px2, py2 = map(int, pbox[:4])
            pred_cls = int(pred_classes[i])
            img_copy = image.copy()
            cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
            cv2.putText(img_copy, f"FP: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
            cv2.imwrite(os.path.join(fp_dir, f"fp_{img_name}"), img_copy)

    for j, gtbox in enumerate(gt_boxes):
        if j not in matched_gt:
            y_true.append(1)
            y_pred.append(0)
            gx1, gy1, gx2, gy2 = gtbox
            img_copy = image.copy()
            cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (255, 0, 0), 2)
            cv2.putText(img_copy, "FN", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            cv2.imwrite(os.path.join(fn_dir, f"fn_{img_name}"), img_copy)

# ✅ Summary metrics
precision = precision_score(y_true, y_pred) * 100
recall = recall_score(y_true, y_pred) * 100
f1 = f1_score(y_true, y_pred) * 100

print("\n✅ Evaluation Summary:")
print(f"Precision: {precision:.2f}%")
print(f"Recall:    {recall:.2f}%")
print(f"F1 Score:  {f1:.2f}%")
print(f"→ FP saved to: {fp_dir}")
print(f"→ FN saved to: {fn_dir}")
print(f"→ MC saved to: {mc_dir}")

Collecting ultralytics
  Downloading ultralytics-8.3.104-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy<=2.1.1,>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.14.1)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.2.2)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.13.2)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.14-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.1.31)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Downloading ultralytics-8.3.104-py3-none-any.whl (994 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 994.1/994.1 kB 56.7 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 116.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 90.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 55.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 35.6 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 15.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 91.3 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.14-py3-none-any.whl (26 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.104 ultralytics-thop-2.0.14
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'models/yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 261MB/s]

Ultralytics 8.3.104 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (NVIDIA L4, 22693MiB)
engine/trainer: task=detect, mode=train, model=models/yolo11n.pt, data=/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/config.yaml, epochs=300, time=None, patience=20, batch=16, imgsz=1200, save=True, save_period=-1, cache=False, device=None, workers=8, project=/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200, name=train_yolo11n_reindexed_1200, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...

100%|██████████| 755k/755k [00:00<00:00, 126MB/s]

Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    432037  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]
YOLO11n summary: 181 layers, 2,591,205 parameters, 2,591,189 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 402MB/s]

AMP: checks passed ✅
WARNING ⚠️ imgsz=[1200] must be multiple of max stride 32, updating to [1216]

train: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/train/labels.cache... 1110 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1110/1110 [00:00<?, ?it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels.cache... 278 images, 0 backgrounds, 0 corrupt: 100%|██████████| 278/278 [00:00<?, ?it/s]

Plotting labels to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 1216 train, 1216 val
Using 8 dataloader workers
Logging results to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/300      8.33G      2.178      9.235      1.862          9       1216: 100%|██████████| 70/70 [01:02<00:00,  1.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:08<00:00,  1.01it/s]

                   all        278        284    0.00625      0.791       0.11     0.0499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/300      9.82G      1.589      6.364      1.469          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.24it/s]

                   all        278        284      0.238      0.394      0.229      0.119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/300      9.82G      1.569      5.197      1.472          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.06it/s]

                   all        278        284       0.36      0.362      0.321      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/300      9.82G      1.563      4.455       1.52         10       1216: 100%|██████████| 70/70 [00:25<00:00,  2.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.08it/s]

                   all        278        284      0.708      0.293      0.391      0.213

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/300      9.82G      1.515      3.456      1.454          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.30it/s]

                   all        278        284      0.323      0.464      0.408      0.215

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/300      9.82G      1.555      3.005      1.518          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.535      0.577      0.532      0.301

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/300      9.82G       1.49      2.645      1.465          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.34it/s]

                   all        278        284      0.549      0.498       0.51      0.288

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/300      9.82G      1.482      2.341      1.469          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.667       0.59      0.607      0.364

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/300      9.82G      1.478      2.207       1.47         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.25it/s]

                   all        278        284       0.69      0.477      0.558      0.326

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/300      9.82G      1.411       1.96      1.427         13       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.26it/s]

                   all        278        284       0.69      0.523      0.607      0.355

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/300      9.82G      1.421      1.846      1.424          5       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.707      0.535       0.62      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/300      9.84G      1.419      1.748      1.424         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.32it/s]

                   all        278        284      0.717      0.555      0.616      0.342

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/300      9.85G      1.374      1.613      1.408         13       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.654      0.696      0.646      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/300      9.85G      1.377       1.56      1.413         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.26it/s]

                   all        278        284      0.849      0.598      0.686      0.415

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/300      9.85G      1.376       1.51      1.397          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.29it/s]

                   all        278        284      0.699       0.61      0.663      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/300      9.86G      1.344      1.513      1.393          3       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.39it/s]

                   all        278        284      0.786      0.634      0.739      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/300      9.87G      1.329      1.394      1.376         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.32it/s]

                   all        278        284      0.824      0.634      0.748      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/300      9.87G       1.34      1.392       1.41         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.849       0.65      0.752      0.442

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/300      9.87G      1.327      1.359      1.384         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.27it/s]

                   all        278        284      0.862      0.648      0.768      0.452

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/300      9.87G      1.315      1.301      1.378         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.30it/s]

                   all        278        284      0.865      0.656      0.736      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/300      9.87G      1.323        1.3      1.382         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.37it/s]

                   all        278        284      0.738      0.684      0.726      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/300      9.87G      1.309       1.25      1.363         14       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.31it/s]

                   all        278        284      0.818      0.657      0.736      0.441

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/300      9.87G      1.304      1.234      1.361         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.32it/s]

                   all        278        284      0.851      0.638      0.725      0.432

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/300      9.87G      1.274      1.197      1.348         13       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.29it/s]

                   all        278        284      0.846      0.603      0.735      0.444

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/300      9.88G      1.283      1.175       1.35         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.25it/s]

                   all        278        284      0.802      0.643      0.745      0.451

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/300       9.9G      1.275      1.136      1.351         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.821      0.694      0.767      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/300      9.91G      1.267      1.145      1.337         14       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.35it/s]

                   all        278        284      0.884      0.646      0.737      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/300      9.91G      1.268      1.125      1.358          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.753      0.733      0.785      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/300      9.91G      1.263      1.139      1.343          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.32it/s]

                   all        278        284      0.825      0.692      0.785      0.473

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/300      9.91G      1.256      1.119      1.335          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.23it/s]

                   all        278        284      0.882      0.699      0.787      0.443

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/300      9.91G      1.256      1.086      1.353          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.886      0.697      0.795      0.469

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/300      9.91G       1.22      1.054      1.331         16       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.34it/s]

                   all        278        284      0.796      0.695      0.768      0.462

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/300      9.91G      1.234      1.043      1.328          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.31it/s]

                   all        278        284      0.862      0.666      0.782      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/300      9.91G      1.224      1.019      1.336         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.29it/s]

                   all        278        284      0.832      0.748      0.818      0.493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/300      9.91G      1.194      0.996      1.324          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.33it/s]

                   all        278        284      0.832      0.768      0.834      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/300      9.91G      1.197     0.9617      1.319          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.838       0.75      0.827      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/300      9.91G      1.204     0.9587      1.312          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.35it/s]

                   all        278        284      0.828      0.694      0.751      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/300      9.91G      1.183      0.947      1.298          6       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.28it/s]

                   all        278        284      0.858      0.737      0.828      0.464

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/300      9.91G       1.19     0.9862        1.3         15       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.33it/s]

                   all        278        284      0.762      0.737      0.771      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/300      9.91G      1.209     0.9707      1.301         15       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.35it/s]

                   all        278        284       0.79      0.786      0.805      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/300      9.91G      1.206     0.9191      1.314          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.913       0.68      0.782      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/300      9.91G      1.158     0.9337      1.285          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.30it/s]

                   all        278        284      0.738      0.688      0.759      0.456

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/300      9.91G      1.172     0.9335      1.301         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.31it/s]

                   all        278        284      0.876      0.743      0.831        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/300      9.91G      1.138      0.878      1.265          6       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.30it/s]

                   all        278        284      0.844      0.725      0.807      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/300      9.91G      1.153      0.911      1.278         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.41it/s]

                   all        278        284      0.879      0.737      0.823      0.481

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/300      9.91G      1.141     0.8847      1.274          5       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.39it/s]

                   all        278        284      0.767      0.768      0.807        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/300      9.91G      1.154     0.9085      1.273          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.33it/s]

                   all        278        284      0.842      0.704      0.775      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/300      9.91G      1.139     0.8788      1.275         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.843      0.736       0.79      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/300      9.91G      1.183     0.9171      1.303          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.35it/s]

                   all        278        284      0.858      0.755      0.818      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/300      9.91G      1.138     0.8691      1.284          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.43it/s]

                   all        278        284      0.863      0.744       0.82      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/300      9.91G      1.132     0.8723      1.268          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.27it/s]

                   all        278        284      0.794      0.787      0.842       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/300      9.91G      1.121     0.8631       1.26          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.836      0.778      0.838      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/300      9.91G      1.113     0.8732      1.276          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.37it/s]

                   all        278        284      0.928      0.743      0.854      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/300      9.91G      1.076     0.7955      1.233          6       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284       0.91      0.725      0.818      0.501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/300      9.91G      1.131     0.8585      1.261         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.31it/s]

                   all        278        284      0.848      0.748      0.836      0.507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/300      9.91G       1.12      0.807      1.244         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.33it/s]

                   all        278        284      0.887      0.789      0.851      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/300      9.91G      1.074     0.7719      1.222          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.849      0.804      0.874      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/300      9.91G      1.108     0.8198      1.259         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.35it/s]

                   all        278        284      0.878      0.779      0.844      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/300      9.91G      1.083     0.8023      1.243         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.33it/s]

                   all        278        284      0.874       0.78      0.846      0.518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/300      9.91G      1.069      0.758      1.225         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.25it/s]

                   all        278        284      0.929      0.749      0.857      0.536

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/300      9.91G      1.061     0.7662       1.23         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.33it/s]

                   all        278        284      0.925      0.751      0.848      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/300      9.91G      1.052     0.7592       1.21          9       1216: 100%|██████████| 70/70 [00:25<00:00,  2.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.41it/s]

                   all        278        284      0.893      0.767      0.855       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/300      9.91G       1.06     0.7812      1.209          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.873      0.774      0.856      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/300      9.91G      1.071     0.7677      1.217          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.28it/s]

                   all        278        284      0.903      0.756       0.85      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/300      9.91G      1.064     0.7434      1.216         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.37it/s]

                   all        278        284      0.918       0.72      0.816      0.509

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/300      9.91G      1.042     0.7382      1.191         14       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.838      0.815      0.857      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/300      9.91G      1.082     0.7657       1.22         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.37it/s]

                   all        278        284      0.898      0.709      0.827      0.515

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/300      9.91G      1.081     0.7724      1.225          3       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.29it/s]

                   all        278        284      0.894      0.783      0.854      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/300      9.91G      1.052     0.7404      1.208         14       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.43it/s]

                   all        278        284      0.868      0.794      0.865       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/300      9.91G      1.007     0.7253      1.189         14       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.869      0.744      0.849      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/300      9.91G     0.9889     0.6994      1.163          5       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.883      0.816      0.873      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/300      9.91G      1.036      0.706      1.202          3       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.36it/s]

                   all        278        284      0.873      0.843      0.868      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/300      9.91G      1.016     0.7255      1.187         10       1216: 100%|██████████| 70/70 [00:25<00:00,  2.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.39it/s]

                   all        278        284      0.848      0.809       0.86       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/300      9.91G      1.037     0.7274        1.2          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.41it/s]

                   all        278        284       0.91      0.789      0.872      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/300      9.91G      1.026     0.7019      1.183         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.41it/s]

                   all        278        284      0.897      0.772      0.859      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/300      9.91G      1.016     0.7221      1.186          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.37it/s]

                   all        278        284      0.878      0.802      0.848       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/300      9.91G      1.004     0.7201       1.17          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.919      0.775      0.848      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/300      9.91G      1.013     0.7297      1.185          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.35it/s]

                   all        278        284      0.934      0.781      0.864      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/300      9.91G     0.9703     0.7221      1.161          7       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284       0.95      0.793       0.88      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/300      9.91G     0.9846     0.6949      1.173          6       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.39it/s]

                   all        278        284      0.865        0.8      0.864      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/300      9.91G      1.008     0.6766      1.179          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.27it/s]

                   all        278        284      0.893      0.798      0.853       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/300      9.91G     0.9993     0.6903      1.165          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.41it/s]

                   all        278        284      0.893      0.791      0.861      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/300      9.91G     0.9691     0.6652      1.151         10       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.865      0.785      0.841       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/300      9.91G     0.9802     0.6817      1.151          5       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.42it/s]

                   all        278        284      0.903      0.758      0.857      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/300      9.91G      1.017     0.6868      1.186         13       1216: 100%|██████████| 70/70 [00:24<00:00,  2.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.27it/s]

                   all        278        284      0.883      0.789      0.867      0.535

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/300      9.91G     0.9237     0.6294      1.136         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284      0.902      0.792      0.869      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/300      9.91G     0.9492     0.6554      1.138         11       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.37it/s]

                   all        278        284      0.865      0.812      0.863      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/300      9.91G     0.9717     0.6633      1.157         12       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.888      0.825      0.869      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/300      9.91G     0.9462     0.6648      1.143          5       1216: 100%|██████████| 70/70 [00:24<00:00,  2.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.38it/s]

                   all        278        284       0.89      0.777      0.856      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/300      9.91G     0.9471     0.6562      1.139          9       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.34it/s]

                   all        278        284      0.909      0.762      0.849      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/300      9.91G      0.949     0.6616      1.148          8       1216: 100%|██████████| 70/70 [00:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:02<00:00,  3.40it/s]

                   all        278        284      0.926        0.8      0.868      0.534
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 71, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

91 epochs completed in 0.721 hours.
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200/weights/last.pt, 5.6MB
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200/weights/best.pt, 5.6MB

Validating /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200/weights/best.pt...
Ultralytics 8.3.104 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (NVIDIA L4, 22693MiB)
YOLO11n summary (fused): 100 layers, 2,583,517 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.76it/s]

                   all        278        284      0.887       0.81      0.872      0.544
               Apoidea         10         10       0.97        0.6      0.667      0.392
             Arachnida         15         15      0.918      0.747      0.865      0.477
            Brachycera         16         16      0.784      0.875       0.93      0.631
            Coleoptera         51         51      0.912      0.961      0.975      0.708
            Formicidae         67         73      0.899      0.863      0.906       0.61
            Nematocera         95         95      0.921      0.947      0.953      0.601
            Syraphidae         24         24      0.801      0.673      0.809      0.388
Speed: 0.8ms preprocess, 5.7ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/train_yolo11n_reindexed_1200
🔍 Evaluating on validation set...

  0%|          | 0/278 [00:00<?, ?it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1576697.jpg: 1216x1216 1 Formicidae, 10.5ms
Speed: 10.8ms preprocess, 10.5ms inference, 1.6ms postprocess per image at shape (1, 3, 1216, 1216)

  0%|          | 1/278 [00:00<04:36,  1.00it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1174454.jpg: 1024x1216 1 Brachycera, 1 Nematocera, 71.9ms
Speed: 10.6ms preprocess, 71.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1216)

  1%|          | 2/278 [00:01<04:22,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802958.jpg: 1216x1216 1 Coleoptera, 11.2ms
Speed: 9.7ms preprocess, 11.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

  1%|          | 3/278 [00:02<04:23,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1892601.jpg: 1216x1216 1 Formicidae, 10.6ms
Speed: 9.9ms preprocess, 10.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  1%|▏         | 4/278 [00:04<04:48,  1.05s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1035967.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 10.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  2%|▏         | 5/278 [00:04<04:29,  1.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869664.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 11.1ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  2%|▏         | 6/278 [00:06<05:04,  1.12s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1658656.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.5ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  3%|▎         | 7/278 [00:07<04:37,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1883122.jpg: 1216x1216 1 Formicidae, 12.6ms
Speed: 9.9ms preprocess, 12.6ms inference, 1.8ms postprocess per image at shape (1, 3, 1216, 1216)

  3%|▎         | 8/278 [00:08<04:34,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650228.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 10.8ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  3%|▎         | 9/278 [00:08<04:17,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_499672.jpg: 928x1216 1 Syraphidae, 80.0ms
Speed: 10.4ms preprocess, 80.0ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

  4%|▎         | 10/278 [00:09<04:18,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1739113.jpg: 1216x1216 1 Arachnida, 1 Coleoptera, 11.0ms
Speed: 9.6ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  4%|▍         | 11/278 [00:10<04:15,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626638.jpg: 1216x1216 1 Formicidae, 10.6ms
Speed: 13.5ms preprocess, 10.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  4%|▍         | 12/278 [00:11<04:11,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1680229.jpg: 1216x1216 1 Nematocera, 11.1ms
Speed: 10.4ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  5%|▍         | 13/278 [00:12<04:07,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542164.jpg: 864x1216 1 Arachnida, 1 Formicidae, 74.2ms
Speed: 8.9ms preprocess, 74.2ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1216)

  5%|▌         | 14/278 [00:13<04:17,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1705644.jpg: 1216x1216 2 Nematoceras, 11.0ms
Speed: 9.3ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

  5%|▌         | 15/278 [00:15<04:36,  1.05s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703727.jpg: 928x1216 1 Brachycera, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

  6%|▌         | 16/278 [00:16<04:38,  1.06s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1679968.jpg: 1216x1216 1 Formicidae, 11.0ms
Speed: 9.7ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

  6%|▌         | 17/278 [00:16<04:18,  1.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1199210.jpg: 960x1216 (no detections), 73.2ms
Speed: 10.0ms preprocess, 73.2ms inference, 0.6ms postprocess per image at shape (1, 3, 960, 1216)

  6%|▋         | 18/278 [00:17<04:22,  1.01s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1880449.jpg: 928x1216 3 Formicidaes, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

  7%|▋         | 19/278 [00:19<04:23,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1720000.jpg: 1216x1216 1 Nematocera, 10.8ms
Speed: 9.4ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

  7%|▋         | 20/278 [00:19<04:18,  1.00s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1889657.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 9.4ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  8%|▊         | 21/278 [00:20<04:09,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541911.jpg: 1216x1216 (no detections), 10.3ms
Speed: 12.1ms preprocess, 10.3ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

  8%|▊         | 22/278 [00:21<04:07,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661407.jpg: 1216x1216 1 Nematocera, 10.6ms
Speed: 10.2ms preprocess, 10.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  8%|▊         | 23/278 [00:22<04:04,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862511.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  9%|▊         | 24/278 [00:23<03:54,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1032411.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 10.7ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  9%|▉         | 25/278 [00:24<03:49,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869258.jpg: 1216x1216 1 Coleoptera, 10.7ms
Speed: 9.7ms preprocess, 10.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

  9%|▉         | 26/278 [00:25<03:41,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803945.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 10%|▉         | 27/278 [00:26<03:38,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214502.jpg: 1216x1216 1 Coleoptera, 14.5ms
Speed: 11.8ms preprocess, 14.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 10%|█         | 28/278 [00:26<03:34,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1909134.jpg: 1216x1216 1 Nematocera, 11.0ms
Speed: 10.1ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 10%|█         | 29/278 [00:27<03:32,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_931985.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 9.9ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 11%|█         | 30/278 [00:28<03:29,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886378.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 9.5ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 11%|█         | 31/278 [00:29<03:14,  1.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1719649.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.8ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 12%|█▏        | 32/278 [00:30<03:08,  1.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803987.jpg: 1216x1216 1 Coleoptera, 10.5ms
Speed: 9.4ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 12%|█▏        | 33/278 [00:31<03:30,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1760513.jpg: 1184x1216 1 Arachnida, 1 Nematocera, 72.4ms
Speed: 12.3ms preprocess, 72.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1184, 1216)

 12%|█▏        | 34/278 [00:31<03:25,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1611112.jpg: 1216x1216 1 Formicidae, 11.1ms
Speed: 9.8ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 13%|█▎        | 35/278 [00:32<03:26,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802908.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 9.4ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 13%|█▎        | 36/278 [00:33<03:25,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1540578.jpg: 1216x1216 1 Formicidae, 10.9ms
Speed: 9.8ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 13%|█▎        | 37/278 [00:34<03:23,  1.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701561.jpg: 1216x1216 2 Syraphidaes, 10.7ms
Speed: 10.0ms preprocess, 10.7ms inference, 1.5ms postprocess per image at shape (1, 3, 1216, 1216)

 14%|█▎        | 38/278 [00:35<03:23,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1884094.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 9.6ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 14%|█▍        | 39/278 [00:36<03:22,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1831577.jpg: 1216x1216 1 Nematocera, 11.1ms
Speed: 9.7ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 14%|█▍        | 40/278 [00:36<03:19,  1.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1537477.jpg: 1216x1216 1 Formicidae, 11.1ms
Speed: 12.5ms preprocess, 11.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1216, 1216)

 15%|█▍        | 41/278 [00:38<03:50,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541858.jpg: 1216x1216 1 Nematocera, 11.5ms
Speed: 10.3ms preprocess, 11.5ms inference, 1.7ms postprocess per image at shape (1, 3, 1216, 1216)

 15%|█▌        | 42/278 [00:39<03:45,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2001820.jpg: 1216x1216 1 Nematocera, 10.6ms
Speed: 9.5ms preprocess, 10.6ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 15%|█▌        | 43/278 [00:39<03:25,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661488.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 9.8ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 16%|█▌        | 44/278 [00:40<03:20,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1693286.jpg: 1216x1216 1 Brachycera, 12.0ms
Speed: 10.0ms preprocess, 12.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 16%|█▌        | 45/278 [00:41<03:13,  1.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_758932.jpg: 1216x1216 1 Nematocera, 11.0ms
Speed: 10.1ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 17%|█▋        | 46/278 [00:42<02:57,  1.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893193.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 9.5ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 17%|█▋        | 47/278 [00:42<02:59,  1.28it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893214.jpg: 1216x1216 1 Formicidae, 10.2ms
Speed: 9.7ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 17%|█▋        | 48/278 [00:43<03:08,  1.22it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1560917.jpg: 928x1216 1 Apoidea, 1 Brachycera, 10.9ms
Speed: 9.7ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

 18%|█▊        | 49/278 [00:44<03:19,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626454.jpg: 1216x1216 2 Formicidaes, 11.4ms
Speed: 10.4ms preprocess, 11.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 18%|█▊        | 50/278 [00:45<03:18,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1208580.jpg: 1216x1216 1 Nematocera, 10.6ms
Speed: 9.7ms preprocess, 10.6ms inference, 1.5ms postprocess per image at shape (1, 3, 1216, 1216)

 18%|█▊        | 51/278 [00:46<03:00,  1.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869228.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 9.4ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 19%|█▊        | 52/278 [00:47<03:01,  1.24it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_405031.jpg: 928x1216 1 Syraphidae, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 19%|█▉        | 53/278 [00:48<03:08,  1.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1589547.jpg: 1216x1216 1 Nematocera, 10.8ms
Speed: 11.5ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 19%|█▉        | 54/278 [00:48<03:08,  1.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1607684.jpg: 1216x1216 1 Formicidae, 10.1ms
Speed: 9.8ms preprocess, 10.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 20%|█▉        | 55/278 [00:49<03:09,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893434.jpg: 1216x1216 1 Formicidae, 10.2ms
Speed: 9.9ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 20%|██        | 56/278 [00:50<03:08,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626230.jpg: 1216x1216 2 Formicidaes, 10.4ms
Speed: 9.6ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 21%|██        | 57/278 [00:51<03:07,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1544074.jpg: 960x1216 1 Syraphidae, 11.0ms
Speed: 10.0ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 960, 1216)

 21%|██        | 58/278 [00:52<03:09,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680031.jpg: 1216x1216 1 Formicidae, 11.0ms
Speed: 10.0ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 21%|██        | 59/278 [00:53<03:11,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_488523.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 9.7ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 22%|██▏       | 60/278 [00:54<03:10,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_931996.jpg: 1216x1216 1 Nematocera, 14.8ms
Speed: 9.6ms preprocess, 14.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 22%|██▏       | 61/278 [00:54<03:07,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_14144.jpg: 704x1216 1 Syraphidae, 72.4ms
Speed: 7.5ms preprocess, 72.4ms inference, 1.3ms postprocess per image at shape (1, 3, 704, 1216)

 22%|██▏       | 62/278 [00:56<03:25,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1558288.jpg: 1216x1216 1 Formicidae, 11.3ms
Speed: 9.9ms preprocess, 11.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 23%|██▎       | 63/278 [00:57<03:27,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/991_1813221.jpg: 960x1216 (no detections), 10.8ms
Speed: 10.0ms preprocess, 10.8ms inference, 0.6ms postprocess per image at shape (1, 3, 960, 1216)

 23%|██▎       | 64/278 [00:58<03:31,  1.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1885403.jpg: 928x1216 1 Formicidae, 11.3ms
Speed: 9.6ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 23%|██▎       | 65/278 [00:59<03:26,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2001915.jpg: 1216x1216 1 Nematocera, 11.6ms
Speed: 9.8ms preprocess, 11.6ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 24%|██▎       | 66/278 [00:59<03:22,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/859_1832273.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 10.2ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 24%|██▍       | 67/278 [01:00<03:17,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943955.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 11.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 24%|██▍       | 68/278 [01:02<03:38,  1.04s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705250.jpg: 1184x1216 1 Brachycera, 10.9ms
Speed: 12.1ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1184, 1216)

 25%|██▍       | 69/278 [01:03<03:28,  1.00it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1543606.jpg: 1216x1216 1 Brachycera, 1 Formicidae, 11.3ms
Speed: 11.1ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 25%|██▌       | 70/278 [01:03<03:20,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1583461.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 10.0ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 26%|██▌       | 71/278 [01:04<03:01,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661404.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 26%|██▌       | 72/278 [01:05<02:47,  1.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1590245.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.7ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 26%|██▋       | 73/278 [01:06<02:48,  1.22it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214640.jpg: 960x1216 1 Nematocera, 11.1ms
Speed: 10.2ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1216)

 27%|██▋       | 74/278 [01:07<03:43,  1.09s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1539172.jpg: 1216x1216 1 Formicidae, 11.2ms
Speed: 9.9ms preprocess, 11.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 27%|██▋       | 75/278 [01:08<03:36,  1.07s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1760492.jpg: 1216x1216 1 Arachnida, 10.2ms
Speed: 9.9ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 27%|██▋       | 76/278 [01:09<03:21,  1.00it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364929.jpg: 1216x1216 1 Arachnida, 10.7ms
Speed: 9.7ms preprocess, 10.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 28%|██▊       | 77/278 [01:10<03:13,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_499671.jpg: 928x1216 1 Syraphidae, 11.0ms
Speed: 10.0ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

 28%|██▊       | 78/278 [01:11<03:01,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310900.jpg: 928x1216 1 Syraphidae, 10.2ms
Speed: 9.4ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

 28%|██▊       | 79/278 [01:12<03:02,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1859767.jpg: 1216x1216 1 Nematocera, 11.1ms
Speed: 11.6ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 29%|██▉       | 80/278 [01:13<03:23,  1.03s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1263711.jpg: 896x1216 1 Nematocera, 70.6ms
Speed: 8.6ms preprocess, 70.6ms inference, 1.3ms postprocess per image at shape (1, 3, 896, 1216)

 29%|██▉       | 81/278 [01:14<03:17,  1.00s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1730099.jpg: 1216x1216 1 Coleoptera, 2 Nematoceras, 11.3ms
Speed: 9.7ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 29%|██▉       | 82/278 [01:15<03:10,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214505.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 30%|██▉       | 83/278 [01:16<03:03,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_983481.jpg: 960x1216 1 Apoidea, 11.3ms
Speed: 10.1ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1216)

 30%|███       | 84/278 [01:17<02:58,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886365.jpg: 1216x1216 1 Formicidae, 11.4ms
Speed: 9.9ms preprocess, 11.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 31%|███       | 85/278 [01:18<03:03,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1129307.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.7ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 31%|███       | 86/278 [01:19<02:57,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1304800.jpg: 1024x1216 1 Coleoptera, 11.0ms
Speed: 10.9ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1216)

 31%|███▏      | 87/278 [01:20<03:04,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1539168.jpg: 1216x1216 1 Formicidae, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 32%|███▏      | 88/278 [01:20<02:58,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1892602.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 9.8ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 32%|███▏      | 89/278 [01:21<03:02,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943961.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 10.4ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 32%|███▏      | 90/278 [01:22<02:54,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541881.jpg: 1216x1216 1 Nematocera, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 33%|███▎      | 91/278 [01:23<02:49,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1793456.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.7ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 33%|███▎      | 92/278 [01:24<02:46,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869227.jpg: 1216x1216 1 Coleoptera, 10.7ms
Speed: 9.7ms preprocess, 10.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 33%|███▎      | 93/278 [01:25<02:30,  1.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862547.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 9.9ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 34%|███▍      | 94/278 [01:26<02:33,  1.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680046.jpg: 960x1216 1 Formicidae, 11.0ms
Speed: 10.1ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1216)

 34%|███▍      | 95/278 [01:26<02:36,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1756184.jpg: 1216x1216 1 Formicidae, 10.9ms
Speed: 9.6ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 35%|███▍      | 96/278 [01:28<02:49,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_376520.jpg: 704x1216 1 Syraphidae, 11.1ms
Speed: 7.6ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 704, 1216)

 35%|███▍      | 97/278 [01:29<02:52,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1558357.jpg: 1216x1216 1 Formicidae, 11.2ms
Speed: 9.7ms preprocess, 11.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 35%|███▌      | 98/278 [01:29<02:46,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1596975.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 10.0ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 36%|███▌      | 99/278 [01:30<02:42,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1296685.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 9.9ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 36%|███▌      | 100/278 [01:31<02:37,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542166.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.4ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 36%|███▋      | 101/278 [01:32<02:36,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_503051.jpg: 704x1216 1 Syraphidae, 14.1ms
Speed: 7.9ms preprocess, 14.1ms inference, 1.7ms postprocess per image at shape (1, 3, 704, 1216)

 37%|███▋      | 102/278 [01:33<02:59,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869236.jpg: 1216x1216 1 Coleoptera, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 37%|███▋      | 103/278 [01:34<02:49,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935393.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 37%|███▋      | 104/278 [01:35<02:57,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1739198.jpg: 1216x1216 1 Coleoptera, 10.9ms
Speed: 9.7ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 38%|███▊      | 105/278 [01:36<02:55,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/34_977656.jpg: 1216x1216 1 Arachnida, 1 Coleoptera, 1 Nematocera, 10.2ms
Speed: 10.0ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 38%|███▊      | 106/278 [01:37<02:47,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661365.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.8ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 38%|███▊      | 107/278 [01:38<02:58,  1.04s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_710011.jpg: 704x1216 1 Syraphidae, 11.6ms
Speed: 7.8ms preprocess, 11.6ms inference, 1.6ms postprocess per image at shape (1, 3, 704, 1216)

 39%|███▉      | 108/278 [01:39<02:53,  1.02s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578215.jpg: 1216x1216 1 Nematocera, 11.1ms
Speed: 9.7ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 39%|███▉      | 109/278 [01:40<02:42,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1202777.jpg: 1216x1216 1 Coleoptera, 1 Nematocera, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 40%|███▉      | 110/278 [01:41<02:36,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680041.jpg: 928x1216 1 Formicidae, 13.8ms
Speed: 9.8ms preprocess, 13.8ms inference, 1.8ms postprocess per image at shape (1, 3, 928, 1216)

 40%|███▉      | 111/278 [01:42<02:36,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870243.jpg: 1216x1216 1 Coleoptera, 11.2ms
Speed: 9.7ms preprocess, 11.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 40%|████      | 112/278 [01:43<02:31,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1909301.jpg: 928x1216 2 Apoideas, 11.0ms
Speed: 9.6ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 41%|████      | 113/278 [01:44<02:34,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1726947.jpg: 1216x1216 1 Nematocera, 11.2ms
Speed: 9.7ms preprocess, 11.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 41%|████      | 114/278 [01:45<02:29,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_495546.jpg: 1216x1216 1 Arachnida, 1 Nematocera, 10.2ms
Speed: 11.8ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 41%|████▏     | 115/278 [01:46<02:29,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650235.jpg: 1216x1216 1 Nematocera, 10.9ms
Speed: 9.8ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 42%|████▏     | 116/278 [01:47<02:30,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1719192.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.6ms preprocess, 10.4ms inference, 1.5ms postprocess per image at shape (1, 3, 1216, 1216)

 42%|████▏     | 117/278 [01:48<02:28,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1582009.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 42%|████▏     | 118/278 [01:48<02:23,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870212.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 9.5ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 43%|████▎     | 119/278 [01:49<02:20,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680043.jpg: 960x1216 1 Formicidae, 13.5ms
Speed: 10.4ms preprocess, 13.5ms inference, 1.7ms postprocess per image at shape (1, 3, 960, 1216)

 43%|████▎     | 120/278 [01:50<02:21,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1887570.jpg: 1216x1216 1 Formicidae, 11.1ms
Speed: 9.4ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 44%|████▎     | 121/278 [01:51<02:18,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1847163.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 9.6ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 44%|████▍     | 122/278 [01:52<02:15,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1650775.jpg: 960x1216 1 Apoidea, 11.0ms
Speed: 10.2ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 960, 1216)

 44%|████▍     | 123/278 [01:53<02:17,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1565506.jpg: 1216x1216 1 Formicidae, 11.1ms
Speed: 9.8ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 45%|████▍     | 124/278 [01:54<02:15,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661377.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.5ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 45%|████▍     | 125/278 [01:54<02:13,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214590.jpg: 1216x1216 1 Coleoptera, 10.8ms
Speed: 11.0ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 45%|████▌     | 126/278 [01:55<02:13,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1225144.jpg: 1024x1216 1 Brachycera, 11.5ms
Speed: 10.6ms preprocess, 11.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1216)

 46%|████▌     | 127/278 [01:56<02:15,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_1570493.jpg: 1216x1216 1 Nematocera, 11.1ms
Speed: 9.7ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 46%|████▌     | 128/278 [01:57<02:12,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1742462.jpg: 1216x1216 1 Nematocera, 10.7ms
Speed: 14.4ms preprocess, 10.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 46%|████▋     | 129/278 [01:58<02:10,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869201.jpg: 1216x1216 1 Coleoptera, 10.9ms
Speed: 11.1ms preprocess, 10.9ms inference, 1.5ms postprocess per image at shape (1, 3, 1216, 1216)

 47%|████▋     | 130/278 [01:59<02:09,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1804174.jpg: 1216x1216 1 Coleoptera, 10.8ms
Speed: 9.6ms preprocess, 10.8ms inference, 1.6ms postprocess per image at shape (1, 3, 1216, 1216)

 47%|████▋     | 131/278 [02:00<02:07,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1947655.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 47%|████▋     | 132/278 [02:01<02:07,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214629.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 9.7ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 48%|████▊     | 133/278 [02:01<02:04,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1883119.jpg: 1216x1216 1 Formicidae, 10.8ms
Speed: 9.5ms preprocess, 10.8ms inference, 1.6ms postprocess per image at shape (1, 3, 1216, 1216)

 48%|████▊     | 134/278 [02:02<01:53,  1.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1550514.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 11.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 49%|████▊     | 135/278 [02:03<01:58,  1.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541854.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 12.0ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 49%|████▉     | 136/278 [02:04<02:05,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802914.jpg: 1216x1216 1 Coleoptera, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 49%|████▉     | 137/278 [02:05<02:09,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1690164.jpg: 928x1216 1 Formicidae, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 50%|████▉     | 138/278 [02:06<02:10,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_934398.jpg: 1216x1216 1 Arachnida, 1 Nematocera, 10.9ms
Speed: 9.9ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 50%|█████     | 139/278 [02:07<02:15,  1.02it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1263867.jpg: 928x1216 1 Nematocera, 10.9ms
Speed: 9.6ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 50%|█████     | 140/278 [02:13<05:48,  2.53s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707531.jpg: 1216x1216 1 Nematocera, 11.4ms
Speed: 9.8ms preprocess, 11.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 51%|█████     | 141/278 [02:14<04:29,  1.97s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703711.jpg: 896x1216 1 Brachycera, 11.3ms
Speed: 9.3ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 896, 1216)

 51%|█████     | 142/278 [02:15<03:52,  1.71s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1035966.jpg: 1216x1216 1 Syraphidae, 11.0ms
Speed: 9.6ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 51%|█████▏    | 143/278 [02:16<03:17,  1.46s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1585491.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.7ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 52%|█████▏    | 144/278 [02:17<02:51,  1.28s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707001.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 10.6ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 52%|█████▏    | 145/278 [02:18<02:31,  1.14s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_70781.jpg: 704x1216 1 Syraphidae, 11.2ms
Speed: 7.5ms preprocess, 11.2ms inference, 1.3ms postprocess per image at shape (1, 3, 704, 1216)

 53%|█████▎    | 146/278 [02:19<02:24,  1.10s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_15077.jpg: 704x1216 1 Syraphidae, 11.1ms
Speed: 7.4ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 704, 1216)

 53%|█████▎    | 147/278 [02:19<02:17,  1.05s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802938.jpg: 1216x1216 1 Coleoptera, 11.1ms
Speed: 10.0ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 53%|█████▎    | 148/278 [02:20<02:08,  1.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1660000.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 9.8ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 54%|█████▎    | 149/278 [02:21<02:02,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1563515.jpg: 1120x1216 2 Formicidaes, 72.4ms
Speed: 11.5ms preprocess, 72.4ms inference, 1.6ms postprocess per image at shape (1, 3, 1120, 1216)

 54%|█████▍    | 150/278 [02:22<02:03,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1788482.jpg: 1216x1216 1 Nematocera, 10.9ms
Speed: 10.1ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 54%|█████▍    | 151/278 [02:23<01:57,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1660109.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.9ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 55%|█████▍    | 152/278 [02:24<01:58,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214573.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 55%|█████▌    | 153/278 [02:25<01:54,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1544081.jpg: 960x1216 1 Syraphidae, 11.5ms
Speed: 10.0ms preprocess, 11.5ms inference, 1.4ms postprocess per image at shape (1, 3, 960, 1216)

 55%|█████▌    | 154/278 [02:26<01:54,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578478.jpg: 1216x1216 1 Nematocera, 11.0ms
Speed: 9.7ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 56%|█████▌    | 155/278 [02:27<01:47,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364920.jpg: 1216x1216 1 Arachnida, 10.2ms
Speed: 9.8ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 56%|█████▌    | 156/278 [02:27<01:45,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/34_998277.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.8ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 56%|█████▋    | 157/278 [02:28<01:43,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1551894.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 57%|█████▋    | 158/278 [02:29<01:45,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_15503.jpg: 704x1216 1 Apoidea, 11.0ms
Speed: 7.5ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 704, 1216)

 57%|█████▋    | 159/278 [02:30<01:49,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1788275.jpg: 864x1216 1 Brachycera, 1 Formicidae, 10.8ms
Speed: 9.1ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1216)

 58%|█████▊    | 160/278 [02:31<01:57,  1.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1708731.jpg: 1216x1216 1 Nematocera, 11.3ms
Speed: 11.4ms preprocess, 11.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 58%|█████▊    | 161/278 [02:32<01:52,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541890.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.8ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 58%|█████▊    | 162/278 [02:33<01:48,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886833.jpg: 1216x1216 1 Formicidae, 10.2ms
Speed: 10.9ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 59%|█████▊    | 163/278 [02:34<01:50,  1.04it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1564042.jpg: 1216x1216 1 Coleoptera, 1 Formicidae, 13.2ms
Speed: 10.3ms preprocess, 13.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1216, 1216)

 59%|█████▉    | 164/278 [02:35<01:47,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709230.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.9ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 59%|█████▉    | 165/278 [02:36<01:46,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803311.jpg: 1216x1216 2 Coleopteras, 10.3ms
Speed: 9.7ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 60%|█████▉    | 166/278 [02:37<01:42,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1833731.jpg: 1216x1216 1 Formicidae, 10.8ms
Speed: 10.1ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 60%|██████    | 167/278 [02:38<01:40,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650212.jpg: 1216x1216 1 Nematocera, 10.5ms
Speed: 9.8ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 60%|██████    | 168/278 [02:39<01:39,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1540596.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 9.7ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 61%|██████    | 169/278 [02:39<01:36,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310895.jpg: 1024x1216 1 Syraphidae, 12.3ms
Speed: 11.3ms preprocess, 12.3ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1216)

 61%|██████    | 170/278 [02:40<01:35,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1708646.jpg: 928x1216 1 Formicidae, 10.7ms
Speed: 9.5ms preprocess, 10.7ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 62%|██████▏   | 171/278 [02:41<01:42,  1.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1577457.jpg: 1216x1216 3 Nematoceras, 10.9ms
Speed: 11.5ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 62%|██████▏   | 172/278 [02:42<01:44,  1.02it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1872752.jpg: 1216x1216 1 Formicidae, 10.5ms
Speed: 9.7ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 62%|██████▏   | 173/278 [02:43<01:37,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1576661.jpg: 960x1216 1 Formicidae, 11.3ms
Speed: 9.9ms preprocess, 11.3ms inference, 1.4ms postprocess per image at shape (1, 3, 960, 1216)

 63%|██████▎   | 174/278 [02:44<01:37,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1706996.jpg: 1216x1216 1 Nematocera, 11.0ms
Speed: 10.1ms preprocess, 11.0ms inference, 2.0ms postprocess per image at shape (1, 3, 1216, 1216)

 63%|██████▎   | 175/278 [02:45<01:28,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1421739.jpg: 1216x1216 1 Arachnida, 1 Coleoptera, 11.6ms
Speed: 9.6ms preprocess, 11.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 63%|██████▎   | 176/278 [02:46<01:27,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626259.jpg: 1216x1216 2 Formicidaes, 10.9ms
Speed: 10.6ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 64%|██████▎   | 177/278 [02:47<01:28,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709242.jpg: 1216x1216 1 Nematocera, 10.6ms
Speed: 10.3ms preprocess, 10.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 64%|██████▍   | 178/278 [02:48<01:26,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1628691.jpg: 960x1216 1 Formicidae, 10.8ms
Speed: 10.1ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1216)

 64%|██████▍   | 179/278 [02:48<01:27,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802936.jpg: 1216x1216 1 Coleoptera, 11.1ms
Speed: 9.5ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 65%|██████▍   | 180/278 [02:49<01:26,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1602609.jpg: 1216x1216 1 Arachnida, 10.9ms
Speed: 9.8ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 65%|██████▌   | 181/278 [02:50<01:24,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650233.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.7ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 65%|██████▌   | 182/278 [02:51<01:23,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_1999521.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.6ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 66%|██████▌   | 183/278 [02:52<01:23,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1722814.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 11.1ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 66%|██████▌   | 184/278 [02:53<01:22,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541874.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.8ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 67%|██████▋   | 185/278 [02:54<01:20,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701558.jpg: 960x1216 (no detections), 10.7ms
Speed: 9.9ms preprocess, 10.7ms inference, 0.6ms postprocess per image at shape (1, 3, 960, 1216)

 67%|██████▋   | 186/278 [02:55<01:30,  1.02it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1621246.jpg: 1216x1216 1 Nematocera, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 67%|██████▋   | 187/278 [02:56<01:27,  1.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_766602.jpg: 1216x1216 2 Nematoceras, 10.3ms
Speed: 9.7ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 68%|██████▊   | 188/278 [02:57<01:23,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2008658.jpg: 1216x1216 1 Brachycera, 10.3ms
Speed: 12.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 68%|██████▊   | 189/278 [02:58<01:21,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1297358.jpg: 1216x1216 1 Brachycera, 10.2ms
Speed: 9.8ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 68%|██████▊   | 190/278 [02:58<01:20,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1590559.jpg: 1216x1216 1 Nematocera, 11.7ms
Speed: 10.8ms preprocess, 11.7ms inference, 2.3ms postprocess per image at shape (1, 3, 1216, 1216)

 69%|██████▊   | 191/278 [02:59<01:17,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1796311.jpg: 1216x1216 1 Nematocera, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 69%|██████▉   | 192/278 [03:00<01:15,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1559305.jpg: 1216x1216 2 Formicidaes, 10.4ms
Speed: 10.2ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 69%|██████▉   | 193/278 [03:01<01:15,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1701608.jpg: 1216x1216 (no detections), 10.4ms
Speed: 9.6ms preprocess, 10.4ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 70%|██████▉   | 194/278 [03:02<01:13,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709231.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.9ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 70%|███████   | 195/278 [03:03<01:12,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650227.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.8ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 71%|███████   | 196/278 [03:04<01:09,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1692863.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 9.9ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 71%|███████   | 197/278 [03:04<01:08,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541905.jpg: 1216x1216 1 Nematocera, 11.0ms
Speed: 9.7ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 71%|███████   | 198/278 [03:05<01:10,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701569.jpg: 1216x1216 1 Syraphidae, 10.2ms
Speed: 10.0ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 72%|███████▏  | 199/278 [03:06<01:09,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1265110.jpg: 928x1216 1 Nematocera, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 72%|███████▏  | 200/278 [03:07<01:09,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661427.jpg: 1216x1216 1 Nematocera, 11.4ms
Speed: 9.7ms preprocess, 11.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 72%|███████▏  | 201/278 [03:08<01:07,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870096.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 11.5ms preprocess, 10.3ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 73%|███████▎  | 202/278 [03:09<01:05,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803962.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 73%|███████▎  | 203/278 [03:10<01:05,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870125.jpg: 1216x1216 1 Coleoptera, 10.7ms
Speed: 9.7ms preprocess, 10.7ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 73%|███████▎  | 204/278 [03:11<01:03,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803326.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 10.4ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 74%|███████▎  | 205/278 [03:11<01:03,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214632.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 11.4ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 74%|███████▍  | 206/278 [03:12<01:01,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802976.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 9.6ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 74%|███████▍  | 207/278 [03:13<00:59,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1630250.jpg: 1216x1216 1 Formicidae, 11.5ms
Speed: 10.0ms preprocess, 11.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 75%|███████▍  | 208/278 [03:14<00:54,  1.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1610847.jpg: 928x1216 1 Brachycera, 10.8ms
Speed: 9.6ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 75%|███████▌  | 209/278 [03:15<00:57,  1.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1658717.jpg: 1216x1216 1 Nematocera, 10.9ms
Speed: 9.9ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 76%|███████▌  | 210/278 [03:16<00:57,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870208.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 9.9ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 76%|███████▌  | 211/278 [03:16<00:56,  1.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542159.jpg: 1120x1216 1 Arachnida, 11.3ms
Speed: 11.6ms preprocess, 11.3ms inference, 1.5ms postprocess per image at shape (1, 3, 1120, 1216)

 76%|███████▋  | 212/278 [03:17<00:58,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893238.jpg: 1216x1216 1 Formicidae, 11.3ms
Speed: 9.6ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 77%|███████▋  | 213/278 [03:18<00:52,  1.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870113.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 9.5ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 77%|███████▋  | 214/278 [03:19<00:53,  1.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1722852.jpg: 1216x1216 1 Coleoptera, 1 Nematocera, 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 77%|███████▋  | 215/278 [03:20<00:52,  1.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_368619.jpg: 960x1216 1 Brachycera, 1 Syraphidae, 10.9ms
Speed: 10.1ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 960, 1216)

 78%|███████▊  | 216/278 [03:21<00:53,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/859_1834070.jpg: 1216x1216 1 Arachnida, 1 Formicidae, 11.1ms
Speed: 10.4ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 78%|███████▊  | 217/278 [03:22<00:53,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1884047.jpg: 1216x1216 1 Formicidae, 10.2ms
Speed: 10.8ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 78%|███████▊  | 218/278 [03:22<00:52,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1709220.jpg: 1216x1216 1 Nematocera, 10.6ms
Speed: 10.1ms preprocess, 10.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 79%|███████▉  | 219/278 [03:23<00:51,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364909.jpg: 1216x1216 1 Arachnida, 10.3ms
Speed: 9.6ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 79%|███████▉  | 220/278 [03:24<00:49,  1.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703719.jpg: 928x1216 1 Brachycera, 11.0ms
Speed: 9.7ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 79%|███████▉  | 221/278 [03:25<00:49,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_939952.jpg: 1216x1216 (no detections), 10.9ms
Speed: 9.9ms preprocess, 10.9ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 80%|███████▉  | 222/278 [03:26<00:48,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870099.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 11.1ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 80%|████████  | 223/278 [03:27<00:47,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1730092.jpg: 1216x1216 1 Nematocera, 10.1ms
Speed: 9.5ms preprocess, 10.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 81%|████████  | 224/278 [03:28<00:46,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_13827.jpg: 704x1216 1 Syraphidae, 11.4ms
Speed: 8.2ms preprocess, 11.4ms inference, 1.4ms postprocess per image at shape (1, 3, 704, 1216)

 81%|████████  | 225/278 [03:29<00:47,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578214.jpg: 1216x1216 1 Nematocera, 11.3ms
Speed: 10.2ms preprocess, 11.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 81%|████████▏ | 226/278 [03:29<00:46,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541869.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 10.2ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 82%|████████▏ | 227/278 [03:30<00:44,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_311300.jpg: 1216x1216 (no detections), 10.3ms
Speed: 9.5ms preprocess, 10.3ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 82%|████████▏ | 228/278 [03:31<00:43,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_930779.jpg: 1216x1216 (no detections), 10.5ms
Speed: 10.0ms preprocess, 10.5ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 82%|████████▏ | 229/278 [03:32<00:42,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707082.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 11.0ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 83%|████████▎ | 230/278 [03:33<00:43,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661381.jpg: 1216x1216 1 Nematocera, 10.2ms
Speed: 9.6ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 83%|████████▎ | 231/278 [03:34<00:41,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1682266.jpg: 960x1216 2 Formicidaes, 10.9ms
Speed: 9.8ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1216)

 83%|████████▎ | 232/278 [03:35<00:42,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705255.jpg: 928x1216 1 Brachycera, 11.6ms
Speed: 9.7ms preprocess, 11.6ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

 84%|████████▍ | 233/278 [03:36<00:41,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802998.jpg: 1216x1216 1 Coleoptera, 11.0ms
Speed: 9.6ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 84%|████████▍ | 234/278 [03:37<00:40,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870207.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.7ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 85%|████████▍ | 235/278 [03:38<00:38,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1889633.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 10.9ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 85%|████████▍ | 236/278 [03:38<00:37,  1.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1891801.jpg: 1216x1216 1 Formicidae, 10.2ms
Speed: 12.3ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 85%|████████▌ | 237/278 [03:39<00:38,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1545097.jpg: 1216x1216 (no detections), 10.3ms
Speed: 10.1ms preprocess, 10.3ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 86%|████████▌ | 238/278 [03:40<00:36,  1.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1690283.jpg: 1216x1216 1 Coleoptera, 10.3ms
Speed: 9.9ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 86%|████████▌ | 239/278 [03:41<00:34,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886831.jpg: 1216x1216 1 Formicidae, 11.2ms
Speed: 11.9ms preprocess, 11.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1216, 1216)

 86%|████████▋ | 240/278 [03:42<00:34,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1572039.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 9.7ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 87%|████████▋ | 241/278 [03:43<00:32,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935478.jpg: 1216x1216 1 Coleoptera, 1 Nematocera, 10.3ms
Speed: 9.9ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 87%|████████▋ | 242/278 [03:44<00:29,  1.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1689926.jpg: 928x1216 (no detections), 10.9ms
Speed: 9.9ms preprocess, 10.9ms inference, 0.7ms postprocess per image at shape (1, 3, 928, 1216)

 87%|████████▋ | 243/278 [03:45<00:29,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705267.jpg: 896x1216 1 Brachycera, 10.9ms
Speed: 9.4ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 896, 1216)

 88%|████████▊ | 244/278 [03:45<00:27,  1.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680040.jpg: 960x1216 1 Brachycera, 11.1ms
Speed: 9.9ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 960, 1216)

 88%|████████▊ | 245/278 [03:46<00:28,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862525.jpg: 1216x1216 1 Coleoptera, 10.9ms
Speed: 9.5ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 88%|████████▊ | 246/278 [03:47<00:27,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541903.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 10.4ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 89%|████████▉ | 247/278 [03:48<00:27,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541909.jpg: 1120x1216 1 Nematocera, 11.0ms
Speed: 11.7ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1120, 1216)

 89%|████████▉ | 248/278 [03:49<00:26,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541855.jpg: 1216x1216 1 Nematocera, 11.2ms
Speed: 12.1ms preprocess, 11.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 90%|████████▉ | 249/278 [03:50<00:26,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680044.jpg: 960x1216 (no detections), 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 0.6ms postprocess per image at shape (1, 3, 960, 1216)

 90%|████████▉ | 250/278 [03:51<00:25,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_939772.jpg: 1216x1216 (no detections), 10.9ms
Speed: 9.6ms preprocess, 10.9ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 90%|█████████ | 251/278 [03:52<00:25,  1.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_938706.jpg: 928x1216 1 Apoidea, 11.0ms
Speed: 10.0ms preprocess, 11.0ms inference, 1.3ms postprocess per image at shape (1, 3, 928, 1216)

 91%|█████████ | 252/278 [03:53<00:24,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1700897.jpg: 928x1216 1 Brachycera, 10.3ms
Speed: 9.9ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

 91%|█████████ | 253/278 [03:54<00:23,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943984.jpg: 1216x1216 1 Coleoptera, 11.4ms
Speed: 9.7ms preprocess, 11.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 91%|█████████▏| 254/278 [03:54<00:21,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578240.jpg: 1216x1216 2 Nematoceras, 10.5ms
Speed: 11.2ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 92%|█████████▏| 255/278 [03:55<00:20,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870089.jpg: 1216x1216 1 Coleoptera, 10.5ms
Speed: 9.9ms preprocess, 10.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 92%|█████████▏| 256/278 [03:56<00:20,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1604091.jpg: 1216x1216 1 Nematocera, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 92%|█████████▏| 257/278 [03:57<00:19,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1446473.jpg: 1216x1216 (no detections), 10.2ms
Speed: 9.9ms preprocess, 10.2ms inference, 0.6ms postprocess per image at shape (1, 3, 1216, 1216)

 93%|█████████▎| 258/278 [03:58<00:18,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1700912.jpg: 960x1216 1 Brachycera, 11.4ms
Speed: 10.5ms preprocess, 11.4ms inference, 1.3ms postprocess per image at shape (1, 3, 960, 1216)

 93%|█████████▎| 259/278 [03:59<00:17,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1746506.jpg: 1216x1216 1 Nematocera, 11.5ms
Speed: 9.8ms preprocess, 11.5ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 94%|█████████▎| 260/278 [04:00<00:16,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214613.jpg: 1216x1216 1 Coleoptera, 12.5ms
Speed: 16.9ms preprocess, 12.5ms inference, 1.6ms postprocess per image at shape (1, 3, 1216, 1216)

 94%|█████████▍| 261/278 [04:01<00:15,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_934128.jpg: 1216x1216 1 Nematocera, 10.6ms
Speed: 9.6ms preprocess, 10.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 94%|█████████▍| 262/278 [04:02<00:14,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1563281.jpg: 1216x1216 1 Formicidae, 10.4ms
Speed: 10.0ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 95%|█████████▍| 263/278 [04:03<00:13,  1.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802956.jpg: 1216x1216 1 Coleoptera, 10.7ms
Speed: 9.9ms preprocess, 10.7ms inference, 1.5ms postprocess per image at shape (1, 3, 1216, 1216)

 95%|█████████▍| 264/278 [04:04<00:12,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1721874.jpg: 1216x1216 1 Nematocera, 10.4ms
Speed: 9.7ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 95%|█████████▌| 265/278 [04:04<00:11,  1.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1564396.jpg: 1216x1216 1 Formicidae, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 96%|█████████▌| 266/278 [04:05<00:10,  1.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1577222.jpg: 1216x1216 1 Nematocera, 10.3ms
Speed: 11.3ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 96%|█████████▌| 267/278 [04:06<00:09,  1.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1551883.jpg: 1216x1216 1 Formicidae, 10.3ms
Speed: 9.7ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 96%|█████████▋| 268/278 [04:08<00:10,  1.05s/it]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943945.jpg: 1216x1216 1 Coleoptera, 10.4ms
Speed: 9.9ms preprocess, 10.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 97%|█████████▋| 269/278 [04:08<00:08,  1.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1708728.jpg: 1184x1216 1 Nematocera, 10.8ms
Speed: 11.5ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1184, 1216)

 97%|█████████▋| 270/278 [04:09<00:07,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/991_1813226.jpg: 1056x1216 (no detections), 72.1ms
Speed: 11.1ms preprocess, 72.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1056, 1216)

 97%|█████████▋| 271/278 [04:10<00:06,  1.02it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1143735.jpg: 1216x1216 1 Brachycera, 11.1ms
Speed: 10.1ms preprocess, 11.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 98%|█████████▊| 272/278 [04:11<00:05,  1.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803155.jpg: 1216x1216 1 Coleoptera, 10.2ms
Speed: 9.5ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

 98%|█████████▊| 273/278 [04:12<00:04,  1.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1551881.jpg: 1152x1216 1 Nematocera, 71.2ms
Speed: 10.6ms preprocess, 71.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1152, 1216)

 99%|█████████▊| 274/278 [04:13<00:03,  1.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869001.jpg: 1216x1216 1 Coleoptera, 10.9ms
Speed: 9.6ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1216, 1216)

 99%|█████████▉| 275/278 [04:14<00:02,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310899.jpg: 928x1216 1 Syraphidae, 11.1ms
Speed: 9.5ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1216)

 99%|█████████▉| 276/278 [04:15<00:01,  1.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935599.jpg: 1216x1216 1 Brachycera, 1 Syraphidae, 10.8ms
Speed: 9.9ms preprocess, 10.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

100%|█████████▉| 277/278 [04:15<00:00,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870086.jpg: 1216x1216 2 Coleopteras, 11.4ms
Speed: 9.5ms preprocess, 11.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1216, 1216)

100%|██████████| 278/278 [04:16<00:00,  1.08it/s]

✅ Evaluation Summary:
Precision: 0.00%
Recall:    0.00%
F1 Score:  0.00%
→ FP saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/false_positives
→ FN saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/false_negatives
→ MC saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_1200/misclassified

In [ ]:
!pip install ultralytics
import os
import cv2
import numpy as np
from tqdm import tqdm
from ultralytics import YOLO
from sklearn.metrics import precision_score, recall_score, f1_score

# ✅ Paths
yaml_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/config.yaml"
model_path = "models/yolo11n.pt"
output_dir = "/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640"

# ✅ Train YOLOv11n model (no resume)
model = YOLO(model_path)
model.train(
    data=yaml_path,
    epochs=300,
    imgsz=640,
    patience=20,
    save=True,
    project=output_dir,
    name="train_yolo11n_reindexed_640"
)

# ✅ Validation and Evaluation
val_images_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images"
val_labels_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels"

fp_dir = os.path.join(output_dir, "false_positives")
fn_dir = os.path.join(output_dir, "false_negatives")
mc_dir = os.path.join(output_dir, "misclassified")
os.makedirs(fp_dir, exist_ok=True)
os.makedirs(fn_dir, exist_ok=True)
os.makedirs(mc_dir, exist_ok=True)

class_names = {
    0: "Apoidea", 1: "Arachnida", 2: "Brachycera", 3: "Coleoptera",
    4: "Formicidae", 5: "Nematocera", 6: "Syraphidae"
}

def compute_iou(box1, box2):
    xA, yA = max(box1[0], box2[0]), max(box1[1], box2[1])
    xB, yB = min(box1[2], box2[2]), min(box1[3], box2[3])
    inter = max(0, xB - xA) * max(0, yB - yA)
    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])
    return inter / (area1 + area2 - inter + 1e-6)

print("🔍 Evaluating on validation set...")
y_true, y_pred = [], []

for img_name in tqdm(os.listdir(val_images_path)):
    if not img_name.endswith(".jpg"):
        continue

    img_path = os.path.join(val_images_path, img_name)
    label_path = os.path.join(val_labels_path, img_name.replace(".jpg", ".txt"))
    image = cv2.imread(img_path)
    height, width = image.shape[:2]

    results = model(img_path, conf=0.25, iou=0.7)[0]
    pred_boxes = results.boxes.xyxy.cpu().numpy()
    pred_classes = results.boxes.cls.cpu().numpy()

    gt_boxes, gt_classes = [], []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                x1 = int((x - w/2) * width)
                y1 = int((y - h/2) * height)
                x2 = int((x + w/2) * width)
                y2 = int((y + h/2) * height)
                gt_boxes.append([x1, y1, x2, y2])
                gt_classes.append(int(cls))

    matched_pred = set()
    matched_gt = set()

    for i, pbox in enumerate(pred_boxes):
        px1, py1, px2, py2 = map(int, pbox[:4])
        pred_cls = int(pred_classes[i])
        for j, gtbox in enumerate(gt_boxes):
            iou = compute_iou(pbox[:4], gtbox)
            if iou > 0.3:
                matched_pred.add(i)
                matched_gt.add(j)
                if pred_cls != gt_classes[j]:
                    img_copy = image.copy()
                    gx1, gy1, gx2, gy2 = gtbox
                    cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (0, 255, 0), 2)
                    cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
                    cv2.putText(img_copy, f"Pred: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
                    cv2.putText(img_copy, f"GT: {class_names.get(gt_classes[j])}", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)
                    cv2.imwrite(os.path.join(mc_dir, f"mc_{img_name}"), img_copy)
                break

    for i, pbox in enumerate(pred_boxes):
        if i not in matched_pred:
            y_true.append(0)
            y_pred.append(1)
            px1, py1, px2, py2 = map(int, pbox[:4])
            pred_cls = int(pred_classes[i])
            img_copy = image.copy()
            cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
            cv2.putText(img_copy, f"FP: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
            cv2.imwrite(os.path.join(fp_dir, f"fp_{img_name}"), img_copy)

    for j, gtbox in enumerate(gt_boxes):
        if j not in matched_gt:
            y_true.append(1)
            y_pred.append(0)
            gx1, gy1, gx2, gy2 = gtbox
            img_copy = image.copy()
            cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (255, 0, 0), 2)
            cv2.putText(img_copy, "FN", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            cv2.imwrite(os.path.join(fn_dir, f"fn_{img_name}"), img_copy)

# ✅ Summary metrics
precision = precision_score(y_true, y_pred) * 100
recall = recall_score(y_true, y_pred) * 100
f1 = f1_score(y_true, y_pred) * 100

print("\n✅ Evaluation Summary:")
print(f"Precision: {precision:.2f}%")
print(f"Recall:    {recall:.2f}%")
print(f"F1 Score:  {f1:.2f}%")
print(f"→ FP saved to: {fp_dir}")
print(f"→ FN saved to: {fn_dir}")
print(f"→ MC saved to: {mc_dir}")

Collecting ultralytics
  Downloading ultralytics-8.3.106-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy<=2.1.1,>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.14.1)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.2.2)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.13.2)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.14-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.1.31)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Downloading ultralytics-8.3.106-py3-none-any.whl (972 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 973.0/973.0 kB 29.4 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 109.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 76.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 51.9 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.5 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 93.7 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.14-py3-none-any.whl (26 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.106 ultralytics-thop-2.0.14
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'models/yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 94.3MB/s]

Ultralytics 8.3.106 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: task=detect, mode=train, model=models/yolo11n.pt, data=/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/config.yaml, epochs=300, time=None, patience=20, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640, name=train_yolo11n_reindexed_640, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...

100%|██████████| 755k/755k [00:00<00:00, 20.0MB/s]

Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    432037  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]
YOLO11n summary: 181 layers, 2,591,205 parameters, 2,591,189 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 85.3MB/s]

AMP: checks passed ✅

train: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/train/labels.cache... 1110 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1110/1110 [00:00<?, ?it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/labels.cache... 278 images, 0 backgrounds, 0 corrupt: 100%|██████████| 278/278 [00:00<?, ?it/s]

Plotting labels to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/300       2.2G      2.316      5.755      1.747          9        640: 100%|██████████| 70/70 [04:15<00:00,  3.64s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.47it/s]

                   all        278        284    0.00457      0.695     0.0885     0.0427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/300      2.61G      1.687      3.878      1.373          3        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.47it/s]

                   all        278        284       0.44      0.316      0.313      0.165

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/300      2.63G      1.637      3.164      1.402          7        640: 100%|██████████| 70/70 [00:40<00:00,  1.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.95it/s]

                   all        278        284      0.474      0.358      0.322      0.178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/300      2.64G      1.615      2.789        1.4          8        640: 100%|██████████| 70/70 [00:40<00:00,  1.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.23it/s]

                   all        278        284      0.356      0.368      0.337      0.167

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/300      2.64G      1.616      2.482      1.401          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.12it/s]

                   all        278        284      0.499      0.491      0.452      0.262

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/300      2.64G      1.612       2.38      1.413          5        640: 100%|██████████| 70/70 [00:42<00:00,  1.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.69it/s]

                   all        278        284      0.521      0.526      0.543      0.312

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/300      2.64G      1.569      2.102      1.409         10        640: 100%|██████████| 70/70 [00:38<00:00,  1.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.59it/s]

                   all        278        284      0.588      0.562      0.573      0.343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/300      2.64G      1.573      1.986      1.434          5        640: 100%|██████████| 70/70 [00:38<00:00,  1.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.75it/s]

                   all        278        284      0.572      0.649      0.635      0.347

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/300      2.64G       1.49      1.802      1.344          7        640: 100%|██████████| 70/70 [00:40<00:00,  1.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.05it/s]

                   all        278        284      0.721      0.603      0.653      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/300      2.64G      1.479      1.704      1.335          8        640: 100%|██████████| 70/70 [00:41<00:00,  1.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.11it/s]

                   all        278        284      0.634      0.508      0.595      0.343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/300      2.64G      1.503      1.636       1.37          4        640: 100%|██████████| 70/70 [00:42<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.61it/s]

                   all        278        284      0.554        0.6      0.613      0.342

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/300      2.66G      1.483      1.581      1.344          5        640: 100%|██████████| 70/70 [00:42<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.17it/s]

                   all        278        284      0.765      0.595      0.672      0.388

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/300      2.68G       1.51      1.537      1.387          9        640: 100%|██████████| 70/70 [00:40<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.12it/s]

                   all        278        284      0.715        0.6      0.653      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/300      2.68G      1.448      1.464      1.329         10        640: 100%|██████████| 70/70 [00:40<00:00,  1.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.15it/s]

                   all        278        284      0.706      0.647      0.664      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/300      2.68G      1.449      1.444      1.305          9        640: 100%|██████████| 70/70 [00:40<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.53it/s]

                   all        278        284      0.699      0.658      0.688      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/300      2.68G      1.381      1.388      1.271         11        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.12it/s]

                   all        278        284      0.636      0.644      0.638      0.365

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/300      2.69G      1.422      1.362      1.319          6        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.17it/s]

                   all        278        284      0.851      0.628      0.733      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/300      2.69G       1.39       1.24      1.295         15        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.79it/s]

                   all        278        284      0.772      0.663      0.718      0.419

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/300      2.69G      1.392      1.253      1.313         11        640: 100%|██████████| 70/70 [00:39<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.63it/s]

                   all        278        284      0.767      0.646      0.731      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/300      2.69G      1.403      1.285      1.319          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.07it/s]

                   all        278        284      0.759      0.616      0.696      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/300      2.69G       1.38      1.246      1.299         17        640: 100%|██████████| 70/70 [00:41<00:00,  1.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.85it/s]

                   all        278        284      0.764      0.645       0.72      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/300      2.69G      1.367      1.172      1.292          7        640: 100%|██████████| 70/70 [00:40<00:00,  1.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.66it/s]

                   all        278        284      0.837      0.657      0.756      0.469

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/300      2.69G      1.358      1.153      1.253         12        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.26it/s]

                   all        278        284      0.818      0.661      0.748      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/300      2.69G      1.387      1.208      1.323         11        640: 100%|██████████| 70/70 [00:40<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.25it/s]

                   all        278        284      0.703      0.681      0.733      0.455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/300      2.69G      1.356      1.181      1.296          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.26it/s]

                   all        278        284      0.788      0.738      0.795      0.475

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/300      2.69G      1.391      1.154      1.306         13        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.13it/s]

                   all        278        284      0.746      0.713      0.743       0.43

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/300      2.69G      1.317      1.112      1.265         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.55it/s]

                   all        278        284      0.729      0.747      0.763      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/300      2.69G      1.338      1.113      1.279          4        640: 100%|██████████| 70/70 [00:38<00:00,  1.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.95it/s]

                   all        278        284      0.879      0.619      0.743       0.44

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/300      2.69G      1.314      1.061      1.267          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.20it/s]

                   all        278        284      0.877      0.706      0.792      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/300      2.69G      1.324      1.126      1.271          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.76it/s]

                   all        278        284      0.772       0.71      0.762      0.444

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/300      2.69G      1.309      1.083      1.278         10        640: 100%|██████████| 70/70 [00:41<00:00,  1.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.61it/s]

                   all        278        284       0.78      0.672      0.747      0.464

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/300      2.69G      1.299      1.033      1.244         11        640: 100%|██████████| 70/70 [00:39<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.17it/s]

                   all        278        284      0.879      0.679      0.787      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/300      2.69G      1.339       1.06      1.283          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.19it/s]

                   all        278        284      0.898       0.68      0.803      0.478

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/300      2.69G      1.298      1.016      1.242         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.20it/s]

                   all        278        284      0.806      0.671      0.765      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/300      2.69G      1.313      1.038      1.273          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.82it/s]

                   all        278        284      0.887      0.654       0.78      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/300      2.69G      1.294      1.044      1.244          8        640: 100%|██████████| 70/70 [00:36<00:00,  1.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.67it/s]

                   all        278        284      0.809      0.718      0.793      0.516

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/300      2.69G      1.286      1.016      1.256          3        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.09it/s]

                   all        278        284      0.895       0.69      0.812      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/300      2.69G      1.301     0.9491      1.283          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.14it/s]

                   all        278        284      0.849      0.762      0.819      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/300      2.69G      1.286     0.9692      1.252          6        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.31it/s]

                   all        278        284      0.873       0.68      0.779      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/300      2.69G      1.268     0.9679      1.223         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.85it/s]

                   all        278        284       0.78      0.759      0.811      0.484

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/300      2.69G       1.26     0.9452      1.257          9        640: 100%|██████████| 70/70 [00:37<00:00,  1.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.54it/s]

                   all        278        284      0.868      0.721      0.815      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/300      2.69G      1.231      0.914      1.219          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.96it/s]

                   all        278        284      0.838      0.735      0.817      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/300      2.69G      1.248     0.9403       1.23          8        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.39it/s]

                   all        278        284      0.857      0.779      0.827      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/300      2.69G      1.239     0.9135       1.23         12        640: 100%|██████████| 70/70 [00:45<00:00,  1.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.60it/s]

                   all        278        284      0.903      0.711      0.808      0.476

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/300      2.69G      1.244     0.8982       1.22          4        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.19it/s]

                   all        278        284       0.83      0.747      0.826      0.514

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/300      2.69G      1.227     0.9014      1.236         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        278        284      0.908      0.748      0.802      0.507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/300      2.69G      1.241       0.91      1.228          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.22it/s]

                   all        278        284      0.904      0.739      0.832      0.505

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/300      2.69G      1.214     0.8638      1.213          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.97it/s]

                   all        278        284      0.863      0.773      0.826      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/300      2.69G      1.238     0.9013      1.232         15        640: 100%|██████████| 70/70 [00:38<00:00,  1.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.69it/s]

                   all        278        284       0.89      0.653      0.784       0.47

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/300      2.69G      1.255     0.8771      1.229         10        640: 100%|██████████| 70/70 [00:37<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.55it/s]

                   all        278        284      0.917      0.707      0.807      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/300      2.69G      1.238     0.8395      1.231         12        640: 100%|██████████| 70/70 [00:38<00:00,  1.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.92it/s]

                   all        278        284      0.881      0.675       0.82      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/300      2.69G      1.213     0.8806      1.208          6        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.19it/s]

                   all        278        284      0.851      0.809      0.847      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/300      2.69G      1.189     0.8199      1.209         12        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.14it/s]

                   all        278        284      0.887      0.754      0.826      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/300      2.69G      1.187     0.8252      1.202         10        640: 100%|██████████| 70/70 [00:38<00:00,  1.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.13it/s]

                   all        278        284       0.84      0.784      0.836      0.497

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/300      2.69G      1.207      0.822      1.199          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.91it/s]

                   all        278        284      0.888      0.741      0.822      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/300      2.69G      1.207     0.8411      1.208          6        640: 100%|██████████| 70/70 [00:38<00:00,  1.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.60it/s]

                   all        278        284      0.866      0.739      0.827      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/300      2.69G      1.218     0.8558      1.223         11        640: 100%|██████████| 70/70 [00:38<00:00,  1.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.82it/s]

                   all        278        284      0.895      0.755      0.803      0.481

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/300      2.69G      1.203     0.8167      1.208          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.27it/s]

                   all        278        284      0.826      0.804       0.85       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/300      2.69G      1.199     0.8253      1.209          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.21it/s]

                   all        278        284      0.876      0.731       0.81       0.46

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/300      2.69G      1.219     0.8442      1.217          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.22it/s]

                   all        278        284      0.885      0.723      0.816      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/300      2.69G      1.201     0.8073      1.214         10        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.93it/s]

                   all        278        284      0.853      0.781      0.843       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/300      2.69G      1.165     0.8094       1.18          9        640: 100%|██████████| 70/70 [00:38<00:00,  1.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.54it/s]

                   all        278        284      0.895      0.779      0.839      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/300      2.69G      1.127     0.7864      1.177         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.24it/s]

                   all        278        284      0.872      0.702      0.802      0.497

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/300      2.69G       1.14     0.7368      1.175         11        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        278        284      0.748       0.81      0.814      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/300      2.69G      1.216     0.8425      1.209         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.21it/s]

                   all        278        284      0.824      0.761      0.795      0.474

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/300      2.69G      1.187     0.7791      1.184          4        640: 100%|██████████| 70/70 [00:39<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.10it/s]

                   all        278        284      0.874       0.76      0.828      0.505

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/300      2.69G      1.149     0.7557      1.175          8        640: 100%|██████████| 70/70 [00:38<00:00,  1.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.61it/s]

                   all        278        284      0.829      0.779      0.841      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/300      2.69G      1.168     0.7758      1.189          6        640: 100%|██████████| 70/70 [00:37<00:00,  1.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.53it/s]

                   all        278        284      0.918      0.741      0.851      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/300      2.69G      1.141     0.7878      1.172         11        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.32it/s]

                   all        278        284      0.829      0.805      0.848        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/300      2.69G      1.138     0.7425      1.182         12        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.30it/s]

                   all        278        284      0.842      0.767       0.83      0.507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/300      2.69G      1.123     0.7352      1.172         10        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.22it/s]

                   all        278        284      0.871      0.807      0.855      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/300      2.69G      1.146     0.7594      1.176          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.00it/s]

                   all        278        284      0.916      0.732      0.846       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/300      2.69G      1.172     0.7964      1.199         10        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.72it/s]

                   all        278        284      0.889      0.775       0.82      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/300      2.69G       1.15     0.7277       1.18         11        640: 100%|██████████| 70/70 [00:37<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.53it/s]

                   all        278        284      0.853      0.772      0.827      0.502

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/300      2.69G      1.133      0.741      1.162         14        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.08it/s]

                   all        278        284       0.88      0.752      0.828      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/300      2.69G      1.138     0.7391      1.158          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.23it/s]

                   all        278        284      0.914      0.775      0.865       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/300      2.69G      1.099      0.722      1.162          7        640: 100%|██████████| 70/70 [00:40<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.37it/s]

                   all        278        284      0.854      0.808      0.856      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/300      2.69G      1.106     0.7161      1.157         17        640: 100%|██████████| 70/70 [00:39<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.83it/s]

                   all        278        284        0.9       0.75      0.836      0.492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/300      2.69G      1.139     0.7399      1.171          7        640: 100%|██████████| 70/70 [00:38<00:00,  1.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.57it/s]

                   all        278        284      0.876      0.788       0.84      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/300      2.69G      1.084      0.706      1.142         10        640: 100%|██████████| 70/70 [00:38<00:00,  1.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.76it/s]

                   all        278        284      0.906      0.768      0.861      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/300      2.69G      1.086     0.6902       1.14          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        278        284      0.859      0.816       0.87      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/300      2.69G      1.092     0.6949      1.148          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.13it/s]

                   all        278        284      0.833      0.809      0.848       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/300      2.69G      1.069     0.6863      1.142          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.20it/s]

                   all        278        284      0.905      0.735       0.84      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/300      2.69G      1.102     0.6988      1.161          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.13it/s]

                   all        278        284      0.876      0.795      0.873      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/300      2.69G      1.136     0.7125      1.173          9        640: 100%|██████████| 70/70 [00:38<00:00,  1.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.67it/s]

                   all        278        284      0.849      0.833      0.867       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/300      2.69G      1.095     0.6892      1.145          9        640: 100%|██████████| 70/70 [00:38<00:00,  1.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.72it/s]

                   all        278        284      0.897      0.758      0.864      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/300      2.69G      1.086     0.7059       1.15          6        640: 100%|██████████| 70/70 [00:38<00:00,  1.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.43it/s]

                   all        278        284      0.932      0.782      0.874      0.536

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/300      2.69G      1.085     0.6921      1.143          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.17it/s]

                   all        278        284      0.911      0.781      0.842      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/300      2.69G      1.099     0.6972      1.154          8        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.27it/s]

                   all        278        284       0.84      0.828      0.843      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/300      2.69G      1.084     0.6812      1.148          7        640: 100%|██████████| 70/70 [00:39<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.21it/s]

                   all        278        284       0.86       0.83      0.869       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/300      2.69G      1.061     0.6731      1.127         15        640: 100%|██████████| 70/70 [00:39<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.07it/s]

                   all        278        284      0.924      0.741      0.821      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/300      2.69G      1.063     0.6819      1.128         10        640: 100%|██████████| 70/70 [00:38<00:00,  1.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.76it/s]

                   all        278        284      0.852      0.792      0.832      0.518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/300      2.69G      1.071     0.6781      1.129          8        640: 100%|██████████| 70/70 [00:37<00:00,  1.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.66it/s]

                   all        278        284      0.897      0.766      0.831       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/300      2.69G      1.043     0.6616      1.121          7        640: 100%|██████████| 70/70 [00:38<00:00,  1.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.11it/s]

                   all        278        284      0.904      0.775      0.841      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/300      2.69G      1.066     0.6813      1.145         12        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        278        284      0.907      0.741      0.825      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/300      2.69G      1.074     0.6834      1.146          7        640: 100%|██████████| 70/70 [00:38<00:00,  1.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        278        284      0.896       0.76      0.837       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/300      2.69G       1.06     0.6604      1.127          9        640: 100%|██████████| 70/70 [00:39<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.36it/s]

                   all        278        284       0.88      0.815      0.852      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/300      2.69G      1.042     0.6573      1.139         11        640: 100%|██████████| 70/70 [00:38<00:00,  1.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.93it/s]

                   all        278        284      0.841       0.79      0.824      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/300      2.69G       1.08     0.6639      1.151          5        640: 100%|██████████| 70/70 [00:38<00:00,  1.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.10it/s]

                   all        278        284      0.906      0.778      0.843      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/300      2.69G      1.026     0.6459      1.119          1        640: 100%|██████████| 70/70 [00:37<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.57it/s]

                   all        278        284      0.863      0.803      0.853      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    101/300      2.69G      1.043     0.6358      1.129         10        640: 100%|██████████| 70/70 [00:37<00:00,  1.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.78it/s]

                   all        278        284      0.893      0.735      0.825      0.513
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 81, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

101 epochs completed in 1.329 hours.
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640/weights/last.pt, 5.5MB
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640/weights/best.pt, 5.5MB

Validating /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640/weights/best.pt...
Ultralytics 8.3.106 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLO11n summary (fused): 100 layers, 2,583,517 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:06<00:00,  1.47it/s]

                   all        278        284      0.853      0.811      0.866      0.553
               Apoidea         10         10      0.965        0.6      0.655      0.412
             Arachnida         15         15      0.702      0.787      0.874       0.48
            Brachycera         16         16      0.891      0.875       0.93      0.649
            Coleoptera         51         51      0.839      0.961      0.979      0.712
            Formicidae         67         73      0.925       0.85      0.935       0.64
            Nematocera         95         95       0.91      0.905      0.956       0.57
            Syraphidae         24         24      0.737      0.701      0.731      0.405
Speed: 0.3ms preprocess, 2.8ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to /content/drive/MyDrive/YOLOv11_Results/reindexed_dataset_run_640/train_yolo11n_reindexed_640
🔍 Evaluating on validation set...

  0%|          | 0/278 [00:00<?, ?it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1576697.jpg: 640x640 1 Formicidae, 8.5ms
Speed: 3.2ms preprocess, 8.5ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

  0%|          | 1/278 [00:00<02:31,  1.83it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1174454.jpg: 544x640 1 Brachycera, 52.7ms
Speed: 4.4ms preprocess, 52.7ms inference, 1.3ms postprocess per image at shape (1, 3, 544, 640)

  1%|          | 2/278 [00:01<02:25,  1.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802958.jpg: 640x640 1 Coleoptera, 9.8ms
Speed: 3.8ms preprocess, 9.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

  1%|          | 3/278 [00:01<03:05,  1.48it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1892601.jpg: 640x640 1 Formicidae, 9.3ms
Speed: 3.7ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  1%|▏         | 4/278 [00:02<03:23,  1.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1035967.jpg: 640x640 1 Formicidae, 1 Syraphidae, 9.0ms
Speed: 4.1ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  2%|▏         | 5/278 [00:03<02:49,  1.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869664.jpg: 640x640 2 Coleopteras, 11.2ms
Speed: 4.0ms preprocess, 11.2ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

  2%|▏         | 6/278 [00:03<02:29,  1.82it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1658656.jpg: 640x640 1 Nematocera, 9.4ms
Speed: 3.3ms preprocess, 9.4ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

  3%|▎         | 7/278 [00:03<02:11,  2.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1883122.jpg: 640x640 1 Formicidae, 9.2ms
Speed: 3.3ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  3%|▎         | 8/278 [00:04<02:00,  2.25it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650228.jpg: 640x640 1 Nematocera, 9.3ms
Speed: 3.6ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  3%|▎         | 9/278 [00:04<01:54,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_499672.jpg: 480x640 1 Syraphidae, 45.0ms
Speed: 3.0ms preprocess, 45.0ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

  4%|▎         | 10/278 [00:05<01:58,  2.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1739113.jpg: 640x640 3 Coleopteras, 9.9ms
Speed: 3.2ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  4%|▍         | 11/278 [00:05<01:50,  2.41it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626638.jpg: 640x640 1 Formicidae, 22.6ms
Speed: 6.2ms preprocess, 22.6ms inference, 7.9ms postprocess per image at shape (1, 3, 640, 640)

  4%|▍         | 12/278 [00:05<01:52,  2.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1680229.jpg: 640x640 1 Nematocera, 14.9ms
Speed: 4.6ms preprocess, 14.9ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

  5%|▍         | 13/278 [00:06<01:51,  2.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542164.jpg: 448x640 1 Arachnida, 70.1ms
Speed: 4.5ms preprocess, 70.1ms inference, 1.9ms postprocess per image at shape (1, 3, 448, 640)

  5%|▌         | 14/278 [00:06<02:00,  2.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1705644.jpg: 640x640 1 Nematocera, 13.9ms
Speed: 6.0ms preprocess, 13.9ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

  5%|▌         | 15/278 [00:07<02:13,  1.97it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703727.jpg: 480x640 1 Brachycera, 19.6ms
Speed: 4.4ms preprocess, 19.6ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

  6%|▌         | 16/278 [00:08<02:11,  1.99it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1679968.jpg: 640x640 1 Formicidae, 10.0ms
Speed: 3.3ms preprocess, 10.0ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

  6%|▌         | 17/278 [00:08<01:56,  2.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1199210.jpg: 512x640 (no detections), 51.8ms
Speed: 3.1ms preprocess, 51.8ms inference, 0.6ms postprocess per image at shape (1, 3, 512, 640)

  6%|▋         | 18/278 [00:08<02:03,  2.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1880449.jpg: 512x640 2 Formicidaes, 9.2ms
Speed: 3.2ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

  7%|▋         | 19/278 [00:09<02:18,  1.87it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1720000.jpg: 640x640 1 Brachycera, 1 Nematocera, 10.3ms
Speed: 3.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

  7%|▋         | 20/278 [00:09<02:04,  2.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1889657.jpg: 640x640 1 Formicidae, 9.0ms
Speed: 3.2ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  8%|▊         | 21/278 [00:10<01:53,  2.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541911.jpg: 640x640 (no detections), 9.1ms
Speed: 3.8ms preprocess, 9.1ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)

  8%|▊         | 22/278 [00:10<01:52,  2.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661407.jpg: 640x640 1 Nematocera, 13.1ms
Speed: 5.0ms preprocess, 13.1ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

  8%|▊         | 23/278 [00:11<01:50,  2.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862511.jpg: 640x640 1 Coleoptera, 9.6ms
Speed: 3.2ms preprocess, 9.6ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

  9%|▊         | 24/278 [00:11<01:48,  2.33it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1032411.jpg: 640x640 1 Formicidae, 1 Nematocera, 9.0ms
Speed: 3.5ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  9%|▉         | 25/278 [00:11<01:47,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869258.jpg: 640x640 2 Coleopteras, 9.4ms
Speed: 3.2ms preprocess, 9.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

  9%|▉         | 26/278 [00:12<01:45,  2.40it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803945.jpg: 640x640 1 Coleoptera, 9.7ms
Speed: 3.5ms preprocess, 9.7ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 10%|▉         | 27/278 [00:12<01:45,  2.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214502.jpg: 640x640 1 Coleoptera, 10.1ms
Speed: 3.2ms preprocess, 10.1ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 10%|█         | 28/278 [00:13<01:33,  2.66it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1909134.jpg: 640x640 1 Nematocera, 9.1ms
Speed: 3.4ms preprocess, 9.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 10%|█         | 29/278 [00:13<01:32,  2.68it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_931985.jpg: 640x640 1 Nematocera, 9.3ms
Speed: 3.3ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 11%|█         | 30/278 [00:13<01:29,  2.76it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886378.jpg: 640x640 1 Formicidae, 14.8ms
Speed: 3.4ms preprocess, 14.8ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

 11%|█         | 31/278 [00:14<01:37,  2.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1719649.jpg: 640x640 1 Nematocera, 9.0ms
Speed: 3.5ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 12%|█▏        | 32/278 [00:14<01:34,  2.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1803987.jpg: 640x640 1 Coleoptera, 10.9ms
Speed: 3.6ms preprocess, 10.9ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 12%|█▏        | 33/278 [00:14<01:32,  2.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1760513.jpg: 640x640 1 Formicidae, 9.9ms
Speed: 4.3ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 12%|█▏        | 34/278 [00:15<01:36,  2.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1611112.jpg: 640x640 1 Formicidae, 10.2ms
Speed: 3.7ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 13%|█▎        | 35/278 [00:15<01:38,  2.46it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802908.jpg: 640x640 1 Coleoptera, 12.9ms
Speed: 5.0ms preprocess, 12.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 13%|█▎        | 36/278 [00:16<01:42,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1540578.jpg: 640x640 1 Formicidae, 9.1ms
Speed: 3.2ms preprocess, 9.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 13%|█▎        | 37/278 [00:16<01:36,  2.51it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1701561.jpg: 640x640 1 Brachycera, 1 Syraphidae, 9.0ms
Speed: 3.5ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 14%|█▎        | 38/278 [00:17<01:46,  2.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1884094.jpg: 640x640 1 Formicidae, 9.8ms
Speed: 3.3ms preprocess, 9.8ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 14%|█▍        | 39/278 [00:17<01:38,  2.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1831577.jpg: 640x640 1 Formicidae, 1 Nematocera, 9.2ms
Speed: 3.5ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 14%|█▍        | 40/278 [00:17<01:41,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1537477.jpg: 640x640 1 Formicidae, 13.9ms
Speed: 6.2ms preprocess, 13.9ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)

 15%|█▍        | 41/278 [00:18<01:41,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541858.jpg: 640x640 1 Nematocera, 11.2ms
Speed: 5.3ms preprocess, 11.2ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 15%|█▌        | 42/278 [00:18<01:46,  2.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2001820.jpg: 640x640 2 Nematoceras, 21.5ms
Speed: 9.9ms preprocess, 21.5ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

 15%|█▌        | 43/278 [00:19<01:42,  2.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661488.jpg: 640x640 1 Nematocera, 12.0ms
Speed: 5.2ms preprocess, 12.0ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

 16%|█▌        | 44/278 [00:19<01:38,  2.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1693286.jpg: 640x640 1 Brachycera, 1 Syraphidae, 16.0ms
Speed: 5.5ms preprocess, 16.0ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

 16%|█▌        | 45/278 [00:20<01:33,  2.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_758932.jpg: 640x640 1 Nematocera, 16.0ms
Speed: 5.2ms preprocess, 16.0ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

 17%|█▋        | 46/278 [00:20<01:36,  2.40it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893193.jpg: 640x640 1 Formicidae, 9.5ms
Speed: 3.2ms preprocess, 9.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 17%|█▋        | 47/278 [00:20<01:33,  2.47it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893214.jpg: 640x640 1 Formicidae, 9.2ms
Speed: 3.5ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 17%|█▋        | 48/278 [00:21<01:34,  2.44it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1560917.jpg: 512x640 1 Apoidea, 9.6ms
Speed: 3.0ms preprocess, 9.6ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

 18%|█▊        | 49/278 [00:21<01:38,  2.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626454.jpg: 640x640 2 Formicidaes, 10.1ms
Speed: 3.4ms preprocess, 10.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 18%|█▊        | 50/278 [00:22<01:47,  2.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1208580.jpg: 640x640 1 Nematocera, 10.7ms
Speed: 4.7ms preprocess, 10.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 18%|█▊        | 51/278 [00:22<01:50,  2.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869228.jpg: 640x640 1 Coleoptera, 1 Nematocera, 9.3ms
Speed: 3.5ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 19%|█▊        | 52/278 [00:23<01:48,  2.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_405031.jpg: 480x640 1 Syraphidae, 9.8ms
Speed: 2.9ms preprocess, 9.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

 19%|█▉        | 53/278 [00:23<01:51,  2.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1589547.jpg: 640x640 1 Nematocera, 11.4ms
Speed: 3.6ms preprocess, 11.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 19%|█▉        | 54/278 [00:24<01:43,  2.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1607684.jpg: 640x640 1 Formicidae, 8.9ms
Speed: 3.3ms preprocess, 8.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 20%|█▉        | 55/278 [00:24<01:36,  2.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1893434.jpg: 640x640 1 Formicidae, 9.0ms
Speed: 3.7ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 20%|██        | 56/278 [00:25<01:48,  2.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1626230.jpg: 640x640 2 Formicidaes, 9.4ms
Speed: 3.5ms preprocess, 9.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 21%|██        | 57/278 [00:25<01:42,  2.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1544074.jpg: 512x640 1 Syraphidae, 10.6ms
Speed: 3.0ms preprocess, 10.6ms inference, 1.7ms postprocess per image at shape (1, 3, 512, 640)

 21%|██        | 58/278 [00:26<01:42,  2.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680031.jpg: 640x640 1 Formicidae, 9.9ms
Speed: 3.3ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 21%|██        | 59/278 [00:26<01:33,  2.33it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_488523.jpg: 640x640 1 Arachnida, 1 Coleoptera, 1 Nematocera, 9.0ms
Speed: 3.3ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 22%|██▏       | 60/278 [00:26<01:29,  2.43it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_931996.jpg: 640x640 1 Nematocera, 9.1ms
Speed: 3.2ms preprocess, 9.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 22%|██▏       | 61/278 [00:27<01:25,  2.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_14144.jpg: 384x640 1 Syraphidae, 45.5ms
Speed: 2.6ms preprocess, 45.5ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

 22%|██▏       | 62/278 [00:27<01:38,  2.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1558288.jpg: 640x640 1 Coleoptera, 1 Formicidae, 10.1ms
Speed: 4.3ms preprocess, 10.1ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 23%|██▎       | 63/278 [00:28<01:31,  2.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/991_1813221.jpg: 512x640 (no detections), 9.9ms
Speed: 3.3ms preprocess, 9.9ms inference, 0.6ms postprocess per image at shape (1, 3, 512, 640)

 23%|██▎       | 64/278 [00:28<01:35,  2.25it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1885403.jpg: 480x640 1 Formicidae, 10.0ms
Speed: 2.9ms preprocess, 10.0ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

 23%|██▎       | 65/278 [00:29<01:34,  2.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_2001915.jpg: 640x640 1 Formicidae, 2 Nematoceras, 10.2ms
Speed: 3.5ms preprocess, 10.2ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 24%|██▎       | 66/278 [00:29<01:27,  2.41it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/859_1832273.jpg: 640x640 1 Formicidae, 9.2ms
Speed: 4.6ms preprocess, 9.2ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 24%|██▍       | 67/278 [00:29<01:23,  2.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943955.jpg: 640x640 1 Coleoptera, 16.0ms
Speed: 5.8ms preprocess, 16.0ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)

 24%|██▍       | 68/278 [00:30<01:24,  2.50it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1705250.jpg: 640x640 1 Brachycera, 16.2ms
Speed: 5.6ms preprocess, 16.2ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 25%|██▍       | 69/278 [00:30<01:24,  2.47it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1543606.jpg: 640x640 1 Brachycera, 1 Nematocera, 11.9ms
Speed: 6.9ms preprocess, 11.9ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

 25%|██▌       | 70/278 [00:31<01:25,  2.44it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1583461.jpg: 640x640 1 Nematocera, 17.2ms
Speed: 5.6ms preprocess, 17.2ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

 26%|██▌       | 71/278 [00:31<01:40,  2.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661404.jpg: 640x640 1 Nematocera, 11.7ms
Speed: 5.1ms preprocess, 11.7ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

 26%|██▌       | 72/278 [00:32<01:33,  2.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1590245.jpg: 640x640 1 Nematocera, 12.8ms
Speed: 5.1ms preprocess, 12.8ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

 26%|██▋       | 73/278 [00:32<01:26,  2.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214640.jpg: 512x640 1 Coleoptera, 9.7ms
Speed: 3.0ms preprocess, 9.7ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

 27%|██▋       | 74/278 [00:33<01:40,  2.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1539172.jpg: 640x640 1 Formicidae, 10.3ms
Speed: 3.5ms preprocess, 10.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 27%|██▋       | 75/278 [00:33<01:31,  2.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1760492.jpg: 640x640 1 Formicidae, 9.9ms
Speed: 3.7ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 27%|██▋       | 76/278 [00:33<01:26,  2.34it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/11_364929.jpg: 640x640 1 Arachnida, 9.9ms
Speed: 3.4ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 28%|██▊       | 77/278 [00:34<01:22,  2.45it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_499671.jpg: 512x640 (no detections), 9.8ms
Speed: 3.0ms preprocess, 9.8ms inference, 0.6ms postprocess per image at shape (1, 3, 512, 640)

 28%|██▊       | 78/278 [00:34<01:33,  2.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_310900.jpg: 512x640 1 Syraphidae, 10.3ms
Speed: 3.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 512, 640)

 28%|██▊       | 79/278 [00:35<01:28,  2.24it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1859767.jpg: 640x640 2 Brachyceras, 1 Coleoptera, 1 Nematocera, 10.5ms
Speed: 3.7ms preprocess, 10.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 29%|██▉       | 80/278 [00:35<01:28,  2.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1263711.jpg: 480x640 1 Nematocera, 9.7ms
Speed: 3.3ms preprocess, 9.7ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

 29%|██▉       | 81/278 [00:35<01:24,  2.33it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1730099.jpg: 640x640 1 Nematocera, 10.5ms
Speed: 3.5ms preprocess, 10.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 29%|██▉       | 82/278 [00:36<01:20,  2.43it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214505.jpg: 640x640 1 Coleoptera, 11.3ms
Speed: 3.7ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 30%|██▉       | 83/278 [00:36<01:16,  2.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_983481.jpg: 512x640 1 Apoidea, 1 Coleoptera, 9.9ms
Speed: 3.1ms preprocess, 9.9ms inference, 1.2ms postprocess per image at shape (1, 3, 512, 640)

 30%|███       | 84/278 [00:37<01:20,  2.40it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1886365.jpg: 640x640 1 Formicidae, 9.7ms
Speed: 3.4ms preprocess, 9.7ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 31%|███       | 85/278 [00:37<01:15,  2.56it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1129307.jpg: 640x640 1 Nematocera, 12.0ms
Speed: 5.4ms preprocess, 12.0ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 31%|███       | 86/278 [00:37<01:15,  2.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1304800.jpg: 544x640 1 Coleoptera, 9.7ms
Speed: 3.1ms preprocess, 9.7ms inference, 1.4ms postprocess per image at shape (1, 3, 544, 640)

 31%|███▏      | 87/278 [00:38<01:23,  2.28it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1539168.jpg: 640x640 1 Formicidae, 20.9ms
Speed: 6.8ms preprocess, 20.9ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 32%|███▏      | 88/278 [00:38<01:18,  2.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1892602.jpg: 640x640 1 Formicidae, 9.5ms
Speed: 3.4ms preprocess, 9.5ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

 32%|███▏      | 89/278 [00:39<01:17,  2.45it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1943961.jpg: 640x640 1 Coleoptera, 9.5ms
Speed: 3.6ms preprocess, 9.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 32%|███▏      | 90/278 [00:39<01:15,  2.48it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541881.jpg: 640x640 1 Nematocera, 10.2ms
Speed: 3.7ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 33%|███▎      | 91/278 [00:40<01:17,  2.40it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1793456.jpg: 640x640 1 Nematocera, 9.4ms
Speed: 4.2ms preprocess, 9.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 33%|███▎      | 92/278 [00:40<01:14,  2.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869227.jpg: 640x640 1 Coleoptera, 1 Nematocera, 15.6ms
Speed: 5.0ms preprocess, 15.6ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 33%|███▎      | 93/278 [00:40<01:10,  2.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1862547.jpg: 640x640 2 Coleopteras, 9.3ms
Speed: 3.2ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 34%|███▍      | 94/278 [00:41<01:10,  2.60it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680046.jpg: 512x640 1 Formicidae, 10.0ms
Speed: 3.3ms preprocess, 10.0ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

 34%|███▍      | 95/278 [00:41<01:12,  2.51it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1756184.jpg: 640x640 1 Arachnida, 1 Formicidae, 11.1ms
Speed: 3.9ms preprocess, 11.1ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 35%|███▍      | 96/278 [00:41<01:09,  2.62it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/10_376520.jpg: 384x640 1 Syraphidae, 11.3ms
Speed: 2.5ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

 35%|███▍      | 97/278 [00:42<01:15,  2.38it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1558357.jpg: 640x640 1 Formicidae, 10.0ms
Speed: 3.4ms preprocess, 10.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 35%|███▌      | 98/278 [00:42<01:10,  2.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1596975.jpg: 640x640 1 Nematocera, 18.8ms
Speed: 9.7ms preprocess, 18.8ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

 36%|███▌      | 99/278 [00:43<01:10,  2.53it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1296685.jpg: 640x640 1 Nematocera, 12.5ms
Speed: 5.7ms preprocess, 12.5ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 36%|███▌      | 100/278 [00:43<01:11,  2.50it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1542166.jpg: 640x640 1 Formicidae, 1 Nematocera, 14.2ms
Speed: 10.1ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 640)

 36%|███▋      | 101/278 [00:43<01:08,  2.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_503051.jpg: 384x640 1 Syraphidae, 11.9ms
Speed: 3.6ms preprocess, 11.9ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)

 37%|███▋      | 102/278 [00:44<01:19,  2.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869236.jpg: 640x640 1 Coleoptera, 26.1ms
Speed: 7.3ms preprocess, 26.1ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)

 37%|███▋      | 103/278 [00:45<02:09,  1.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_935393.jpg: 640x640 1 Nematocera, 9.2ms
Speed: 3.4ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 37%|███▋      | 104/278 [00:46<01:47,  1.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1739198.jpg: 640x640 3 Coleopteras, 9.2ms
Speed: 4.6ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 38%|███▊      | 105/278 [00:46<01:33,  1.85it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/34_977656.jpg: 640x640 1 Arachnida, 1 Coleoptera, 9.2ms
Speed: 4.4ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 38%|███▊      | 106/278 [00:47<01:25,  2.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661365.jpg: 640x640 1 Nematocera, 9.6ms
Speed: 4.2ms preprocess, 9.6ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 38%|███▊      | 107/278 [00:47<01:28,  1.94it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_710011.jpg: 384x640 1 Formicidae, 1 Nematocera, 1 Syraphidae, 9.7ms
Speed: 2.6ms preprocess, 9.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

 39%|███▉      | 108/278 [00:48<01:36,  1.76it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1578215.jpg: 640x640 1 Nematocera, 10.4ms
Speed: 3.5ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 39%|███▉      | 109/278 [00:48<01:26,  1.95it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1202777.jpg: 640x640 2 Nematoceras, 14.8ms
Speed: 3.4ms preprocess, 14.8ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)

 40%|███▉      | 110/278 [00:49<01:22,  2.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680041.jpg: 512x640 1 Formicidae, 10.2ms
Speed: 3.0ms preprocess, 10.2ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

 40%|███▉      | 111/278 [00:49<01:20,  2.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870243.jpg: 640x640 1 Coleoptera, 9.9ms
Speed: 3.4ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 40%|████      | 112/278 [00:49<01:13,  2.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1909301.jpg: 480x640 1 Apoidea, 10.2ms
Speed: 3.0ms preprocess, 10.2ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

 41%|████      | 113/278 [00:50<01:19,  2.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1726947.jpg: 640x640 1 Nematocera, 10.1ms
Speed: 3.7ms preprocess, 10.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 41%|████      | 114/278 [00:50<01:11,  2.28it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_495546.jpg: 640x640 1 Arachnida, 1 Nematocera, 11.3ms
Speed: 3.4ms preprocess, 11.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 41%|████▏     | 115/278 [00:51<01:08,  2.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_650235.jpg: 640x640 1 Nematocera, 9.3ms
Speed: 3.4ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 42%|████▏     | 116/278 [00:51<01:05,  2.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1719192.jpg: 640x640 1 Nematocera, 9.4ms
Speed: 4.1ms preprocess, 9.4ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 42%|████▏     | 117/278 [00:51<01:03,  2.54it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1582009.jpg: 640x640 1 Nematocera, 9.1ms
Speed: 3.4ms preprocess, 9.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 42%|████▏     | 118/278 [00:52<01:00,  2.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1870212.jpg: 640x640 1 Coleoptera, 9.1ms
Speed: 3.3ms preprocess, 9.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 43%|████▎     | 119/278 [00:52<00:59,  2.66it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1680043.jpg: 512x640 1 Formicidae, 10.3ms
Speed: 3.8ms preprocess, 10.3ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

 43%|████▎     | 120/278 [00:53<01:01,  2.57it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1887570.jpg: 640x640 1 Formicidae, 11.0ms
Speed: 3.2ms preprocess, 11.0ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 44%|████▎     | 121/278 [00:53<01:03,  2.47it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1847163.jpg: 640x640 1 Formicidae, 9.2ms
Speed: 3.4ms preprocess, 9.2ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 44%|████▍     | 122/278 [00:53<01:00,  2.56it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1650775.jpg: 512x640 1 Apoidea, 10.1ms
Speed: 3.1ms preprocess, 10.1ms inference, 1.3ms postprocess per image at shape (1, 3, 512, 640)

 44%|████▍     | 123/278 [00:54<01:01,  2.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1565506.jpg: 640x640 1 Formicidae, 10.1ms
Speed: 4.3ms preprocess, 10.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 45%|████▍     | 124/278 [00:55<01:17,  1.98it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_661377.jpg: 640x640 1 Nematocera, 13.3ms
Speed: 4.5ms preprocess, 13.3ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

 45%|████▍     | 125/278 [00:55<01:11,  2.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214590.jpg: 640x640 1 Coleoptera, 11.3ms
Speed: 5.6ms preprocess, 11.3ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 45%|████▌     | 126/278 [00:55<01:05,  2.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1225144.jpg: 544x640 1 Brachycera, 12.5ms
Speed: 5.0ms preprocess, 12.5ms inference, 1.6ms postprocess per image at shape (1, 3, 544, 640)

 46%|████▌     | 127/278 [00:56<01:05,  2.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/925_1570493.jpg: 640x640 1 Nematocera, 13.3ms
Speed: 7.1ms preprocess, 13.3ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

 46%|████▌     | 128/278 [00:56<01:01,  2.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1742462.jpg: 640x640 1 Arachnida, 1 Nematocera, 1 Syraphidae, 16.4ms
Speed: 5.5ms preprocess, 16.4ms inference, 3.9ms postprocess per image at shape (1, 3, 640, 640)

 46%|████▋     | 129/278 [00:57<01:03,  2.36it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1869201.jpg: 640x640 1 Coleoptera, 17.1ms
Speed: 5.0ms preprocess, 17.1ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

 47%|████▋     | 130/278 [00:57<00:59,  2.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1804174.jpg: 640x640 1 Coleoptera, 9.3ms
Speed: 3.4ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 47%|████▋     | 131/278 [00:57<00:57,  2.58it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1947655.jpg: 640x640 1 Formicidae, 9.0ms
Speed: 3.4ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 47%|████▋     | 132/278 [00:58<00:55,  2.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1214629.jpg: 640x640 3 Coleopteras, 9.3ms
Speed: 3.4ms preprocess, 9.3ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 48%|████▊     | 133/278 [00:58<00:55,  2.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1354_1883119.jpg: 640x640 1 Formicidae, 9.7ms
Speed: 3.5ms preprocess, 9.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 48%|████▊     | 134/278 [00:58<00:54,  2.64it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1550514.jpg: 640x640 1 Arachnida, 1 Formicidae, 10.9ms
Speed: 3.8ms preprocess, 10.9ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)

 49%|████▊     | 135/278 [00:59<00:55,  2.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_541854.jpg: 640x640 1 Nematocera, 9.9ms
Speed: 4.0ms preprocess, 9.9ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 49%|████▉     | 136/278 [00:59<00:56,  2.50it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802914.jpg: 640x640 1 Coleoptera, 9.4ms
Speed: 4.5ms preprocess, 9.4ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

 49%|████▉     | 137/278 [01:01<02:00,  1.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1690164.jpg: 480x640 1 Formicidae, 9.8ms
Speed: 2.9ms preprocess, 9.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

 50%|████▉     | 138/278 [01:02<01:45,  1.33it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_934398.jpg: 640x640 1 Nematocera, 9.9ms
Speed: 3.4ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 50%|█████     | 139/278 [01:02<01:25,  1.62it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1263867.jpg: 480x640 1 Nematocera, 10.5ms
Speed: 2.9ms preprocess, 10.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

 50%|█████     | 140/278 [01:02<01:17,  1.78it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707531.jpg: 640x640 1 Nematocera, 9.9ms
Speed: 3.3ms preprocess, 9.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

 51%|█████     | 141/278 [01:03<01:32,  1.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/827_1703711.jpg: 480x640 1 Brachycera, 10.1ms
Speed: 3.0ms preprocess, 10.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

 51%|█████     | 142/278 [01:04<01:22,  1.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/265_1035966.jpg: 640x640 1 Syraphidae, 9.9ms
Speed: 3.4ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 51%|█████▏    | 143/278 [01:04<01:11,  1.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1585491.jpg: 640x640 1 Nematocera, 9.2ms
Speed: 3.3ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 52%|█████▏    | 144/278 [01:04<01:03,  2.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/562_1707001.jpg: 640x640 1 Nematocera, 9.1ms
Speed: 3.4ms preprocess, 9.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 52%|█████▏    | 145/278 [01:05<00:57,  2.32it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_70781.jpg: 384x640 1 Syraphidae, 10.9ms
Speed: 2.8ms preprocess, 10.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

 53%|█████▎    | 146/278 [01:05<00:58,  2.26it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/1_15077.jpg: 384x640 1 Syraphidae, 9.2ms
Speed: 2.7ms preprocess, 9.2ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

 53%|█████▎    | 147/278 [01:06<00:59,  2.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images/793_1802938.jpg: 640x640 1 Coleoptera, 9.9ms
Speed: 3.5ms preprocess, 9.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)

 53%|█████▎    | 148/278 [01:06<00:54,  2.38it/s]

In [ ]:
import os
import shutil
import random
from sklearn.model_selection import train_test_split
import pandas as pd

# ✅ Paths
background_images_dir = "/content/drive/MyDrive/no-tags-3"  # Folder with 216 background-only .jpg images
existing_train_dir = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/train/images"
existing_val_dir = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_and_split/val/images"

# ✅ New dataset base path
new_dataset_base = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background"
new_train_img_dir = os.path.join(new_dataset_base, "train/images")
new_train_lbl_dir = os.path.join(new_dataset_base, "train/labels")
new_val_img_dir = os.path.join(new_dataset_base, "val/images")
new_val_lbl_dir = os.path.join(new_dataset_base, "val/labels")

os.makedirs(new_train_img_dir, exist_ok=True)
os.makedirs(new_train_lbl_dir, exist_ok=True)
os.makedirs(new_val_img_dir, exist_ok=True)
os.makedirs(new_val_lbl_dir, exist_ok=True)

# ✅ Copy original train/val images and labels to new folders
def copy_dataset(src_img_dir, src_lbl_dir, dst_img_dir, dst_lbl_dir):
    for f in os.listdir(src_img_dir):
        if f.endswith(".jpg"):
            shutil.copy(os.path.join(src_img_dir, f), os.path.join(dst_img_dir, f))
            label_file = f.replace(".jpg", ".txt")
            lbl_src = os.path.join(src_lbl_dir, label_file)
            if os.path.exists(lbl_src):
                shutil.copy(lbl_src, os.path.join(dst_lbl_dir, label_file))

copy_dataset(existing_train_dir, existing_train_dir.replace("images", "labels"), new_train_img_dir, new_train_lbl_dir)
copy_dataset(existing_val_dir, existing_val_dir.replace("images", "labels"), new_val_img_dir, new_val_lbl_dir)

# ✅ Split background images into 80:20
bg_images = [f for f in os.listdir(background_images_dir) if f.endswith(".jpg")]
train_bg, val_bg = train_test_split(bg_images, test_size=0.2, random_state=42)

# ✅ Copy background images (without labels)
for f in train_bg:
    shutil.copy(os.path.join(background_images_dir, f), os.path.join(new_train_img_dir, f))
for f in val_bg:
    shutil.copy(os.path.join(background_images_dir, f), os.path.join(new_val_img_dir, f))

# ✅ Summary
summary = {
    "Total Background Images": len(bg_images),
    "Background in Train Set": len(train_bg),
    "Background in Val Set": len(val_bg),
    "Total Train Images After Merge": len(os.listdir(new_train_img_dir)),
    "Total Val Images After Merge": len(os.listdir(new_val_img_dir)),
}

df_summary = pd.DataFrame([summary])
df_summary

,Total Background Images,Background in Train Set,Background in Val Set,Total Train Images After Merge,Total Val Images After Merge
0,216,172,44,1282,322

In [ ]:
!pip install ultralytics
import os
import cv2
import numpy as np
from tqdm import tqdm
from ultralytics import YOLO
from sklearn.metrics import precision_score, recall_score, f1_score

# ✅ Paths
yaml_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/config.yaml"
model_path = "models/yolo11n.pt"
output_dir = "/content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000"

# ✅ Train YOLOv11n model (no resume)
model = YOLO(model_path)
model.train(
    data=yaml_path,
    epochs=300,
    imgsz=1000,
    patience=20,
    save=True,
    project=output_dir,
    name="train_yolo11n_reindexed_with_background_1000"
)

# ✅ Validation and Evaluation
val_images_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images"
val_labels_path = "/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/labels"

fp_dir = os.path.join(output_dir, "false_positives")
fn_dir = os.path.join(output_dir, "false_negatives")
mc_dir = os.path.join(output_dir, "misclassified")
os.makedirs(fp_dir, exist_ok=True)
os.makedirs(fn_dir, exist_ok=True)
os.makedirs(mc_dir, exist_ok=True)

class_names = {
    0: "Apoidea", 1: "Arachnida", 2: "Brachycera", 3: "Coleoptera",
    4: "Formicidae", 5: "Nematocera", 6: "Syraphidae"
}

def compute_iou(box1, box2):
    xA, yA = max(box1[0], box2[0]), max(box1[1], box2[1])
    xB, yB = min(box1[2], box2[2]), min(box1[3], box2[3])
    inter = max(0, xB - xA) * max(0, yB - yA)
    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])
    return inter / (area1 + area2 - inter + 1e-6)

print("🔍 Evaluating on validation set...")
y_true, y_pred = [], []

for img_name in tqdm(os.listdir(val_images_path)):
    if not img_name.endswith(".jpg"):
        continue

    img_path = os.path.join(val_images_path, img_name)
    label_path = os.path.join(val_labels_path, img_name.replace(".jpg", ".txt"))
    image = cv2.imread(img_path)
    height, width = image.shape[:2]

    results = model(img_path, conf=0.25, iou=0.7)[0]
    pred_boxes = results.boxes.xyxy.cpu().numpy()
    pred_classes = results.boxes.cls.cpu().numpy()

    gt_boxes, gt_classes = [], []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                x1 = int((x - w/2) * width)
                y1 = int((y - h/2) * height)
                x2 = int((x + w/2) * width)
                y2 = int((y + h/2) * height)
                gt_boxes.append([x1, y1, x2, y2])
                gt_classes.append(int(cls))

    matched_pred = set()
    matched_gt = set()

    for i, pbox in enumerate(pred_boxes):
        px1, py1, px2, py2 = map(int, pbox[:4])
        pred_cls = int(pred_classes[i])
        for j, gtbox in enumerate(gt_boxes):
            iou = compute_iou(pbox[:4], gtbox)
            if iou > 0.3:
                matched_pred.add(i)
                matched_gt.add(j)
                if pred_cls != gt_classes[j]:
                    img_copy = image.copy()
                    gx1, gy1, gx2, gy2 = gtbox
                    cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (0, 255, 0), 2)
                    cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
                    cv2.putText(img_copy, f"Pred: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
                    cv2.putText(img_copy, f"GT: {class_names.get(gt_classes[j])}", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)
                    cv2.imwrite(os.path.join(mc_dir, f"mc_{img_name}"), img_copy)
                break

    for i, pbox in enumerate(pred_boxes):
        if i not in matched_pred:
            y_true.append(0)
            y_pred.append(1)
            px1, py1, px2, py2 = map(int, pbox[:4])
            pred_cls = int(pred_classes[i])
            img_copy = image.copy()
            cv2.rectangle(img_copy, (px1, py1), (px2, py2), (0, 0, 255), 2)
            cv2.putText(img_copy, f"FP: {class_names.get(pred_cls)}", (px1, py1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
            cv2.imwrite(os.path.join(fp_dir, f"fp_{img_name}"), img_copy)

    for j, gtbox in enumerate(gt_boxes):
        if j not in matched_gt:
            y_true.append(1)
            y_pred.append(0)
            gx1, gy1, gx2, gy2 = gtbox
            img_copy = image.copy()
            cv2.rectangle(img_copy, (gx1, gy1), (gx2, gy2), (255, 0, 0), 2)
            cv2.putText(img_copy, "FN", (gx1, gy1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)
            cv2.imwrite(os.path.join(fn_dir, f"fn_{img_name}"), img_copy)

# ✅ Summary metrics
precision = precision_score(y_true, y_pred) * 100
recall = recall_score(y_true, y_pred) * 100
f1 = f1_score(y_true, y_pred) * 100

print("\n✅ Evaluation Summary:")
print(f"Precision: {precision:.2f}%")
print(f"Recall:    {recall:.2f}%")
print(f"F1 Score:  {f1:.2f}%")
print(f"→ FP saved to: {fp_dir}")
print(f"→ FN saved to: {fn_dir}")
print(f"→ MC saved to: {mc_dir}")

Collecting ultralytics
  Downloading ultralytics-8.3.106-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy<=2.1.1,>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.14.1)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.2.2)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.13.2)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.14-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->ultralytics) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.1.31)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Downloading ultralytics-8.3.106-py3-none-any.whl (972 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 973.0/973.0 kB 20.3 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.0 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 77.2 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 48.6 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 55.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 6.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 16.5 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.14-py3-none-any.whl (26 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.106 ultralytics-thop-2.0.14
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'models/yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 15.7MB/s]

Ultralytics 8.3.106 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: task=detect, mode=train, model=models/yolo11n.pt, data=/content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/config.yaml, epochs=300, time=None, patience=20, batch=16, imgsz=1000, save=True, save_period=-1, cache=False, device=None, workers=8, project=/content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000, name=train_yolo11n_reindexed_with_background_1000, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...

100%|██████████| 755k/755k [00:00<00:00, 3.24MB/s]

Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    432037  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]
YOLO11n summary: 181 layers, 2,591,205 parameters, 2,591,189 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 15.7MB/s]

AMP: checks passed ✅
WARNING ⚠️ imgsz=[1000] must be multiple of max stride 32, updating to [1024]

train: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/train/labels... 1110 images, 172 backgrounds, 0 corrupt: 100%|██████████| 1282/1282 [00:16<00:00, 78.10it/s]

train: New cache created: /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Scanning /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/labels... 278 images, 44 backgrounds, 0 corrupt: 100%|██████████| 322/322 [00:05<00:00, 62.04it/s]

val: New cache created: /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/labels.cache
Plotting labels to /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/300       6.1G      2.177      8.449      1.806          1       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:11<00:00,  1.08s/it]

                   all        322        284    0.00448      0.827      0.139     0.0627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/300      7.17G      1.611      5.643      1.436          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.17it/s]

                   all        322        284      0.371      0.438      0.367      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/300      7.18G      1.625      4.595      1.463          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.50it/s]

                   all        322        284      0.325      0.368      0.361      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/300       7.2G      1.618      3.858      1.493          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.52it/s]

                   all        322        284      0.494      0.303      0.343      0.171

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/300      7.22G      1.566      3.238      1.475          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.44it/s]

                   all        322        284      0.421      0.482      0.449      0.243

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/300      7.23G      1.508      2.838      1.417          0       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.39it/s]

                   all        322        284      0.523      0.413      0.447      0.248

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/300      7.24G      1.508      2.331      1.429          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.48it/s]

                   all        322        284      0.636      0.525      0.531      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/300      7.26G      1.528      2.257      1.435          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.50it/s]

                   all        322        284      0.638      0.478      0.547      0.286

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/300      7.28G      1.472      1.945      1.418          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.42it/s]

                   all        322        284       0.54      0.404      0.446      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/300      7.29G      1.491       1.93      1.434          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.46it/s]

                   all        322        284      0.456      0.596      0.557      0.326

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/300       7.3G      1.432      1.812        1.4          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.29it/s]

                   all        322        284      0.636      0.592      0.607      0.331

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/300      7.32G       1.42      1.727      1.403          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.22it/s]

                   all        322        284       0.67       0.59      0.615      0.372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/300      7.33G       1.44      1.612      1.415          3       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.604      0.533      0.558      0.323

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/300      7.35G       1.41      1.544      1.382          5       1024: 100%|██████████| 81/81 [01:13<00:00,  1.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.27it/s]

                   all        322        284      0.699       0.56      0.604      0.334

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/300      7.36G      1.413      1.581      1.412          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.808       0.57      0.656      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/300      7.38G      1.397      1.515      1.408          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284      0.685      0.598      0.645      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/300      7.39G      1.407      1.519      1.386          2       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.25it/s]

                   all        322        284      0.769       0.59      0.681      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/300      7.41G      1.351      1.434      1.346          4       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.04it/s]

                   all        322        284      0.747      0.632      0.712      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/300      7.42G      1.379      1.381      1.371          5       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.698      0.667      0.704      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/300      7.44G      1.363      1.378      1.365          5       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.20it/s]

                   all        322        284      0.731      0.663      0.731      0.423

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/300      7.45G      1.349      1.338      1.369          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.16it/s]

                   all        322        284      0.654       0.73      0.745      0.432

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/300      7.47G      1.338      1.279       1.35          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.14it/s]

                   all        322        284       0.84      0.624      0.723      0.419

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/300      7.47G      1.343      1.282       1.35          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.704      0.676      0.713      0.428

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/300       7.5G      1.338      1.258      1.368          2       1024: 100%|██████████| 81/81 [01:13<00:00,  1.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.18it/s]

                   all        322        284      0.722      0.639      0.722      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/300      7.51G      1.321      1.231      1.336          2       1024: 100%|██████████| 81/81 [01:13<00:00,  1.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.29it/s]

                   all        322        284      0.823      0.724      0.777      0.436

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/300      7.53G       1.32      1.228      1.357          4       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.20it/s]

                   all        322        284      0.757      0.671       0.74      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/300      7.54G      1.305      1.152      1.356          3       1024: 100%|██████████| 81/81 [01:13<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.55it/s]

                   all        322        284      0.856      0.584      0.713       0.46

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/300      7.56G      1.285      1.079      1.328          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.46it/s]

                   all        322        284      0.827      0.591      0.743      0.442

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/300      7.57G       1.33      1.172      1.374          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.48it/s]

                   all        322        284      0.785      0.638      0.746       0.45

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/300      7.59G      1.274      1.119      1.342          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.32it/s]

                   all        322        284      0.822      0.658      0.763      0.488

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/300      7.59G      1.236      1.073      1.308          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.28it/s]

                   all        322        284      0.797      0.731      0.805      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/300      7.62G      1.269      1.112      1.327          3       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.41it/s]

                   all        322        284      0.822      0.666      0.764      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/300      7.63G       1.29      1.073      1.344          3       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.19it/s]

                   all        322        284      0.892       0.66      0.805      0.499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/300      7.65G      1.251       1.05      1.301          0       1024: 100%|██████████| 81/81 [01:13<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.13it/s]

                   all        322        284      0.744      0.816      0.836      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/300      7.65G      1.245      1.084      1.308          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.09it/s]

                   all        322        284      0.836      0.721      0.799      0.478

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/300      7.68G      1.297      1.083      1.345          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.33it/s]

                   all        322        284      0.797      0.723       0.79      0.464

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/300      7.69G       1.22       1.01      1.307          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.27it/s]

                   all        322        284      0.768      0.723       0.77       0.48

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/300      7.71G       1.24     0.9896      1.306          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.40it/s]

                   all        322        284      0.888      0.719      0.793      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/300      7.71G      1.252      1.049      1.311          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.31it/s]

                   all        322        284      0.863       0.69      0.765      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/300      7.74G      1.231      1.002      1.311          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.861      0.717      0.822      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/300      7.75G      1.217     0.9702      1.295          2       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.23it/s]

                   all        322        284      0.891       0.74      0.839        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/300      7.77G      1.195     0.9211      1.281          3       1024: 100%|██████████| 81/81 [01:13<00:00,  1.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.26it/s]

                   all        322        284      0.832      0.743      0.785      0.474

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/300      7.77G      1.227     0.9366      1.287          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.30it/s]

                   all        322        284      0.869       0.72      0.795       0.49

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/300       7.8G       1.23     0.9674      1.298          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.13it/s]

                   all        322        284      0.799      0.727      0.798      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/300      7.81G      1.204      0.938      1.271          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.28it/s]

                   all        322        284      0.909       0.72      0.816      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/300      7.83G      1.217     0.9027       1.28          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.14it/s]

                   all        322        284      0.787      0.755        0.8      0.484

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/300      7.83G      1.183     0.9009      1.261          3       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.31it/s]

                   all        322        284      0.867      0.725      0.832      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/300      7.86G      1.188     0.8834      1.262          3       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.47it/s]

                   all        322        284      0.908      0.652      0.786      0.501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/300      7.87G      1.169     0.8973      1.257          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.48it/s]

                   all        322        284      0.872      0.677      0.795      0.464

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/300      7.89G      1.169     0.8822      1.249          5       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.45it/s]

                   all        322        284      0.827      0.743      0.814      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/300      7.89G      1.161     0.8624      1.262          5       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.39it/s]

                   all        322        284      0.866      0.738      0.822      0.499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/300      7.91G      1.138     0.8433      1.246          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.40it/s]

                   all        322        284      0.903      0.728      0.832       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/300      7.93G      1.179     0.8658      1.281          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.40it/s]

                   all        322        284      0.934      0.694      0.797      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/300      7.95G      1.147      0.869      1.248          3       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.51it/s]

                   all        322        284      0.881      0.771       0.83      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/300      7.95G      1.148     0.8332       1.25          5       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.45it/s]

                   all        322        284      0.781       0.76      0.848      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/300      7.97G      1.154     0.8081      1.239          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.38it/s]

                   all        322        284      0.909      0.723      0.833       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/300      7.99G      1.124     0.7802      1.215          2       1024: 100%|██████████| 81/81 [01:18<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.47it/s]

                   all        322        284      0.817      0.719      0.804      0.507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/300         8G      1.155     0.8541      1.258          1       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.35it/s]

                   all        322        284      0.874      0.759      0.829       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/300      8.01G       1.13     0.8146      1.241          3       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.49it/s]

                   all        322        284      0.904      0.768      0.845      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/300      8.03G      1.115     0.8108      1.237          2       1024: 100%|██████████| 81/81 [01:19<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.22it/s]

                   all        322        284       0.88      0.806      0.875      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/300      8.05G      1.122     0.8328      1.236          4       1024: 100%|██████████| 81/81 [01:19<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.20it/s]

                   all        322        284      0.832      0.746      0.832      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/300      8.06G       1.12     0.8251      1.233          3       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.19it/s]

                   all        322        284      0.857      0.716      0.812      0.489

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/300      8.07G      1.154     0.8377      1.252          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.07it/s]

                   all        322        284      0.812      0.744       0.81      0.493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/300      8.09G      1.109     0.7729       1.22          2       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.33it/s]

                   all        322        284      0.916       0.72      0.843      0.519

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/300      8.11G      1.099     0.7763      1.214          1       1024: 100%|██████████| 81/81 [01:18<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.34it/s]

                   all        322        284      0.873      0.776      0.857      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/300      8.12G      1.068     0.7858      1.189          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.36it/s]

                   all        322        284      0.805      0.763      0.838      0.505

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/300      8.13G      1.119     0.7835      1.245          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.28it/s]

                   all        322        284      0.842      0.787      0.859      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/300      8.15G      1.054     0.7538      1.186          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284       0.86      0.719      0.815      0.496

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/300      8.17G      1.083     0.7504        1.2          0       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284      0.924      0.727      0.847      0.515

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/300      8.18G      1.054     0.7397      1.183          1       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.18it/s]

                   all        322        284      0.856      0.748      0.828      0.514

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/300      8.19G      1.101     0.7561      1.212          1       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.23it/s]

                   all        322        284      0.825      0.805       0.87      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/300      8.21G      1.071     0.7748      1.204          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.882      0.804      0.869      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/300      8.23G      1.074     0.7571      1.199          2       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.905      0.742      0.864      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/300      8.24G      1.107     0.7705      1.217          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.15it/s]

                   all        322        284       0.88      0.795      0.872      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/300      8.25G      1.059     0.7917      1.186          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.08it/s]

                   all        322        284      0.907      0.776      0.863      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/300      8.27G      1.057     0.7374      1.178          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.29it/s]

                   all        322        284      0.902       0.75      0.852      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/300      8.29G      1.044     0.7509       1.19          3       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.10it/s]

                   all        322        284      0.812      0.827      0.861      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/300       8.3G      1.072      0.744      1.199          5       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.23it/s]

                   all        322        284       0.83        0.8      0.864      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/300      8.31G      1.051     0.7443      1.184          4       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.829      0.813      0.856      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/300      8.33G      1.047     0.7217      1.178          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.26it/s]

                   all        322        284      0.869      0.775      0.854      0.518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/300      8.35G      1.026     0.6974      1.172          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.848      0.802      0.842      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/300      8.36G      1.033     0.7312       1.17          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.19it/s]

                   all        322        284      0.867      0.826      0.867      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/300      8.37G      1.044      0.734      1.186          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.928      0.731      0.844      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/300      8.39G      1.078     0.7864      1.199          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284      0.859      0.752      0.833      0.521

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/300      8.41G      1.022     0.7122      1.172          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.22it/s]

                   all        322        284      0.915      0.774      0.855      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/300      8.42G      1.005     0.6931      1.159          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.33it/s]

                   all        322        284      0.896      0.741      0.848       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/300      8.43G     0.9982     0.6552      1.158          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.26it/s]

                   all        322        284       0.83      0.834       0.86      0.521

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/300      8.45G      1.015     0.6865      1.166          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.42it/s]

                   all        322        284      0.851      0.819      0.848      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/300      8.47G     0.9872     0.6497      1.139          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284      0.894      0.812      0.858      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/300      8.48G      1.014     0.6898      1.163          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.45it/s]

                   all        322        284       0.85      0.811      0.871      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/300      8.49G     0.9897     0.6711      1.147          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.43it/s]

                   all        322        284      0.837      0.823      0.859      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/300      8.51G      1.016     0.6932      1.158          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.47it/s]

                   all        322        284      0.923      0.752      0.866      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/300      8.53G     0.9957     0.6747      1.148          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.37it/s]

                   all        322        284      0.875      0.802      0.859       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/300      8.54G      1.024     0.6812      1.159          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.49it/s]

                   all        322        284      0.876      0.814      0.881      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/300      8.55G      0.993     0.6812      1.148          1       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.38it/s]

                   all        322        284      0.882      0.823      0.886       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/300      8.57G     0.9822     0.6588      1.145          5       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.02it/s]

                   all        322        284      0.873        0.8       0.87      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/300      8.59G     0.9662     0.6532      1.134          4       1024: 100%|██████████| 81/81 [01:20<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.28it/s]

                   all        322        284      0.937      0.745      0.867      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/300       8.6G     0.9678     0.6355      1.121          0       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.30it/s]

                   all        322        284      0.919      0.793      0.881       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/300      8.61G     0.9645     0.6372      1.131          2       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.28it/s]

                   all        322        284      0.857      0.841      0.888      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/300      8.63G     0.9466     0.6646      1.122          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.29it/s]

                   all        322        284      0.922      0.759       0.85      0.516

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    101/300      8.65G     0.9672     0.6377      1.135          4       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.38it/s]

                   all        322        284      0.856      0.754      0.837      0.519

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    102/300      8.66G     0.9545     0.6796      1.127          4       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.856      0.765      0.828      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    103/300      8.67G     0.9769     0.6632      1.141          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.13it/s]

                   all        322        284      0.846      0.788       0.87      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    104/300      8.69G     0.9888     0.6637      1.154          3       1024: 100%|██████████| 81/81 [01:19<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.22it/s]

                   all        322        284      0.905       0.77      0.886      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    105/300      8.71G     0.9519     0.6521      1.131          4       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.15it/s]

                   all        322        284      0.933      0.811       0.88      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    106/300      8.72G      0.967     0.6543       1.12          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.06it/s]

                   all        322        284      0.889      0.826      0.867      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    107/300      8.72G     0.9597     0.6512      1.121          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.40it/s]

                   all        322        284      0.888      0.829      0.878       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    108/300      8.75G     0.9663     0.6852      1.134          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.33it/s]

                   all        322        284      0.865      0.782      0.857      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    109/300      8.76G     0.9194     0.6126      1.095          0       1024: 100%|██████████| 81/81 [01:19<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.44it/s]

                   all        322        284      0.903      0.771       0.86      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    110/300      8.78G     0.9422     0.6399      1.114          5       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.49it/s]

                   all        322        284      0.908      0.829      0.871      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    111/300      8.79G     0.9162     0.6116      1.099          5       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.13it/s]

                   all        322        284      0.873      0.777      0.844      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    112/300      8.81G     0.9316      0.604      1.097          4       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.42it/s]

                   all        322        284      0.906      0.814      0.872      0.535

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    113/300      8.82G     0.9286     0.6063      1.097          2       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.31it/s]

                   all        322        284      0.903      0.789      0.859      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    114/300      8.84G     0.9297     0.6195      1.123          3       1024: 100%|██████████| 81/81 [01:18<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.32it/s]

                   all        322        284      0.907      0.812      0.873      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    115/300      8.84G     0.9188     0.6337       1.11          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.919      0.718      0.839      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    116/300      8.87G     0.9205     0.5956      1.107          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.34it/s]

                   all        322        284      0.829      0.871      0.873      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    117/300      8.88G     0.8992     0.5915      1.084          6       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.07it/s]

                   all        322        284      0.897      0.806      0.874      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    118/300       8.9G      0.923     0.6241      1.105          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.24it/s]

                   all        322        284      0.907      0.834      0.892      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    119/300       8.9G     0.9075     0.5963      1.106          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.06it/s]

                   all        322        284      0.925      0.808      0.865      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    120/300      8.93G     0.8997     0.5769      1.084          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.12it/s]

                   all        322        284      0.894      0.796      0.876      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    121/300      8.94G     0.9012     0.5997      1.084          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.26it/s]

                   all        322        284      0.904      0.783      0.873      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    122/300      8.96G     0.9055      0.595      1.098          4       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.13it/s]

                   all        322        284      0.807      0.814      0.864      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    123/300      8.96G     0.8739     0.5945      1.076          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.26it/s]

                   all        322        284      0.871      0.822      0.862      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    124/300      8.99G     0.8978     0.6033      1.094          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:11<00:00,  1.02s/it]

                   all        322        284      0.903      0.798       0.88      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    125/300         9G     0.9009     0.6025      1.101          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.12it/s]

                   all        322        284       0.89      0.802       0.86      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    126/300      9.02G     0.8767      0.583      1.084          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.02it/s]

                   all        322        284      0.907        0.8      0.886      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    127/300      9.03G      0.871     0.5611      1.087          5       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.25it/s]

                   all        322        284      0.922      0.798      0.876      0.559

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    128/300      9.04G     0.8916     0.5824       1.09          1       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.07it/s]

                   all        322        284      0.873       0.81      0.876      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    129/300      9.06G     0.9045     0.5876      1.082          3       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.39it/s]

                   all        322        284      0.881      0.825      0.872      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    130/300      9.08G     0.8911     0.5951      1.081          5       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284      0.941      0.756       0.88      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    131/300      9.08G     0.8984     0.5969      1.082          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.39it/s]

                   all        322        284       0.91      0.838       0.89      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    132/300      9.11G     0.8686     0.5949      1.063          3       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.20it/s]

                   all        322        284      0.853      0.843      0.862      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    133/300      9.12G     0.8577      0.544      1.079          4       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.32it/s]

                   all        322        284      0.887      0.799      0.874      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    134/300      9.13G     0.8676     0.5756       1.08          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.48it/s]

                   all        322        284      0.898      0.824      0.887      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    135/300      9.14G     0.9034     0.5858      1.095          1       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.51it/s]

                   all        322        284      0.885      0.789      0.877      0.552

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    136/300      9.17G     0.8809     0.5548      1.096          3       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.28it/s]

                   all        322        284      0.895      0.822      0.879      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    137/300      9.18G     0.8694     0.5722      1.074          2       1024: 100%|██████████| 81/81 [01:19<00:00,  1.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.44it/s]

                   all        322        284       0.89      0.828      0.878      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    138/300       9.2G     0.8678     0.5841      1.081          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.27it/s]

                   all        322        284      0.856      0.836      0.859       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    139/300       9.2G      0.867     0.5753      1.067          4       1024: 100%|██████████| 81/81 [01:18<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.33it/s]

                   all        322        284      0.908      0.812      0.875      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    140/300      9.22G     0.8736     0.5579      1.068          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.16it/s]

                   all        322        284      0.902      0.831      0.882      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    141/300      9.24G     0.8729     0.5918      1.077          6       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.21it/s]

                   all        322        284      0.878      0.819      0.872       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    142/300      9.26G     0.8464     0.5421      1.049          3       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.13it/s]

                   all        322        284      0.924      0.821      0.881      0.559

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    143/300      9.26G     0.8557     0.5609      1.063          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.18it/s]

                   all        322        284      0.911      0.836      0.882      0.566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    144/300      9.28G      0.879     0.5828      1.069          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.17it/s]

                   all        322        284      0.881      0.812      0.862      0.574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    145/300       9.3G     0.8375     0.5683      1.063          1       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.25it/s]

                   all        322        284      0.895      0.827      0.887      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    146/300      9.31G     0.8387     0.5451      1.045          2       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.19it/s]

                   all        322        284       0.91      0.798      0.887      0.566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    147/300      9.32G     0.8463     0.5524      1.059          4       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.25it/s]

                   all        322        284      0.918      0.774      0.874      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    148/300      9.34G     0.8482     0.5686      1.052          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.22it/s]

                   all        322        284      0.902      0.813      0.879      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    149/300      9.36G     0.8214      0.541      1.039          0       1024: 100%|██████████| 81/81 [01:17<00:00,  1.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.10it/s]

                   all        322        284      0.888      0.832      0.883      0.536

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    150/300      9.37G     0.8103     0.5189       1.03          2       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.44it/s]

                   all        322        284      0.916      0.803      0.888      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    151/300      9.38G     0.8205     0.5581      1.039          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.15it/s]

                   all        322        284      0.882      0.836      0.883      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    152/300       9.4G     0.8184     0.5539      1.048          2       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.26it/s]

                   all        322        284      0.914      0.827      0.886       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    153/300      9.42G     0.8161     0.5338      1.045          2       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.37it/s]

                   all        322        284      0.927      0.797      0.872      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    154/300      9.43G     0.8166     0.5382      1.043          1       1024: 100%|██████████| 81/81 [01:17<00:00,  1.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.30it/s]

                   all        322        284      0.918      0.796       0.88       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    155/300      9.44G      0.817     0.5253      1.053          2       1024: 100%|██████████| 81/81 [01:19<00:00,  1.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.39it/s]

                   all        322        284      0.919        0.8      0.867      0.547

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    156/300      9.46G     0.8341     0.5408      1.055          3       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.33it/s]

                   all        322        284      0.939      0.777      0.863      0.555

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    157/300      9.48G     0.7998     0.5342       1.05          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.07it/s]

                   all        322        284      0.893      0.814      0.877      0.555

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    158/300      9.49G     0.8266     0.5436      1.048          4       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.46it/s]

                   all        322        284      0.924      0.779      0.881      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    159/300       9.5G     0.8159     0.5308      1.039          2       1024: 100%|██████████| 81/81 [01:18<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.42it/s]

                   all        322        284      0.894      0.839      0.891      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    160/300      9.52G     0.8228     0.5677      1.046          1       1024: 100%|██████████| 81/81 [01:15<00:00,  1.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.45it/s]

                   all        322        284      0.937      0.832      0.886      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    161/300      9.54G     0.8103      0.526      1.031          4       1024: 100%|██████████| 81/81 [01:14<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:09<00:00,  1.19it/s]

                   all        322        284      0.908        0.8      0.893      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    162/300      9.55G     0.8203     0.5393      1.045          2       1024: 100%|██████████| 81/81 [01:16<00:00,  1.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:08<00:00,  1.36it/s]

                   all        322        284      0.895      0.786      0.874       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    163/300      9.56G      0.814     0.5439      1.038          2       1024: 100%|██████████| 81/81 [01:19<00:00,  1.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:07<00:00,  1.38it/s]

                   all        322        284      0.863       0.84      0.875      0.552

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    164/300      9.58G     0.7882     0.5411      1.025          3       1024: 100%|██████████| 81/81 [01:20<00:00,  1.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:10<00:00,  1.08it/s]

                   all        322        284      0.877       0.86      0.898      0.558

EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 144, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

164 epochs completed in 3.929 hours.
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000/weights/last.pt, 5.6MB
Optimizer stripped from /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000/weights/best.pt, 5.6MB

Validating /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000/weights/best.pt...
Ultralytics 8.3.106 🚀 Python-3.11.11 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLO11n summary (fused): 100 layers, 2,583,517 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:15<00:00,  1.40s/it]

                   all        322        284      0.882      0.812      0.861      0.577
               Apoidea         10         10      0.944        0.7      0.729      0.456
             Arachnida         15         15      0.903      0.619      0.807      0.471
            Brachycera         16         16      0.889      0.875      0.934      0.652
            Coleoptera         51         51       0.89       0.98       0.99      0.758
            Formicidae         67         73      0.851      0.904      0.902      0.645
            Formicidae         95         95      0.902      0.937      0.952      0.614
            Syraphidae         24         24      0.793      0.667      0.718       0.44
Speed: 1.4ms preprocess, 6.8ms inference, 0.0ms loss, 4.4ms postprocess per image
Results saved to /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/train_yolo11n_reindexed_with_background_1000
🔍 Evaluating on validation set...

  0%|          | 0/322 [00:00<?, ?it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1576697.jpg: 1024x1024 1 Formicidae, 10.2ms
Speed: 8.2ms preprocess, 10.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

  0%|          | 1/322 [00:00<01:13,  4.36it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1174454.jpg: 864x1024 1 Brachycera, 48.7ms
Speed: 10.5ms preprocess, 48.7ms inference, 1.4ms postprocess per image at shape (1, 3, 864, 1024)

  1%|          | 2/322 [00:00<00:59,  5.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802958.jpg: 1024x1024 1 Coleoptera, 12.7ms
Speed: 6.6ms preprocess, 12.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1892601.jpg: 1024x1024 1 Formicidae, 9.8ms
Speed: 7.2ms preprocess, 9.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  1%|          | 4/322 [00:01<01:33,  3.38it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1035967.jpg: 1024x1024 (no detections), 9.4ms
Speed: 7.5ms preprocess, 9.4ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

  2%|▏         | 5/322 [00:01<01:15,  4.22it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869664.jpg: 1024x1024 1 Coleoptera, 10.0ms
Speed: 8.2ms preprocess, 10.0ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1658656.jpg: 1024x1024 1 Formicidae, 10.3ms
Speed: 11.5ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

  2%|▏         | 7/322 [00:01<00:48,  6.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1883122.jpg: 1024x1024 1 Formicidae, 9.0ms
Speed: 6.5ms preprocess, 9.0ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_650228.jpg: 1024x1024 1 Formicidae, 9.8ms
Speed: 7.1ms preprocess, 9.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_499672.jpg: 768x1024 1 Syraphidae, 50.2ms
Speed: 9.3ms preprocess, 50.2ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

  3%|▎         | 10/322 [00:01<00:37,  8.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1739113.jpg: 1024x1024 1 Coleoptera, 10.4ms
Speed: 6.7ms preprocess, 10.4ms inference, 1.2ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1626638.jpg: 1024x1024 1 Formicidae, 9.3ms
Speed: 7.0ms preprocess, 9.3ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1680229.jpg: 1024x1024 1 Formicidae, 10.1ms
Speed: 7.4ms preprocess, 10.1ms inference, 1.2ms postprocess per image at shape (1, 3, 1024, 1024)

  4%|▍         | 13/322 [00:01<00:27, 11.05it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1542164.jpg: 736x1024 1 Arachnida, 49.1ms
Speed: 6.8ms preprocess, 49.1ms inference, 2.1ms postprocess per image at shape (1, 3, 736, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1705644.jpg: 1024x1024 1 Formicidae, 12.4ms
Speed: 7.2ms preprocess, 12.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  5%|▍         | 15/322 [00:01<00:28, 10.70it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1703727.jpg: 768x1024 1 Brachycera, 12.7ms
Speed: 7.1ms preprocess, 12.7ms inference, 1.4ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1679968.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 8.0ms preprocess, 14.7ms inference, 2.4ms postprocess per image at shape (1, 3, 1024, 1024)

  5%|▌         | 17/322 [00:02<00:47,  6.45it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1199210.jpg: 800x1024 (no detections), 51.2ms
Speed: 7.0ms preprocess, 51.2ms inference, 0.7ms postprocess per image at shape (1, 3, 800, 1024)

  6%|▌         | 18/322 [00:02<00:50,  5.98it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1880449.jpg: 800x1024 3 Formicidaes, 12.2ms
Speed: 10.0ms preprocess, 12.2ms inference, 1.5ms postprocess per image at shape (1, 3, 800, 1024)

  6%|▌         | 19/322 [00:02<00:53,  5.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1720000.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.2ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1889657.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

  7%|▋         | 21/322 [00:03<00:40,  7.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541911.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661407.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 10.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  7%|▋         | 23/322 [00:03<00:34,  8.58it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1862511.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1032411.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  8%|▊         | 25/322 [00:03<00:28, 10.37it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869258.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1803945.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

  8%|▊         | 27/322 [00:03<00:24, 12.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214502.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 8.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1909134.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.2ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

  9%|▉         | 29/322 [00:03<00:21, 13.46it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_931985.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1886378.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.9ms preprocess, 14.1ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 10%|▉         | 31/322 [00:03<00:19, 14.71it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1719649.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1803987.jpg: 1024x1024 1 Coleoptera, 16.6ms
Speed: 9.8ms preprocess, 16.6ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 10%|█         | 33/322 [00:03<00:18, 15.43it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1760513.jpg: 992x1024 1 Formicidae, 49.0ms
Speed: 8.7ms preprocess, 49.0ms inference, 1.4ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1611112.jpg: 1024x1024 2 Formicidaes, 21.4ms
Speed: 7.1ms preprocess, 21.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 11%|█         | 35/322 [00:04<00:25, 11.43it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802908.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1540578.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 11%|█▏        | 37/322 [00:04<00:22, 12.91it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1701561.jpg: 1024x1024 1 Syraphidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1884094.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 12%|█▏        | 39/322 [00:04<00:20, 13.75it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1831577.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1537477.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 13%|█▎        | 41/322 [00:04<00:20, 13.96it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541858.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.7ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/925_2001820.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 13%|█▎        | 43/322 [00:04<00:18, 14.88it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661488.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1693286.jpg: 1024x1024 1 Brachycera, 14.1ms
Speed: 7.5ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 14%|█▍        | 45/322 [00:04<00:17, 15.68it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_758932.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.2ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1893193.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 15%|█▍        | 47/322 [00:04<00:17, 16.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1893214.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.0ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1560917.jpg: 800x1024 1 Apoidea, 12.8ms
Speed: 6.8ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 15%|█▌        | 49/322 [00:05<00:19, 13.68it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1626454.jpg: 1024x1024 2 Formicidaes, 14.8ms
Speed: 7.6ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1208580.jpg: 1024x1024 1 Formicidae, 16.7ms
Speed: 19.0ms preprocess, 16.7ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 16%|█▌        | 51/322 [00:05<00:19, 13.87it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869228.jpg: 1024x1024 1 Coleoptera, 17.5ms
Speed: 12.6ms preprocess, 17.5ms inference, 2.2ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/10_405031.jpg: 768x1024 3 Syraphidaes, 13.4ms
Speed: 10.4ms preprocess, 13.4ms inference, 1.5ms postprocess per image at shape (1, 3, 768, 1024)

 16%|█▋        | 53/322 [00:05<00:29,  9.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1589547.jpg: 1024x1024 1 Formicidae, 15.1ms
Speed: 13.2ms preprocess, 15.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1607684.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.9ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 17%|█▋        | 55/322 [00:05<00:27,  9.76it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1893434.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.3ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1626230.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 10.8ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 18%|█▊        | 57/322 [00:05<00:24, 10.93it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1544074.jpg: 800x1024 1 Syraphidae, 15.2ms
Speed: 11.3ms preprocess, 15.2ms inference, 1.7ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1680031.jpg: 1024x1024 1 Formicidae, 15.0ms
Speed: 10.7ms preprocess, 15.0ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 18%|█▊        | 59/322 [00:06<00:26, 10.03it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_488523.jpg: 1024x1024 2 Coleopteras, 1 Formicidae, 1 Formicidae, 14.1ms
Speed: 11.0ms preprocess, 14.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_931996.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.5ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 19%|█▉        | 61/322 [00:06<00:25, 10.13it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_14144.jpg: 576x1024 1 Syraphidae, 83.0ms
Speed: 7.9ms preprocess, 83.0ms inference, 2.1ms postprocess per image at shape (1, 3, 576, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1558288.jpg: 1024x1024 1 Formicidae, 15.7ms
Speed: 11.9ms preprocess, 15.7ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 20%|█▉        | 63/322 [00:06<00:35,  7.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/991_1813221.jpg: 800x1024 (no detections), 16.8ms
Speed: 11.1ms preprocess, 16.8ms inference, 0.8ms postprocess per image at shape (1, 3, 800, 1024)

 20%|█▉        | 64/322 [00:07<00:55,  4.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1885403.jpg: 768x1024 1 Formicidae, 13.8ms
Speed: 10.5ms preprocess, 13.8ms inference, 1.6ms postprocess per image at shape (1, 3, 768, 1024)

 20%|██        | 65/322 [00:07<00:56,  4.57it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/925_2001915.jpg: 1024x1024 1 Formicidae, 15.0ms
Speed: 11.3ms preprocess, 15.0ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/859_1832273.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.2ms preprocess, 14.2ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 21%|██        | 67/322 [00:07<00:41,  6.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1943955.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 11.0ms preprocess, 14.2ms inference, 2.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1705250.jpg: 1024x1024 1 Brachycera, 14.2ms
Speed: 14.1ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 21%|██▏       | 69/322 [00:07<00:35,  7.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1543606.jpg: 1024x1024 1 Brachycera, 1 Formicidae, 14.2ms
Speed: 14.3ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 22%|██▏       | 70/322 [00:07<00:34,  7.39it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1583461.jpg: 1024x1024 1 Formicidae, 16.3ms
Speed: 11.4ms preprocess, 16.3ms inference, 2.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661404.jpg: 1024x1024 1 Formicidae, 21.7ms
Speed: 11.4ms preprocess, 21.7ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 22%|██▏       | 72/322 [00:08<00:28,  8.86it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1590245.jpg: 1024x1024 1 Formicidae, 18.5ms
Speed: 15.3ms preprocess, 18.5ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214640.jpg: 800x1024 (no detections), 14.9ms
Speed: 11.6ms preprocess, 14.9ms inference, 0.8ms postprocess per image at shape (1, 3, 800, 1024)

 23%|██▎       | 74/322 [00:08<00:34,  7.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1539172.jpg: 1024x1024 1 Formicidae, 19.1ms
Speed: 12.6ms preprocess, 19.1ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1760492.jpg: 1024x1024 1 Arachnida, 16.8ms
Speed: 17.1ms preprocess, 16.8ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 24%|██▎       | 76/322 [00:08<00:29,  8.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/11_364929.jpg: 1024x1024 1 Arachnida, 20.2ms
Speed: 11.3ms preprocess, 20.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_499671.jpg: 800x1024 1 Syraphidae, 19.3ms
Speed: 11.7ms preprocess, 19.3ms inference, 2.0ms postprocess per image at shape (1, 3, 800, 1024)

 24%|██▍       | 78/322 [00:08<00:29,  8.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_310900.jpg: 800x1024 1 Syraphidae, 17.0ms
Speed: 11.7ms preprocess, 17.0ms inference, 2.0ms postprocess per image at shape (1, 3, 800, 1024)

 25%|██▍       | 79/322 [00:09<00:29,  8.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1859767.jpg: 1024x1024 (no detections), 20.2ms
Speed: 13.4ms preprocess, 20.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 25%|██▍       | 80/322 [00:09<00:32,  7.39it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1263711.jpg: 768x1024 1 Formicidae, 12.6ms
Speed: 6.5ms preprocess, 12.6ms inference, 1.6ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1730099.jpg: 1024x1024 1 Formicidae, 16.6ms
Speed: 13.0ms preprocess, 16.6ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 25%|██▌       | 82/322 [00:09<00:26,  9.01it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214505.jpg: 1024x1024 2 Coleopteras, 14.1ms
Speed: 7.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_983481.jpg: 800x1024 1 Apoidea, 1 Brachycera, 12.8ms
Speed: 6.9ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 26%|██▌       | 84/322 [00:09<00:27,  8.67it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1886365.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 7.3ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1129307.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.8ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 27%|██▋       | 86/322 [00:09<00:22, 10.47it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1304800.jpg: 864x1024 1 Coleoptera, 13.4ms
Speed: 8.0ms preprocess, 13.4ms inference, 1.4ms postprocess per image at shape (1, 3, 864, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1539168.jpg: 1024x1024 1 Formicidae, 15.0ms
Speed: 7.3ms preprocess, 15.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 27%|██▋       | 88/322 [00:09<00:22, 10.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1892602.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 8.0ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1943961.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 10.2ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 28%|██▊       | 90/322 [00:10<00:19, 11.81it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541881.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 7.0ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1793456.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 29%|██▊       | 92/322 [00:10<00:17, 12.99it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869227.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.2ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1862547.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 29%|██▉       | 94/322 [00:10<00:15, 14.31it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1680046.jpg: 800x1024 1 Formicidae, 14.1ms
Speed: 10.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1756184.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.1ms preprocess, 14.8ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 30%|██▉       | 96/322 [00:10<00:17, 12.70it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/10_376520.jpg: 576x1024 1 Syraphidae, 10.5ms
Speed: 5.6ms preprocess, 10.5ms inference, 1.3ms postprocess per image at shape (1, 3, 576, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1558357.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 7.0ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 30%|███       | 98/322 [00:11<00:59,  3.74it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1596975.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1296685.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 31%|███       | 100/322 [00:11<00:45,  4.88it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1542166.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_503051.jpg: 576x1024 1 Syraphidae, 10.5ms
Speed: 5.6ms preprocess, 10.5ms inference, 1.5ms postprocess per image at shape (1, 3, 576, 1024)

 32%|███▏      | 102/322 [00:12<00:40,  5.49it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869236.jpg: 1024x1024 1 Coleoptera, 15.0ms
Speed: 10.7ms preprocess, 15.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_935393.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 32%|███▏      | 104/322 [00:12<00:31,  6.91it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1739198.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/34_977656.jpg: 1024x1024 1 Coleoptera, 1 Formicidae, 16.1ms
Speed: 10.9ms preprocess, 16.1ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 33%|███▎      | 106/322 [00:12<00:27,  7.91it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661365.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_710011.jpg: 576x1024 1 Syraphidae, 10.8ms
Speed: 5.6ms preprocess, 10.8ms inference, 1.7ms postprocess per image at shape (1, 3, 576, 1024)

 34%|███▎      | 108/322 [00:12<00:27,  7.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1578215.jpg: 1024x1024 2 Formicidaes, 18.4ms
Speed: 7.0ms preprocess, 18.4ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1202777.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 7.3ms preprocess, 14.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 34%|███▍      | 110/322 [00:12<00:23,  9.11it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1680041.jpg: 800x1024 1 Formicidae, 13.1ms
Speed: 7.0ms preprocess, 13.1ms inference, 1.7ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870243.jpg: 1024x1024 1 Coleoptera, 14.9ms
Speed: 8.7ms preprocess, 14.9ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 35%|███▍      | 112/322 [00:13<00:21,  9.56it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1909301.jpg: 768x1024 1 Apoidea, 13.6ms
Speed: 7.6ms preprocess, 13.6ms inference, 1.4ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1726947.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 6.9ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 35%|███▌      | 114/322 [00:13<00:29,  7.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_495546.jpg: 1024x1024 1 Arachnida, 14.1ms
Speed: 7.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_650235.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 36%|███▌      | 116/322 [00:13<00:24,  8.46it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1719192.jpg: 1024x1024 1 Formicidae, 15.8ms
Speed: 8.2ms preprocess, 15.8ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1582009.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 37%|███▋      | 118/322 [00:13<00:20,  9.95it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870212.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 8.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1680043.jpg: 800x1024 1 Formicidae, 13.0ms
Speed: 8.0ms preprocess, 13.0ms inference, 1.4ms postprocess per image at shape (1, 3, 800, 1024)

 37%|███▋      | 120/322 [00:13<00:19, 10.35it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1887570.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.1ms preprocess, 14.8ms inference, 1.2ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1847163.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 38%|███▊      | 122/322 [00:14<00:16, 11.95it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1650775.jpg: 832x1024 1 Apoidea, 48.9ms
Speed: 7.2ms preprocess, 48.9ms inference, 1.4ms postprocess per image at shape (1, 3, 832, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1565506.jpg: 1024x1024 1 Formicidae, 14.9ms
Speed: 6.6ms preprocess, 14.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 39%|███▊      | 124/322 [00:14<00:17, 11.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661377.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214590.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 39%|███▉      | 126/322 [00:14<00:15, 12.71it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1225144.jpg: 864x1024 1 Brachycera, 13.3ms
Speed: 7.4ms preprocess, 13.3ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/925_1570493.jpg: 1024x1024 1 Formicidae, 15.1ms
Speed: 6.7ms preprocess, 15.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 40%|███▉      | 128/322 [00:14<00:16, 12.12it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1742462.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869201.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 40%|████      | 130/322 [00:14<00:14, 13.56it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1804174.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1947655.jpg: 1024x1024 1 Formicidae, 15.8ms
Speed: 10.4ms preprocess, 15.8ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 41%|████      | 132/322 [00:14<00:13, 14.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214629.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1883119.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 42%|████▏     | 134/322 [00:14<00:12, 15.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1550514.jpg: 1024x1024 (no detections), 14.1ms
Speed: 8.7ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541854.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 8.6ms preprocess, 14.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 42%|████▏     | 136/322 [00:15<00:14, 12.93it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802914.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1690164.jpg: 768x1024 2 Formicidaes, 12.7ms
Speed: 7.0ms preprocess, 12.7ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

 43%|████▎     | 138/322 [00:16<00:50,  3.67it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_934398.jpg: 1024x1024 1 Formicidae, 15.5ms
Speed: 11.9ms preprocess, 15.5ms inference, 2.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1263867.jpg: 768x1024 1 Formicidae, 12.6ms
Speed: 6.9ms preprocess, 12.6ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

 43%|████▎     | 140/322 [00:16<00:44,  4.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1707531.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 8.9ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1703711.jpg: 768x1024 1 Brachycera, 12.7ms
Speed: 6.9ms preprocess, 12.7ms inference, 1.8ms postprocess per image at shape (1, 3, 768, 1024)

 44%|████▍     | 142/322 [00:17<00:56,  3.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1035966.jpg: 1024x1024 1 Syraphidae, 15.2ms
Speed: 7.3ms preprocess, 15.2ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1585491.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.6ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 45%|████▍     | 144/322 [00:18<00:42,  4.16it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1707001.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_70781.jpg: 576x1024 1 Syraphidae, 10.8ms
Speed: 5.9ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 576, 1024)

 45%|████▌     | 146/322 [00:18<00:53,  3.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_15077.jpg: 576x1024 1 Syraphidae, 12.8ms
Speed: 8.1ms preprocess, 12.8ms inference, 1.7ms postprocess per image at shape (1, 3, 576, 1024)

 46%|████▌     | 147/322 [00:21<01:55,  1.51it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802938.jpg: 1024x1024 1 Coleoptera, 15.1ms
Speed: 10.9ms preprocess, 15.1ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1660000.jpg: 1024x1024 1 Formicidae, 15.4ms
Speed: 11.0ms preprocess, 15.4ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 46%|████▋     | 149/322 [00:21<01:20,  2.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1563515.jpg: 960x1024 2 Formicidaes, 83.8ms
Speed: 13.1ms preprocess, 83.8ms inference, 1.9ms postprocess per image at shape (1, 3, 960, 1024)

 47%|████▋     | 150/322 [00:21<01:14,  2.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1788482.jpg: 1024x1024 1 Formicidae, 20.7ms
Speed: 16.0ms preprocess, 20.7ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1660109.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 11.5ms preprocess, 14.2ms inference, 2.0ms postprocess per image at shape (1, 3, 1024, 1024)

 47%|████▋     | 152/322 [00:21<00:52,  3.24it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214573.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 10.9ms preprocess, 14.2ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1544081.jpg: 800x1024 1 Syraphidae, 21.3ms
Speed: 12.9ms preprocess, 21.3ms inference, 2.6ms postprocess per image at shape (1, 3, 800, 1024)

 48%|████▊     | 154/322 [00:22<00:43,  3.91it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1578478.jpg: 1024x1024 2 Formicidaes, 15.2ms
Speed: 10.7ms preprocess, 15.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/11_364920.jpg: 1024x1024 1 Arachnida, 16.2ms
Speed: 11.0ms preprocess, 16.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 48%|████▊     | 156/322 [00:22<00:32,  5.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/34_998277.jpg: 1024x1024 1 Coleoptera, 19.7ms
Speed: 15.0ms preprocess, 19.7ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1551894.jpg: 1024x1024 1 Formicidae, 17.2ms
Speed: 10.6ms preprocess, 17.2ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 49%|████▉     | 158/322 [00:22<00:26,  6.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_15503.jpg: 576x1024 1 Apoidea, 10.4ms
Speed: 5.4ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 576, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1788275.jpg: 736x1024 1 Formicidae, 12.4ms
Speed: 6.5ms preprocess, 12.4ms inference, 1.3ms postprocess per image at shape (1, 3, 736, 1024)

 50%|████▉     | 160/322 [00:23<00:50,  3.22it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1708731.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 8.2ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541890.jpg: 1024x1024 1 Formicidae, 19.9ms
Speed: 6.8ms preprocess, 19.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 50%|█████     | 162/322 [00:23<00:37,  4.23it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1886833.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1564042.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 51%|█████     | 164/322 [00:24<00:29,  5.45it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1709230.jpg: 1024x1024 1 Formicidae, 16.0ms
Speed: 8.5ms preprocess, 16.0ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1803311.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 52%|█████▏    | 166/322 [00:24<00:22,  6.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1833731.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 8.7ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_650212.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 52%|█████▏    | 168/322 [00:24<00:18,  8.41it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1540596.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_310895.jpg: 864x1024 1 Syraphidae, 13.5ms
Speed: 7.8ms preprocess, 13.5ms inference, 1.3ms postprocess per image at shape (1, 3, 864, 1024)

 53%|█████▎    | 170/322 [00:24<00:16,  9.48it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1708646.jpg: 768x1024 1 Formicidae, 12.8ms
Speed: 7.0ms preprocess, 12.8ms inference, 1.4ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1577457.jpg: 1024x1024 2 Formicidaes, 14.7ms
Speed: 8.2ms preprocess, 14.7ms inference, 1.7ms postprocess per image at shape (1, 3, 1024, 1024)

 53%|█████▎    | 172/322 [00:24<00:21,  6.87it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1872752.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1576661.jpg: 800x1024 1 Formicidae, 12.8ms
Speed: 6.9ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 54%|█████▍    | 174/322 [00:25<00:18,  7.84it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1706996.jpg: 1024x1024 1 Formicidae, 16.3ms
Speed: 7.6ms preprocess, 16.3ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1421739.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 55%|█████▍    | 176/322 [00:25<00:15,  9.18it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1626259.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 7.5ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1709242.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 55%|█████▌    | 178/322 [00:25<00:13, 10.38it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1628691.jpg: 800x1024 1 Formicidae, 13.2ms
Speed: 6.9ms preprocess, 13.2ms inference, 1.8ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802936.jpg: 1024x1024 1 Coleoptera, 14.7ms
Speed: 6.8ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 56%|█████▌    | 180/322 [00:25<00:13, 10.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1602609.jpg: 1024x1024 1 Arachnida, 14.1ms
Speed: 6.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_650233.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 10.1ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 57%|█████▋    | 182/322 [00:25<00:11, 11.99it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/925_1999521.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1722814.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 13.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 57%|█████▋    | 184/322 [00:25<00:10, 13.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541874.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.4ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1701558.jpg: 800x1024 (no detections), 12.9ms
Speed: 6.7ms preprocess, 12.9ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

 58%|█████▊    | 186/322 [00:26<00:12, 11.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1621246.jpg: 1024x1024 1 Formicidae, 15.2ms
Speed: 7.3ms preprocess, 15.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_766602.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 10.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 58%|█████▊    | 188/322 [00:26<00:10, 12.71it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/925_2008658.jpg: 1024x1024 1 Brachycera, 14.2ms
Speed: 9.0ms preprocess, 14.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1297358.jpg: 1024x1024 1 Brachycera, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 59%|█████▉    | 190/322 [00:26<00:10, 12.28it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1590559.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.9ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1796311.jpg: 1024x1024 1 Formicidae, 1 Formicidae, 14.1ms
Speed: 8.8ms preprocess, 14.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 60%|█████▉    | 192/322 [00:26<00:09, 13.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1559305.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1701608.jpg: 1024x1024 (no detections), 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 60%|██████    | 194/322 [00:26<00:09, 13.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1709231.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.6ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_650227.jpg: 1024x1024 1 Formicidae, 15.4ms
Speed: 11.9ms preprocess, 15.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 61%|██████    | 196/322 [00:26<00:08, 14.10it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1692863.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.5ms preprocess, 14.1ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541905.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 61%|██████▏   | 198/322 [00:26<00:08, 15.22it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1701569.jpg: 1024x1024 1 Syraphidae, 14.2ms
Speed: 10.8ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1265110.jpg: 768x1024 1 Formicidae, 12.6ms
Speed: 6.6ms preprocess, 12.6ms inference, 1.4ms postprocess per image at shape (1, 3, 768, 1024)

 62%|██████▏   | 200/322 [00:27<00:09, 12.71it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661427.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 10.5ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870096.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 63%|██████▎   | 202/322 [00:27<00:08, 13.99it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1803962.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 9.2ms preprocess, 14.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870125.jpg: 1024x1024 1 Coleoptera, 16.0ms
Speed: 10.2ms preprocess, 16.0ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 63%|██████▎   | 204/322 [00:27<00:08, 14.69it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1803326.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214632.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.4ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 64%|██████▍   | 206/322 [00:27<00:07, 14.91it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802976.jpg: 1024x1024 1 Coleoptera, 14.4ms
Speed: 10.3ms preprocess, 14.4ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1630250.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 65%|██████▍   | 208/322 [00:27<00:07, 15.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1610847.jpg: 800x1024 2 Formicidaes, 12.9ms
Speed: 8.2ms preprocess, 12.9ms inference, 1.5ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1658717.jpg: 1024x1024 1 Formicidae, 15.0ms
Speed: 7.2ms preprocess, 15.0ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 65%|██████▌   | 210/322 [00:27<00:09, 11.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870208.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 9.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1542159.jpg: 928x1024 1 Arachnida, 49.4ms
Speed: 7.8ms preprocess, 49.4ms inference, 1.4ms postprocess per image at shape (1, 3, 928, 1024)

 66%|██████▌   | 212/322 [00:27<00:09, 11.19it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1893238.jpg: 1024x1024 1 Formicidae, 14.6ms
Speed: 9.3ms preprocess, 14.6ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870113.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 66%|██████▋   | 214/322 [00:28<00:08, 12.67it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1722852.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 10.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/10_368619.jpg: 800x1024 1 Brachycera, 1 Formicidae, 13.4ms
Speed: 6.6ms preprocess, 13.4ms inference, 1.9ms postprocess per image at shape (1, 3, 800, 1024)

 67%|██████▋   | 216/322 [00:28<00:10,  9.95it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/859_1834070.jpg: 1024x1024 1 Formicidae, 14.8ms
Speed: 7.5ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1884047.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.8ms preprocess, 14.2ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

 68%|██████▊   | 218/322 [00:28<00:09, 11.36it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1709220.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.6ms preprocess, 14.2ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/11_364909.jpg: 1024x1024 2 Arachnidas, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 68%|██████▊   | 220/322 [00:28<00:08, 12.59it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1703719.jpg: 768x1024 1 Brachycera, 12.7ms
Speed: 6.5ms preprocess, 12.7ms inference, 1.3ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_939952.jpg: 1024x1024 (no detections), 14.8ms
Speed: 7.0ms preprocess, 14.8ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 69%|██████▉   | 222/322 [00:28<00:08, 11.81it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870099.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 6.7ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1730092.jpg: 1024x1024 1 Formicidae, 1 Formicidae, 14.1ms
Speed: 8.9ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 70%|██████▉   | 224/322 [00:28<00:07, 12.64it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_13827.jpg: 576x1024 1 Syraphidae, 10.3ms
Speed: 5.4ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 576, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1578214.jpg: 1024x1024 1 Formicidae, 14.9ms
Speed: 7.8ms preprocess, 14.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 70%|███████   | 226/322 [00:29<00:08, 11.34it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541869.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.1ms preprocess, 14.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_311300.jpg: 1024x1024 1 Brachycera, 1 Coleoptera, 1 Syraphidae, 14.1ms
Speed: 6.4ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 71%|███████   | 228/322 [00:29<00:07, 12.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_930779.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.4ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1707082.jpg: 1024x1024 2 Formicidaes, 14.1ms
Speed: 7.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 71%|███████▏  | 230/322 [00:29<00:07, 12.32it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_661381.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1682266.jpg: 800x1024 2 Formicidaes, 12.9ms
Speed: 6.8ms preprocess, 12.9ms inference, 1.4ms postprocess per image at shape (1, 3, 800, 1024)

 72%|███████▏  | 232/322 [00:29<00:07, 12.07it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1705255.jpg: 768x1024 1 Brachycera, 12.7ms
Speed: 7.1ms preprocess, 12.7ms inference, 1.4ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802998.jpg: 1024x1024 1 Coleoptera, 14.9ms
Speed: 8.2ms preprocess, 14.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 73%|███████▎  | 234/322 [00:31<00:27,  3.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870207.jpg: 1024x1024 1 Coleoptera, 14.2ms
Speed: 10.2ms preprocess, 14.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1889633.jpg: 1024x1024 1 Formicidae, 14.4ms
Speed: 6.8ms preprocess, 14.4ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 73%|███████▎  | 236/322 [00:31<00:20,  4.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1891801.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1545097.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 74%|███████▍  | 238/322 [00:31<00:16,  5.14it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1690283.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 7.1ms preprocess, 14.2ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1354_1886831.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.4ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 75%|███████▍  | 240/322 [00:31<00:13,  6.30it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1572039.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 8.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_935478.jpg: 1024x1024 1 Formicidae, 65.1ms
Speed: 25.4ms preprocess, 65.1ms inference, 8.2ms postprocess per image at shape (1, 3, 1024, 1024)

 75%|███████▌  | 242/322 [00:32<00:11,  6.71it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1689926.jpg: 800x1024 (no detections), 78.7ms
Speed: 36.9ms preprocess, 78.7ms inference, 4.2ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1705267.jpg: 768x1024 1 Formicidae, 47.4ms
Speed: 16.3ms preprocess, 47.4ms inference, 6.8ms postprocess per image at shape (1, 3, 768, 1024)

 76%|███████▌  | 244/322 [00:33<00:22,  3.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1680040.jpg: 800x1024 (no detections), 15.2ms
Speed: 10.6ms preprocess, 15.2ms inference, 0.7ms postprocess per image at shape (1, 3, 800, 1024)

 76%|███████▌  | 245/322 [00:34<00:33,  2.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1862525.jpg: 1024x1024 1 Coleoptera, 15.4ms
Speed: 10.3ms preprocess, 15.4ms inference, 2.2ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541903.jpg: 1024x1024 1 Formicidae, 20.4ms
Speed: 11.9ms preprocess, 20.4ms inference, 3.4ms postprocess per image at shape (1, 3, 1024, 1024)

 77%|███████▋  | 247/322 [00:34<00:23,  3.15it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541909.jpg: 928x1024 1 Formicidae, 15.8ms
Speed: 12.1ms preprocess, 15.8ms inference, 1.9ms postprocess per image at shape (1, 3, 928, 1024)

 77%|███████▋  | 248/322 [00:34<00:21,  3.47it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_541855.jpg: 1024x1024 1 Formicidae, 15.1ms
Speed: 13.7ms preprocess, 15.1ms inference, 1.6ms postprocess per image at shape (1, 3, 1024, 1024)

 77%|███████▋  | 249/322 [00:34<00:20,  3.60it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1680044.jpg: 800x1024 (no detections), 13.3ms
Speed: 10.9ms preprocess, 13.3ms inference, 0.7ms postprocess per image at shape (1, 3, 800, 1024)

 78%|███████▊  | 250/322 [00:35<00:29,  2.46it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_939772.jpg: 1024x1024 (no detections), 15.3ms
Speed: 10.3ms preprocess, 15.3ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_938706.jpg: 800x1024 1 Apoidea, 22.6ms
Speed: 10.5ms preprocess, 22.6ms inference, 2.0ms postprocess per image at shape (1, 3, 800, 1024)

 78%|███████▊  | 252/322 [00:36<00:20,  3.41it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1700897.jpg: 768x1024 1 Brachycera, 18.1ms
Speed: 10.1ms preprocess, 18.1ms inference, 1.8ms postprocess per image at shape (1, 3, 768, 1024)

 79%|███████▊  | 253/322 [00:36<00:25,  2.76it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1943984.jpg: 1024x1024 1 Coleoptera, 28.9ms
Speed: 13.7ms preprocess, 28.9ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1578240.jpg: 1024x1024 2 Formicidaes, 17.4ms
Speed: 11.2ms preprocess, 17.4ms inference, 2.1ms postprocess per image at shape (1, 3, 1024, 1024)

 79%|███████▉  | 255/322 [00:36<00:17,  3.94it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870089.jpg: 1024x1024 1 Coleoptera, 18.8ms
Speed: 13.9ms preprocess, 18.8ms inference, 2.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1604091.jpg: 1024x1024 1 Formicidae, 16.8ms
Speed: 11.7ms preprocess, 16.8ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 80%|███████▉  | 257/322 [00:37<00:12,  5.21it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1446473.jpg: 1024x1024 1 Formicidae, 14.4ms
Speed: 15.1ms preprocess, 14.4ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1700912.jpg: 800x1024 1 Brachycera, 12.8ms
Speed: 6.9ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

 80%|████████  | 259/322 [00:37<00:10,  5.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1746506.jpg: 1024x1024 1 Formicidae, 14.9ms
Speed: 10.8ms preprocess, 14.9ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1214613.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 81%|████████  | 261/322 [00:37<00:08,  7.52it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_934128.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 10.0ms preprocess, 14.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1563281.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 6.9ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 82%|████████▏ | 263/322 [00:37<00:06,  9.17it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1802956.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 11.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1721874.jpg: 1024x1024 1 Formicidae, 14.2ms
Speed: 7.1ms preprocess, 14.2ms inference, 1.5ms postprocess per image at shape (1, 3, 1024, 1024)

 82%|████████▏ | 265/322 [00:37<00:05, 10.87it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1564396.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 9.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1577222.jpg: 1024x1024 1 Formicidae, 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

 83%|████████▎ | 267/322 [00:37<00:04, 12.27it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1551883.jpg: 1024x1024 1 Formicidae, 14.9ms
Speed: 10.5ms preprocess, 14.9ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1943945.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 7.0ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 84%|████████▎ | 269/322 [00:37<00:03, 13.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/562_1708728.jpg: 992x1024 1 Formicidae, 14.6ms
Speed: 7.4ms preprocess, 14.6ms inference, 1.3ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/991_1813226.jpg: 896x1024 (no detections), 52.9ms
Speed: 7.7ms preprocess, 52.9ms inference, 0.6ms postprocess per image at shape (1, 3, 896, 1024)

 84%|████████▍ | 271/322 [00:38<00:04, 10.50it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_1143735.jpg: 1024x1024 1 Brachycera, 14.7ms
Speed: 6.9ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1803155.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 9.2ms preprocess, 14.1ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)

 85%|████████▍ | 273/322 [00:38<00:04, 11.90it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/827_1551881.jpg: 992x1024 1 Formicidae, 14.7ms
Speed: 7.5ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1869001.jpg: 1024x1024 1 Coleoptera, 14.8ms
Speed: 8.8ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 85%|████████▌ | 275/322 [00:38<00:03, 12.77it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/1_310899.jpg: 800x1024 1 Syraphidae, 12.8ms
Speed: 8.1ms preprocess, 12.8ms inference, 1.3ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/265_935599.jpg: 1024x1024 1 Syraphidae, 14.8ms
Speed: 8.1ms preprocess, 14.8ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

 86%|████████▌ | 277/322 [00:38<00:03, 12.44it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/793_1870086.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 10.6ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-24_10-25-00-304492_pos3.95_rate4_imx708_0.jpg.jpg: 608x1024 (no detections), 51.6ms
Speed: 5.7ms preprocess, 51.6ms inference, 0.9ms postprocess per image at shape (1, 3, 608, 1024)

 87%|████████▋ | 279/322 [00:38<00:03, 13.08it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-25_09-18-39-511370_pos3.95_rate4_imx708_0.jpg.jpg: 992x1024 (no detections), 14.6ms
Speed: 8.0ms preprocess, 14.6ms inference, 0.6ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-18_11-08-46-636194_pos3.8_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.9ms
Speed: 12.4ms preprocess, 14.9ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 87%|████████▋ | 281/322 [00:38<00:03, 13.46it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-20_06-36-25-929779_pos3.0_rate4_imx708_0.jpg.jpg: 992x1024 (no detections), 14.7ms
Speed: 8.4ms preprocess, 14.7ms inference, 0.6ms postprocess per image at shape (1, 3, 992, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-01-06_14-47-53-580830_pos5.35_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.7ms
Speed: 7.5ms preprocess, 14.7ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 88%|████████▊ | 283/322 [00:38<00:02, 13.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-14_08-31-58-192634_pos3.4_rate4_imx708_0.jpg.jpg: 1024x1024 1 Brachycera, 1 Syraphidae, 14.1ms
Speed: 10.5ms preprocess, 14.1ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-20_10-25-33-583736_pos3.7_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 8.9ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 89%|████████▊ | 285/322 [00:39<00:02, 13.61it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-09_07-40-57-682239_pos3.7_rate4_imx708_0.jpg.jpg: 736x1024 (no detections), 12.5ms
Speed: 6.7ms preprocess, 12.5ms inference, 0.6ms postprocess per image at shape (1, 3, 736, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-24_14-28-07-685324_pos3.85_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.7ms
Speed: 6.9ms preprocess, 14.7ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 89%|████████▉ | 287/322 [00:39<00:02, 12.56it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-18_11-07-09-662125_pos3.8_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 8.7ms preprocess, 14.2ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-19_07-57-16-834018_pos3.25_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 9.1ms preprocess, 14.2ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 90%|████████▉ | 289/322 [00:39<00:02, 12.41it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2024-12-26_14-44-05-369270_pos3.6_rate4_imx708_0.jpg.jpg: 800x1024 (no detections), 12.8ms
Speed: 6.7ms preprocess, 12.8ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-23_07-51-31-858587_pos3.4_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 15.0ms
Speed: 10.6ms preprocess, 15.0ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

 90%|█████████ | 291/322 [00:39<00:02, 11.65it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2024-12-14_06-52-33-774312_pos3.85_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 11.9ms preprocess, 14.2ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-05_09-38-53-225933_pos3.6_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 11.8ms preprocess, 14.1ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

 91%|█████████ | 293/322 [00:39<00:02, 12.97it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-20_07-45-05-665875_pos3.2_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 8.8ms preprocess, 14.2ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-20_08-00-44-391918_pos3.2_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 7.5ms preprocess, 14.2ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

 92%|█████████▏| 295/322 [00:39<00:02, 12.74it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2024-11-17_13-56-44-910211_pos5.35_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 12.4ms preprocess, 14.2ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-19_08-41-19-772067_pos3.45_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 10.5ms preprocess, 14.1ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)

 92%|█████████▏| 297/322 [00:40<00:01, 13.83it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-05_11-57-10-634986_pos3.6_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 8.1ms preprocess, 14.1ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-21_11-51-21-433752_pos3.45_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 10.9ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 93%|█████████▎| 299/322 [00:40<00:01, 14.97it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-17_07-22-18-121730_pos3.55_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 15.5ms
Speed: 6.9ms preprocess, 15.5ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-08_14-15-18-105208_pos3.475_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 8.9ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 93%|█████████▎| 301/322 [00:40<00:01, 15.85it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2024-11-22_12-20-53-380272_pos3.6_rate4_imx708_0.jpg.jpg: 1024x1024 1 Coleoptera, 14.1ms
Speed: 10.7ms preprocess, 14.1ms inference, 1.8ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-11_18-05-50-254766_pos3.475_rate4_imx708_0.jpg.jpg: 992x1024 (no detections), 14.6ms
Speed: 6.5ms preprocess, 14.6ms inference, 0.6ms postprocess per image at shape (1, 3, 992, 1024)

 94%|█████████▍| 303/322 [00:40<00:01, 16.06it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-18_13-17-22-506075_pos3.65_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.8ms
Speed: 9.3ms preprocess, 14.8ms inference, 1.9ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-19_07-54-15-353537_pos3.25_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 9.3ms preprocess, 14.2ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 95%|█████████▍| 305/322 [00:40<00:01, 14.09it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2024-11-15_08-05-47-947868_pos5.35_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 11.6ms preprocess, 14.2ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/7.jpg: 1024x1024 (no detections), 14.1ms
Speed: 9.8ms preprocess, 14.1ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

 95%|█████████▌| 307/322 [00:40<00:00, 15.29it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-24_09-02-50-097487_pos3.75_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 10.7ms preprocess, 14.2ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-11_15-28-40-727194_pos3.475_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.2ms
Speed: 10.2ms preprocess, 14.2ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

 96%|█████████▌| 309/322 [00:40<00:00, 15.98it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/17.jpg: 1024x1024 1 Formicidae, 14.7ms
Speed: 13.7ms preprocess, 14.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-14_08-11-13-400480_pos3.4_rate4_imx708_0.jpg.jpg: 800x1024 (no detections), 12.9ms
Speed: 6.9ms preprocess, 12.9ms inference, 0.7ms postprocess per image at shape (1, 3, 800, 1024)

 97%|█████████▋| 311/322 [00:40<00:00, 14.20it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-23_07-48-52-318298_pos3.4_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 15.0ms
Speed: 11.8ms preprocess, 15.0ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-14_10-32-22-401880_pos3.4_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 10.5ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 97%|█████████▋| 313/322 [00:41<00:00, 15.40it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-18_07-25-53-986422_pos3.2_rate4_imx708_0.jpg.jpg: 768x1024 (no detections), 13.0ms
Speed: 6.8ms preprocess, 13.0ms inference, 0.7ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-09_06-28-09-149341_pos3.7_rate4_imx708_0.jpg.jpg: 544x1024 (no detections), 52.9ms
Speed: 5.0ms preprocess, 52.9ms inference, 0.8ms postprocess per image at shape (1, 3, 544, 1024)

 98%|█████████▊| 315/322 [00:41<00:00, 11.85it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-18_10-35-11-522744_pos3.8_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.8ms
Speed: 9.0ms preprocess, 14.8ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-14_07-54-29-202997_pos3.4_rate4_imx708_0.jpg.jpg: 832x1024 (no detections), 13.2ms
Speed: 7.5ms preprocess, 13.2ms inference, 0.6ms postprocess per image at shape (1, 3, 832, 1024)

 98%|█████████▊| 317/322 [00:41<00:00, 10.80it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-12_13-12-24-008307_pos3.4_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.8ms
Speed: 11.0ms preprocess, 14.8ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-11_09-21-15-597252_pos3.475_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 7.3ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

 99%|█████████▉| 319/322 [00:41<00:00, 12.42it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-21_06-53-19-783117_pos3.3_rate4_imx708_0.jpg.jpg: 768x1024 (no detections), 12.7ms
Speed: 6.8ms preprocess, 12.7ms inference, 0.6ms postprocess per image at shape (1, 3, 768, 1024)

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-14_08-00-28-549463_pos3.4_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.8ms
Speed: 10.6ms preprocess, 14.8ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

100%|█████████▉| 321/322 [00:42<00:00,  6.63it/s]

image 1/1 /content/drive/MyDrive/hand-picked-data/2024-04-11-reindexed_with_background/val/images/2025-03-08_10-06-47-260219_pos3.475_rate4_imx708_0.jpg.jpg: 1024x1024 (no detections), 14.1ms
Speed: 6.8ms preprocess, 14.1ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)

100%|██████████| 322/322 [00:42<00:00,  7.60it/s]

✅ Evaluation Summary:
Precision: 0.00%
Recall:    0.00%
F1 Score:  0.00%
→ FP saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/false_positives
→ FN saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/false_negatives
→ MC saved to: /content/drive/MyDrive/YOLOv11_Results/reindexed_with_background_1000/misclassified